[VAX-532] Introduce depency info for row add-wins semantic
electric-sql/electric pull request #100
Opened 2023-02-22 09:22 UTC by define-null

Tags mechanism is added to Satellite protocol to track row dependencies in the form similar to ORSet, to provide add-wins semantics for concurrent operations. Tags stored with the row determine wherever or not row exists.

2023-02-23 10:22 UTC, icehaunter reviewed
Nice work, I think the Electric side is clear to me, although I had a couple of questions

2023-02-23 10:22 UTC, icehaunter commented on lib/electric/replication/changes.ex
> +                )
Could it have been deleted at this point already by a simultaneos deletion?

2023-02-23 10:22 UTC, icehaunter commented on lib/electric/replication/metadata.ex
> +  # The scheama itself is a crdt map with reset funcationality, where
```suggestion
  # The schema itself is a CRDT map with reset functionality, where
```

2023-02-23 10:22 UTC, icehaunter commented on lib/electric/replication/row.ex
> +  # setting field to default value is effectively removing the field
```suggestion
  # The schema itself is a CRDT map with reset functionality, where
```

2023-02-23 10:22 UTC, icehaunter commented on test/support/satellite_table.ex
> +    {:ok, conn} = SatelliteWsClient.connect_and_spawn(opts)
Dialyzer complains that `SatelliteWsClient.connect_and_spawn/1` spec returns `pid()`, not `{:ok, pid()}`

2023-02-23 10:22 UTC, icehaunter commented on test/electric/to_vaxine_test.exs
>    @id Ecto.UUID.generate()
Is this meant to be constant and shared for the entire test suite run? And, if so, why not hardcode smth like `00000000-0000-0000-0000-000000000000` to ease matching/verification?

2023-02-23 10:22 UTC, icehaunter commented on test/electric/to_vaxine_test.exs
>    @row Row.new("fake", "to_vaxine_test", %{"id" => @id}, ["id"])
When running tests:

```log
warning: module attribute @row was set but never used
  test/electric/to_vaxine_test.exs:11
```

2023-02-23 10:22 UTC, icehaunter requested changes
Nice work, I think the Electric side is clear to me, although I had a couple of questions

2023-02-23 10:30 UTC, icehaunter commented on lib/electric/replication/vaxine/transaction_builder.ex
> +  defp build_transaction_int(entries, commit_timestamp) do
I know this is a nitpick, but I "stumbled" over this suffix trying to understand what it has to do with `integer`. May I ask you to name this private function `do_build_transaction/2` or `build_transaction_internal`? `_int` suffix is not very common in Elixir codebases in my experience, although I appreciate that this is very minor.

2023-02-23 10:31 UTC, define-null commented on lib/electric/replication/vaxine/transaction_builder.ex
> +    :orddict.fetch_keys(internal_value)
I'm not sure wherever `Keyword` interface fully map with `orddict`. I though it was more aligned with `proplists`. So I'm just caling whatever is used in 

But the thing is - we break abstraction here, looking into the type internal. We either should propagate `antidote_type:value()` from Vaxine in the first place, or just call module:value().

2023-02-23 10:31 UTC, icehaunter commented on test/electric/to_vaxine_test.exs
>    @id Ecto.UUID.generate()
Sorry, didn't notice that this wasn't part of the PR at all. Disregard this then if you don't want to address now.

2023-02-23 10:31 UTC, icehaunter commented on test/electric/to_vaxine_test.exs
>    @row Row.new("fake", "to_vaxine_test", %{"id" => @id}, ["id"])
Sorry, didn't notice that this wasn't part of the PR at all. Disregard this then if you don't want to address now.

2023-02-23 10:33 UTC, define-null commented on lib/electric/replication/vaxine/transaction_builder.ex
> +    # "Deteled" is implemented as an OR-set, however setting field to a bottom value
Bottom value of the CRDT type, is an initial value of the type, when the object is created. For example for a Set it's an empty set representation.

2023-02-23 10:35 UTC, define-null commented on test/electric/to_vaxine_test.exs
>    @id Ecto.UUID.generate()
I think the idea here, is to be able to rerun the test without starting/stoping Vaxine.

2023-02-23 10:37 UTC, icehaunter commented on lib/electric/replication/vaxine/transaction_builder.ex
> +    :orddict.fetch_keys(internal_value)
I see. Yeah, breaking abstraction here isn't great, I've noticed your comment above

2023-02-23 10:42 UTC, icehaunter commented on test/electric/to_vaxine_test.exs
>    @id Ecto.UUID.generate()
Ah, so the test kinda doesn't clean up after itself properly because Vaxine? Makes sense, thanks.

2023-02-23 10:44 UTC, define-null commented on lib/electric/replication/vaxine/transaction_builder.ex
> +    case deleted == [] or deleted == nil do
As far as I understood implementation detail - when the field is deleted in the map, the field is actually removed, so we get `nil`, when trying to read materialized value. However when we create an object with empty set, it's gonna be present in the map when the whole key is introduced. This behaviour is dependent on the map crdt type that we use.

Thinking more about it - this set should always have at least 1 element in it, when created. So we do not create a row without setting tag in the deleted set. However given that we can get `nil` or `[]` depending on the crdt being used I think it's safer to keep empty list check as well.

2023-02-23 10:49 UTC, define-null commented on lib/electric/replication/changes.ex
> +                )
It could, but once the row is present in Vaxine it doesn't go away. So reload should always succeed

2023-02-23 11:31 UTC, icehaunter commented on lib/electric/replication/row.ex
> +    field(:deleted?, Vax.Types.Set, type: :string)
I think I have one last question: will this cause a hard break on all rows already in Vaxine if we update Electric for an existing cluster?

2023-02-23 11:32 UTC, define-null commented on lib/electric/replication/row.ex
> +    field(:deleted?, Vax.Types.Set, type: :string)
Yes, it's a non-compatible change.

2023-02-23 14:01 UTC, icehaunter approved these changes

2023-03-28 15:28 UTC, icehaunter approved these changes

2023-03-29 08:00 UTC, merged