(WIP) feat (client): support for PG on the client
electric-sql/electric pull request #1038
Opened 2024-03-07 14:16 UTC by kevin-dp

This PR adds support for Postgres on the client:
- adds DB drivers for Postgres in NodeJS and in Tauri
- modifies the initial Electric schema (meta tables)
- modifies the queries executed by the `BundleMigrator`
- modifies the triggers to also support PG
- modifies the Satellite process to also support PG
- modifies the CLI to bundle both SQLite and PG migrations

**To test** this PR you will need to:
- use a local build of Electric from `alco/vax-1659-postgresql-dialect`
- npm pack the generator
- use the packed generator in the ts-client
- npm pack the ts-client
- use the packed version of ts-client in the example app (and use node-postgres or tauri-postgres driver)

A couple of things to note:
- Had to change a trigger in both SQLite and PG for storing the JSON of a row's PK:
  - In PG, `jsonb` adds whitespace and re-orders keys. Whereas, SQLite has no whitespace and preserves the ordering of keys. So in PG we use `json` instead of `jsonb` and strip any whitespace but that has the side effect of also removing `null` values. Hence, we also remove `null` values in SQLite.
- The Postgres version does not yet support infinity values and/or `NaN` for real numbers.
- Postgres requires migrations coming from Electric to define all FKs as `DEFERRABLE`
- We no longer defer foreign key checks before applying an incoming transaction as PG does not like deferred constraints when trying to apply some DDL. This happens because PG wants to run all trigger events before applying DDL but they are deferred so they are only allowed to run when committing so PG is stuck. So if a TX contains DML and DDL then when it encounters the DDL we get errors like this: `cannot ALTER TABLE "parent" because it has pending trigger events`

Remains to be done (perhaps in a follow-up PR):
- e2e tests for PG client
- check data type support (boolean, real, json, etc.) -> `REAL`s don't work for sure

2024-04-03 07:55 UTC, kevin-dp commented
Additional TODO:

- Stefanos added BLOB support on main. Will need to also add it here

2024-04-23 13:31 UTC, msfstef reviewed
Amazing work! Left a few minor comments, might do a second pass/review later!

2024-04-23 13:31 UTC, msfstef commented on clients/typescript/src/client/model/builder.ts
> +      .select({ autoQuoteFieldNames: false })
I understand the issue with bigint but wont this be an issue with field names like "group" that we've seen before? Should `addFieldSelection` do the quoting instead? I see that `castBigIntToText` manually quotes the field but I'm unclear about how the other fields are quoted since it is disabled here.

2024-04-23 13:31 UTC, msfstef commented on clients/typescript/src/client/model/builder.ts
> +  } else if (isObject(fieldValue) && !(fieldValue instanceof Date)) {
I'm assuming this is where the `isDataObject` (that feels a bit confusing although I see the need now!) would be appropriate?

2024-04-23 13:31 UTC, msfstef commented on clients/typescript/src/migrators/triggers.ts
> +    if (
nit: another petition here to maybe use a switch statement for readability

2024-04-23 13:31 UTC, msfstef commented on clients/typescript/src/satellite/client.ts
>        return column
nit: maybe worth having a decoder for `bytea` and have it be a no-op? an argument could be made in the future for encoding byte arrays for the wire and it'll make it easier to spot

2024-04-23 13:31 UTC, msfstef commented on clients/typescript/src/satellite/client.ts
>        return columnValue as Uint8Array
nit: see argument above about no-op `bytea` encoder/decoder

2024-04-24 07:19 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +      .select({ autoQuoteFieldNames: false })
`addFieldSelection` returns:
```ts
const fields = identificationFields
  .filter((f) => this._fields.includes(f))
  .concat(selectedFields)
  .map((f) => this.castBigIntToText(f))

return q.fields(fields)
```

If we look at `castBigIntToText` then we see that it quotes all fields:
```ts
if (pgType === PgBasicType.PG_INT8 && this.dialect === 'SQLite') {
  return `cast("${field}" as TEXT) AS "${field}"`
}
return `"${field}"` // <-- we quote it here
```

And all the other functions such add `addOrderBy`, `addDistinct`, etc. also quote all field names.

2024-04-24 07:21 UTC, msfstef commented on clients/typescript/src/client/model/builder.ts
> +      .select({ autoQuoteFieldNames: false })
Aah I see, I missed that, thank you for clarifying!

2024-04-24 15:01 UTC, msfstef approved these changes
Did a second pass, looking good!

2024-04-25 08:22 UTC, kevin-dp commented
> e2e test `03.25_node_satellite_can_resume_replication_after_server_restart.lux` consistently fails on CI but always passes on my machine locally. Not sure why it fails on CI.

When client reconnects, Electric restores some information from the DB we then checked that that information was gone from the DB. However, CI is slow and Electric did not yet restore the information by the time we checked that the information was gone from the DB. Now added an explicit match in the e2e tests to make sure we only check the DB state after that information has been restored by Electric.

2024-04-29 12:53 UTC, msfstef commented on clients/typescript/src/satellite/client.ts
> +      return encoder.text(columnValue as string)
this will accept numbers as well without converting them to strings (but we force cast the type to string) - we should not rely on the encoder being able to handle non-string inputs (see https://github.com/electric-sql/electric/pull/1204/files)

2024-04-29 14:13 UTC, kevin-dp commented on clients/typescript/src/satellite/client.ts
> +      return encoder.text(columnValue as string)
I don't think we need to address that in this PR, either #1204 gets merged before this one and we will rebase this PR to include it, or this PR gets merged first and yours will then affect the merged code. In both cases, the fix will be present.

2024-04-30 14:05 UTC, icehaunter reviewed
some nitpicks, reviewing other stuff still

2024-04-30 14:12 UTC, kevin-dp commented on clients/typescript/src/satellite/process.ts
> +      .flat()
:upside_down_face:

2024-04-30 14:17 UTC, icehaunter commented on clients/typescript/package.json
> +    "kysely": "^0.27.2",
oof, `kysely` + `prisma` + `squel` in direct non-dev deps... we need to do a pass over this

2024-04-30 14:17 UTC, icehaunter commented on clients/typescript/package.json
> +    "kysely": "^0.27.2",
not right now, but soon

2024-04-30 14:19 UTC, kevin-dp commented on clients/typescript/package.json
> +    "kysely": "^0.27.2",
Indeed... used Kysely for internally building some simple queries in a dialect agnostic way. However, those queries are very simple, we could as well not use Kysely and use our own query builder abstraction (iirc the only difference in those queries are the positional parameters, i.e. `?` vs `$i`).

2024-04-30 14:21 UTC, kevin-dp commented on clients/typescript/package.json
> +    "kysely": "^0.27.2",
Had a look again. Kysely is definitely overkill at this point, we're only using it to construct 2 very simple queries.

2024-04-30 15:02 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +  abstract countTablesIn(countName: string, tables: string[]): Statement
nitpick: tbh not a fan of this name or signature. `countName` is useless, just hardcode that as `result` or `count`, it's literally used once in the code base. Name's also weird, but I'm strugging to come up with a better one. `countTablesIfExist`?

2024-04-30 15:03 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      const oplog = `"${this.opts.oplogTable.namespace}"."${this.opts.oplogTable.tablename}"`
another candidate for `this.opts.oplogTable.toString()` :D

2024-04-30 15:06 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +        const qualifiedTableName = QualifiedTablename.parse(tablenameStr)
Technically should be outside of the inner loop here

2024-04-30 15:12 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +  abstract tableExists(tableName: string, namespace?: string): Statement
nitpick: this function is used in a single place of call, and yet we have an optional argument making for a non-intuitive namespace after table name argument order. Maybe make it non-optional and order as expected? Any place-of-call has access to `instance.defaultNamespace` anyway

2024-04-30 15:13 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +  abstract pgOnlyQuery(query: string): string[]
unused

2024-04-30 15:13 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +  abstract sqliteOnlyQuery(query: string): string[]
unused

2024-04-30 15:17 UTC, icehaunter commented on clients/typescript/src/util/relations.ts
>    const schema = 'public' // TODO
Question: shouldn't this be default schema as well? And used in `getTableInfo` call?

2024-04-30 15:20 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +    table: string,
So definintely for this and all function below, and maybe for 2 above: why are we leaving `schema` as an optional argument at all here, if every place of call fills it? It also occurs to me that most if not all places of call pull both table and schema from a `QualifiedTablename` instance, so why not accept that as the first argument in all of those instead?

2024-04-30 15:26 UTC, icehaunter commented on clients/typescript/src/config/index.ts
> +  dialect?: 'SQLite' | 'Postgres' // defaults to SQLite
nitpick: use JSDoc comments in cases like this, helps with hover tooltips


```suggestion
  /** defaults to SQLite */
  dialect?: 'SQLite' | 'Postgres'
```

2024-05-01 06:59 UTC, kevin-dp commented on clients/typescript/src/util/common.ts
> -    !ArrayBuffer.isView(value)
This was not the right place to perform this check, it was moved to the [`isDataObject` function](https://github.com/electric-sql/electric/pull/1038/files/eaf50dd60983069c94e1b541b2de897d2da571e5#diff-fcc94e2387326ffec6132e5b462a3adefd42a29b21e9f00ecb3eec27fb75bea9R27). The reason we have `isObject` and `isDataObject` is because we rely on the [`isFilterObject` function](https://github.com/electric-sql/electric/blob/eaf50dd60983069c94e1b541b2de897d2da571e5/clients/typescript/src/client/conversions/input.ts#L380) to determine whether an input object is a filter (e.g. `{ lt: 5 }`) or a data object (e.g. a date or a UInt8Array or ...). So `isObject` should match any JS object and `isDataObject` should match real input values (data to be stored).

2024-05-01 07:04 UTC, kevin-dp commented on clients/typescript/src/util/tablename.ts
> +    // would be collapsed to "foo.bar.baz".
The quotes in the comment are confusing, the quotes in `"<namespace>.<tablename>"` represent a JS string, the actual namespace and tablename in that string are not quoted. i.e. `this.namespace` is for example `"main"`, note that this is the string "main" and that string does not contain quotes otherwise it would be `"\"main\""`. So in the collapsed version, since there are no quotes around namespace and tablename, we cannot distinguish the two possibilities as per the comment.

2024-05-01 07:05 UTC, kevin-dp commented on clients/typescript/src/util/tablename.ts
> +    // would be collapsed to "foo.bar.baz".
Perhaps it would have been more clear if the comment used single quotes in order not to confuse this, so `'<namespace>.<tablename>'` which would lead to 'foo.bar.baz' and we cannot distinguish between the 2 posibilities.

2024-05-01 07:10 UTC, kevin-dp commented on clients/typescript/src/util/tablename.ts
> +    // would be collapsed to "foo.bar.baz".
Still, i see your point that if we serialise it already with the quotes we can distinguish both cases and use it as `${table}` in SQL. I will give it a try

2024-05-01 07:19 UTC, kevin-dp commented on clients/typescript/src/satellite/process.ts
> +    if (this.builder.dialect === 'Postgres') {
Yeah, i had it like that originally but didn't like the fact that depending on the dialect it was actually doing something different (deferring vs disabling). But i had it named as `deferFKs` but with the name you propose it is probably fine.

2024-05-01 07:31 UTC, kevin-dp commented on clients/typescript/src/util/tablename.ts
> +    // would be collapsed to "foo.bar.baz".
@icehaunter I see you are escaping double quotes in the namespace and tablename. Can double quotes really occur in namespaces and/or tablenames? Quickly tried this `CREATE TABLE "\"weird" (a INTEGER PRIMARY KEY);` but PG is not understanding the escaped quote as it is still waiting for a quote to end this statement. So i don't think it's possible. PG documentation also doesn't mention anything about escaping quotes inside quoted names.

2024-05-01 09:30 UTC, icehaunter commented on clients/typescript/src/util/tablename.ts
> +    // would be collapsed to "foo.bar.baz".
I'm sarying the "collapsed" version should use SQL quoting policy of explicitly double-quoting the namespace and the tablename separately, and that properly-escaped version should be the canonical string representation (as it is in SQL)

2024-05-01 09:31 UTC, icehaunter commented on clients/typescript/src/util/tablename.ts
> +    // would be collapsed to "foo.bar.baz".
Basically, I'm arguing that the comment "we can't collapse" is countered with "you're collapsing it wrong, it should be SQL standards"

2024-05-01 12:37 UTC, kevin-dp commented on clients/typescript/src/util/tablename.ts
> +    // would be collapsed to "foo.bar.baz".
Fixed this as proposes and refactored all instances of `"${table.namespace}"."${table.tablename}"` and modified the query builder methods to take qualified table names instead of taking tablename and namespace separately. You may want to have a look at the way [how qualified table names are parsed](https://github.com/electric-sql/electric/pull/1038/files#diff-0f99aa60443a9a9b65800c5ab13fd3629977a934c14207bfffb06aa942eeb414R22).

2024-05-01 14:25 UTC, kevin-dp commented on clients/typescript/src/util/relations.ts
>    const schema = 'public' // TODO
The `getTableInfo` call should indeed take the default namespace.
However, the schema in the inferred relation should be `'public'`.
I added a comment explaining why:

```ts
// schema needs to be 'public' because these relations are used
// by the Satellite process and client to replicate changes to Electric
// and merge incoming changes from Electric, and those use the 'public' namespace.
```

2024-05-01 14:53 UTC, davidmartos96 commented on clients/typescript/test/migrators/builder.ts
> +export const bundleTests = (test: TestFn<ContextType>) => {
I guess this was intended to be named builderTests

2024-05-01 16:53 UTC, icehaunter commented on clients/typescript/package.json
> +    "@tauri-apps/api": "^1.5.3",
Where is this used? Do we need this as a prod dependency, can't we get it into dev + peers?

2024-05-01 16:53 UTC, icehaunter commented on clients/typescript/src/util/tablename.ts
> +      const [_, namespace, tablename] = /"(.*)"\."(.*)"/.exec(
Counterexample: `"main"".""".""".""body"` which is a valid SQL value with (in unescaped form) schema `main"."` and table name `"."body`, but won't be parsed as such. Edge case for sure, but also makes invalid strings valid, like `"main""."s".""".""body"`. We also should match string boundaries.

So, to never return to this again, allow only paired double quotes within the quotes. Also identifers can't be empty: 

```suggestion
      const [_, namespace, tablename] = /^"((?:[^"]|"")+)"\."((?:[^"]|"")+)"$/.exec(
```

2024-05-01 16:53 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      { sql: this.builder.deferForeignKeys },
I thought you said this doesn't work on Postgres with non-deferrable constraints?

2024-05-01 16:53 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +    if (this.builder.dialect === 'Postgres') {
You said in the DMs that you don't like this approach either, but I don't like that Postgres builder implements `deferFKs` which you're now telling me not to use at all. I feel like that's a foot-gun for ourselves next time we add something that requires no FK checks for txn duration. I think builder exposing exactly one field here will force people to think about what's going on. Maybe even more explicit, `deferOrDisableFKsForTxn`

2024-05-01 17:41 UTC, icehaunter requested changes
Last batch of comments. Honestly mostly nitpicks, although I really want `package.json` and `deferFKs` addressed before we proceed. Feel free to ignore/address the rest as you see fit.

Very good work overall, speaks to a reasonable code organisation that this change was actually impressively reviewable and contained

2024-05-01 17:41 UTC, icehaunter commented on clients/typescript/src/migrators/schema.ts
> +          }" (\n ${builder.pgOnly(
```suggestion
          `CREATE TABLE "${shadowTable}" (\n ${builder.pgOnly(
```

2024-05-01 17:41 UTC, icehaunter commented on clients/typescript/src/client/conversions/input.ts
>    const fieldsAndValues = Object.entries(keepTableFieldsOnly(o, fields))
nitpick: We go `o: object -> Object.entries -> filter -> Object.fromEntries -> Object.entries -> map -> Object.fromEntries` over this object `o`, which feels hot-pathy to me. I'd rather we do `o -> Object.entries -> filter -> map -> Object.fromEntries`.

Smth like
```typescript
const copied = {...o}

for (const [field, value] of Object.entries(o)) {
  const pgType = fields.get(field)
  // Skip anything that's not an actual column on the table
  if (pgType === undefined) continue

  const transformedValue =
    transformation === Transformation.Encode
      ? converter.encode(value, pgType)
      : converter.decode(value, pgType)

  copied[field] = transformedValue
}

return copied
```

Your `transformField` does `fields.get` and checks if it exists althought this function is the only place of call in entire codebase and you've filtered it out in `keepTableFieldsOnly`. This implementation saves about 3 iterations/transformations (including `Map.keys() -> new Set()` although `Map.has` exists too)

2024-05-01 17:41 UTC, icehaunter commented on clients/typescript/src/client/conversions/input.ts
>    const fieldsAndValues = Object.entries(keepTableFieldsOnly(o, fields))
BTW you can make `filterKeys(o: object, keys: Set<string>)` signature to be `filterKeys(o: object, keys: { has: (x: string) => boolean })` and it'll accept map instances just as well

2024-05-01 17:41 UTC, icehaunter commented on clients/typescript/src/client/model/builder.ts
> +      return query.order(`"${field}"`, squelOrder)
nitpick: this quoting technically doesn't match SQL `.replaceAll('"', '""')`, but I'm not sure how much it currently matters. Worth opening a good-first-issue on GitHub maybe?

2024-05-01 17:41 UTC, icehaunter commented on clients/typescript/src/client/model/builder.ts
> +          prefixFieldsWith
nitpick: why not do `prefixFieldsWith + '"' + fieldName + '"'` into first argument instead of doing this in every single handler?...

2024-05-01 18:35 UTC, samwillis commented on clients/typescript/src/drivers/node-postgres/database.ts
> +export class ElectricDatabase implements Database {
@kevin-dp 

Can I just check I'm understanding this correctly, we have a `ElectricDatabase` wrapper for a node-postgres connection which is then passed to electrify rather than passing it the connection directly?

For the embedded postgres this is done automatically with our `createEmbeddedPostgres` wrapper, but for a normal node-postgres a user would have to do this:

```ts
import pg from 'pg'
import { electrify, ElectricDatabase } from 'electric-sql/node-postgres'

// Import your generated database schema.
import { schema } from './generated/client'

// Define custom configuration if needed
const config = {
  url: 'https://example.com:5133'
}

// Create the node-postgres database connection.
const client = new pg.Client({
  // Connection configuration, see:
  // https://node-postgres.com/apis/client
})
await client.connect()
const conn = ElectricDatabase(client, 'name-of-database')

// Instantiate your electric client.
const electric = await electrify(conn, schema, config)
```

Is there a reason the patching of `exec` below can't be done inside the adapter and not this secondary wrapper. It makes initiating the database connection a little complex.

Ideally we could just do:

```ts
const client = new pg.Client({
  // ...
})
await client.connect()
const electric = await electrify(client, schema, config)
```

2024-05-01 20:15 UTC, alco commented
@kevin-dp Don't forget to add a changeset.

2024-05-02 07:10 UTC, kevin-dp commented on clients/typescript/src/satellite/process.ts
> +    if (this.builder.dialect === 'Postgres') {
Applied the proposes change. Also had to change L308 in `_garbageCollectShapeHandler` which was using `deferForeignKeys` but for Postgres that would not work as expected (since that would only defer FKs that were defined as deferrable in the first place). So replaced that by `deferOrDisableFKsForTx`.

2024-05-02 07:33 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/pgBuilder.ts
> +        FROM information_schema.tables
Great tip! I did a quick and dirty `EXPLAIN ANALYZE` for my original query it took:
```
 Planning Time: 31.000 ms
 Execution Time: 12.000 ms
```

For your query it took:
```
 Planning Time: 15.000 ms
 Execution Time: 13.000 ms
```

2024-05-02 07:57 UTC, kevin-dp commented on clients/typescript/package.json
> +    "@tauri-apps/api": "^1.5.3",
It's not being used (anymore?). Removed it.

2024-05-02 08:59 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +      return query.order(`"${field}"`, squelOrder)
Right, let's make a good-first-issue on GH. We can always pick it up ourselves later in a separate PR.

2024-05-02 09:17 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +          prefixFieldsWith
Because some handlers use the field name, e.g. `makeBooleanFilter` uses the field name to index the object.

2024-05-02 09:19 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +          prefixFieldsWith
Could repurpose the handlers' `prefixFieldsWith` parameter to pass the full field name with prefix and quotes. Such that every handler gets just the name and the full name.

2024-05-02 09:40 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +      return query.order(`"${field}"`, squelOrder)
Ended up doing it right away.

2024-05-02 11:20 UTC, icehaunter approved these changes
Thanks for addressing feedback! Final function deletion and LGTM

2024-05-02 11:20 UTC, icehaunter commented on clients/typescript/src/client/conversions/input.ts
> +export function transformField(
This function is unused, should be deleted

2024-05-02 15:34 UTC, merged