feat(electric): Use two replications slots to allow clients to resume replication after Electric restarts
electric-sql/electric pull request #1043
Opened 2024-03-12 13:37 UTC by alco

This is the first of a few steps towards fixing resilience issues outlined in this [Linear project spec](https://linear.app/electric-sql/document/project-spec-fixing-restartability-of-the-sync-service-a060f28ac426).

Specifically, in this PR
* configuration options `ELECTRIC_IN_MEMORY_WAL_WINDOW` and `ELECTRIC_RESUMABLE_WAL_WINDOW` are added
* LogicalReplicationProducer advances the replication slot only as much as needed to keep it in the configured resumable WAL window. Previously, it would get advanced after every transaction was consumed so Electric couldn't restart its replication stream at an earlier point in the WAL. Now it can.

Coming up next: changes to the in-memory cache implemented in `CachedWal.EtsBacked` as well as fetching transactions from the database for those clients that are outside of the in-memory WAL window.

2024-03-14 13:26 UTC, icehaunter requested changes
Great work, exactly what I had in mind myself, and additional thanks for cleaning and testing the LSN module. One big question from me

2024-03-14 13:26 UTC, icehaunter commented on components/electric/lib/electric/config.ex
> +  @spec parse_human_readable_size(binary, pos_integer) :: {:ok, pos_integer} | {:error, binary}
```suggestion
  @spec parse_human_readable_size(binary | nil, pos_integer) :: {:ok, pos_integer} | {:error, binary}
```

Slightly wrong spec

2024-03-14 13:26 UTC, icehaunter commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +  # TODO(optimization): do not run this after every consumed transaction.
So I have 2 questions here:

1. Why are we running this whenever we see a `Commit`? We have `ack_fn` set to `ack` being the previous function - I believe it makes more sense to advance the slot as we do right now - once stored in memory at least (although I'll agree that it matters a bit less given that we're advancing a secondary slot here).
2. I see the "optimization" note you've left here, but I'm not sure I'm comfortable leaving this as a TODO. Advancing a slot on every transaction is fine-ish, however we're opening a new fully separate connection to PG on every received transaction. This is going to be extremely slow and costly for us, and PG won't be able to keep up with the amount of connections we're opening for one-shot queries. I'd be against even a pooling approach here - I believe we need to just open and hold a stable connection to PG to perform these tasks.

2024-03-14 13:26 UTC, icehaunter commented on components/electric/lib/electric/replication/postgres/slot_server.ex
> +    first_lsn = Lsn.increment(state.current_lsn, @lsn_step)
What's the reason to introduce these steps?

2024-03-14 15:39 UTC, alco commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +  # TODO(optimization): do not run this after every consumed transaction.
The optimization note wasn't meant to be left in the code for long. I split the code into multiple PRs to help myself draw boundaries between changes to different components and to get to a working version faster to then be able to focus on the edge cases and inefficiencies.

So, point taken. Holding a persistent connection might be the way to go if the current approach of advancing the slot often remains in place. Though I'm hoping to implement more of a batched approach, e.g. advancing every N transactions or in size-on-disk increments, at which point relying on a connection pool may be sufficient. I'll circle back to this discussion when I have more concrete ideas to share but I'm expecting those to be implemented in a follow-up PR in any case.

---

N.B.: I had a connection pool implemented as part of the early implementation work but had to take that out for now just to keep the scope of changes that are already spread over multiple PRs manageable.

2024-03-17 10:06 UTC, icehaunter commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +  # TODO(optimization): do not run this after every consumed transaction.
With or without batching, holding a single open connection just for slot advancement is fine, since only one process is likely to ever do logical replication stream consumption. I think just spawn a sibling GenServer that holds the advancing connection - to split the responsibility a little - and just `cast` to that server on `ack` - this makes the whole approach easy and doesn't clog up logical replication consumer with ack message handling since `cast`s will be sent to a different process. And if that genserver goes down and we lose a couple casts in the middle - no problem, worst case we'll have slightly more WAL stored at a point in time, but it'll resolve on any next cast. 

I'm not sure how you want to structure the PR merge sequence, but I would insist on adding this functionality in this PR. It's not much code, but the difference in perfomance implications is huge.

2024-04-02 12:53 UTC, alco commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +  # TODO(optimization): do not run this after every consumed transaction.
The implementation has changed now that this PR is based on https://github.com/electric-sql/electric/pull/1099 which is a fix for https://github.com/electric-sql/electric/issues/1083.

See the new commit - https://github.com/electric-sql/electric/pull/1043/commits/76addc4da4b5a4f5d092dfaace65fc964b99e3d5.

TL;DR: LogicalReplicationProducer now opens a persistent "service connection" during initialization and uses it to advance the main slot with the help of a timer.

2024-04-04 09:19 UTC, magnetised commented on components/electric/lib/electric/postgres/lsn.ex
> +    def to_charlist(lsn), do: ~c'#{Electric.Postgres.Lsn.to_iolist(lsn)}'
nitpick: do you need to wrap this with the `~c` sigil?

2024-04-04 09:57 UTC, alco commented on components/electric/lib/electric/postgres/lsn.ex
> +    def to_charlist(lsn), do: ~c'#{Electric.Postgres.Lsn.to_iolist(lsn)}'
Mix formatter has been adding those since [Elixir v1.15.0](https://github.com/elixir-lang/elixir/blob/v1.15/CHANGELOG.md#v1150-2023-06-19):
> [Code] Code.format_string!/2 now converts 'charlists' into ~c"charlists" by default

2024-04-04 10:08 UTC, magnetised approved these changes
Super

2024-04-04 12:27 UTC, icehaunter requested changes

2024-04-04 12:27 UTC, icehaunter commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +        ack_fn: fn -> ack(repl_conn, origin, end_lsn) end
I think this `ack` should not operate on `repl_conn`. 

`ack_fn` function is going to be called in a different process later down the line - in particular, in WAL cache consumer stage. This means that if this repl connection is closed for any reason, old transcations will call it with a stale value and probably crash - I don't know how `:epgsql.standby_status_update/3` acts when it's passed a nonexistent pid. 

To decouple that a little and make sure that the process calling the `ack_fn` doesn't crash, I'd rather `ack_fn` sent a `GenServer.cast/2` to a process that would actually hold the repl conn and do the acknowledge. If the cast fails because the holding GenServer is temporarily dead -- no problem, main code continues to operate, and worst case we acknowledge on the next magic write anyway. So I'd rather put this "advancing" repl conn into a separate GenServer that can restart and reconnect separately, and just `GenServer.cast` into it - maybe make it a `:gproc` via-tuple using the origin so that we don't even care where the repl process currently lives. 

What do you think?

2024-04-10 08:42 UTC, icehaunter approved these changes
Nice design, I like it! a couple of nitpicks, but nothing more. Let's coordinate a release before merging this though

2024-04-10 08:42 UTC, icehaunter commented on components/electric/lib/electric/postgres/cached_wal/ets_backed.ex
> +    |> Stream.map(fn %Transaction{} = tx -> {lsn_to_position(tx.lsn), tx} end)
nitpick: I don't understand why you don't like destructuring assignment of `lsn`, given that it's faster than dynamic dispatch of a `.` operator. Doesn't really matter in this case, just caught my eye.

2024-04-10 08:42 UTC, icehaunter commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +    state = %{state | queue: queue_remaining, queue_Len: queue_len - demand, demand: 0}
Typo that should lead to a runtime error, possibly means that this code path is not covered by test (although this is caught by Dialyzer)
```suggestion
    state = %{state | queue: queue_remaining, queue_len: queue_len - demand, demand: 0}
```

2024-04-10 10:37 UTC, alco commented on components/electric/lib/electric/postgres/cached_wal/ets_backed.ex
> +    |> Stream.map(fn %Transaction{} = tx -> {lsn_to_position(tx.lsn), tx} end)
It's not that I don't like it. As a rule of thumb, I use pattern matching in function heads when the same field is used multiple times in the function body. Because we have instances in the code where some fields are pattern-matched while others are accessed via the dot operator, the split usually looks arbitrary.

I believe that BEAM is smart enough to optimize uses of the dot operator if there's pattern-matching/guard in the function head. Can't find the source now, but here's at least a partial confirmation of that https://elixirforum.com/t/way-too-much-detail-about-matching-in-the-head-vs-accessing-maps-in-the-body/49167/2

2024-04-10 10:48 UTC, alco commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +    state = %{state | queue: queue_remaining, queue_Len: queue_len - demand, demand: 0}
Yeah, I had to stop working on this abruptly yesterday and pushed what I had ready by then. This condition requires a specific test setup to cover. I think having dialyzer complain about it is good enough.

2024-04-10 11:00 UTC, alco commented on components/electric/lib/electric/replication/postgres/logical_replication_producer.ex
> +        ack_fn: fn -> ack(repl_conn, origin, end_lsn) end
As we've discussed elsewhere, it is fine to acknowledge transactions inside LogicalReplicationProducer and rely on Elixir's supervision tree to restart things if anything fails. Since we now have a replication slot with a persistent starting point, we can replay already-seen transactions when a new replication connection opens.

2024-04-18 13:53 UTC, merged