Alco/vax 1729 persist client reconnection info
electric-sql/electric pull request #1116
Opened 2024-04-01 13:09 UTC by alco

2024-04-15 11:44 UTC, magnetised approved these changes
lovely work as usual. would it make sense to pull the persistence functions out of `ClientReconnectionInfo` and into a separate module, just to keep that module a little cleaner? it's doing a lot atm and separating those concerns would make the algo a bit clearer.

looking forward to that e2e test...

2024-04-15 17:24 UTC, icehaunter requested changes
Good work! I've a couple of questions and comments I'd like to address before merging, but I really like the general approach with write-through cache

2024-04-15 17:24 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +     ], rows} = Client.query!("SELECT * FROM #{Extension.client_additional_data_table()}")
Why rely at all on standard PG column auto-ordering at all and match instead of just listing them in the `SELECT` clause? Same q for all above

2024-04-15 17:24 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +    Client.with_pool(origin, fn ->
I like the write-through cache approach!

2024-04-15 17:24 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +    #{Extension.client_additional_data_table()}(
```suggestion
    #{Extension.client_additional_data_table()} (
```

2024-04-15 17:24 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +          advance_by_additional_data(graph, client_id, acknowledged, origin)
Optimization nitpick: we may want to agg deletions and execute one query instead of checking out a connection for each encountered element in `delete_additional_data`.

2024-04-15 17:24 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +              clear_stored_actions(origin, client_id, included_txns)
Same optimization nitpick as below: checking out a connection per item feels suboptimal against aggregating intended writes

2024-04-15 17:24 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +    (client_id, subscription_id)
Why an `ON CONFLICT` clause at all here? This should not be reachable at all under current model, so I'd rather it fail visibly when we do horizontal scaling. I'm not sure just taking a later write here is correct in a general case. This applies to other queries as well

2024-04-15 17:24 UTC, icehaunter commented on components/electric/test/electric/satellite/subscriptions_test.exs
> -        Electric.Satellite.ClientReconnectionInfo.clear_all_data(client_id)
What's the reason to delete that?

2024-04-16 11:07 UTC, alco commented on components/electric/test/electric/satellite/subscriptions_test.exs
> -        Electric.Satellite.ClientReconnectionInfo.clear_all_data(client_id)
ClientReconnectionInfo has been moved from global scope (where it used to be started inside the `Application.start()` callback) to origin-based scope. So it will now shut down together with the whole `PostgresConnectorSup` supervision tree.

The function `active_clients()` above this line relies on the global `Electric.Satellite.ClientManager` but since we only start a websocket listener for the duration of a single test case, there's no need to do explicit clean up of clients, IMO. They will get cleaned up from `ClientManager`'s state via process monitors.

2024-04-16 14:40 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +    (client_id, subscription_id)
Good catch. This is a leftover from my initial attempt to store additional data for subscriptions in the `client_subscriptions` table. Removed.

2024-04-16 14:41 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +              clear_stored_actions(origin, client_id, included_txns)
Yep, thought about this myself when I was writing it. Just finished an optimization pass on the code to add this, though, admittedly, its readability has arguably suffered a bit as a result.

2024-04-16 14:49 UTC, alco commented on components/electric/lib/electric/postgres/repo.ex
> +  use Ecto.Repo, otp_app: :electric, adapter: Ecto.Adapters.Postgres
* Ecto is a simpler choice because it provides a high-level API on top of Postgrex and DBConnection.
* I would like us to adopt a more structured approach to querying and updating our internal tables. Ecto schemas could be used for this, as opposed to writing plain-text queries as I did in this PR for expedience.
* Our own custom pooler on top of `nimble_pool` would be guaranteed to take up more time to write, plus we'd need to redo some of the work already done in Ecto.
* I'm not sure there are any problems with read queries: the only time client reconnection info (including subscriptions) is fetched from the DB is when the ClientReconnectionInfo process starts. All subsequent lookups are done by ETS.

2024-04-16 14:53 UTC, alco commented
@magnetised 
> would it make sense to pull the persistence functions out of `ClientReconnectionInfo` and into a separate module, just to keep that module a little cleaner?

I've done an optimization pass on the code since your review, to make fewer checkouts from the connection pool (and fewer SQL queries overall). As a result, it's become even more difficult to untangle persistence from the rest of the implementation than before. Not that the logic in this module is sensitive to stateful operations performed on ETS tables, so we cannot simply reorder those. As for DB queries, I've done a bit of grouping for those, such that they are now less coupled to ETS operations but still very much coupled to the overall module implementation.

2024-04-16 21:18 UTC, alco commented on components/electric/lib/electric/postgres/repo.ex
> +  use Ecto.Repo, otp_app: :electric, adapter: Ecto.Adapters.Postgres
* The current implementation of `Electric.Postgres.Repo` can be tweaked a bit to make the repo name depend on another parameter in addition to `origin`. That will make it possible to have multiple disjoint pools at the same time.
* I think fetching client's last acked lsn can use the same pool as restoring reconnection info cache from the DB. Both are client-related concerns.
* I agree that a different pool should be used for direct writes because of a different DB access patterns in that case.
* Loading up the ETS cache from DB on client connections sounds nice! I'll refrain from adding it here but will create an issue for it.

I've had somewhat similar thoughts about the in-memory wal window cache: as an example, on startup Electric could fetch last acked lsn for all clients and leave out the lowest quartile. The minimum lsn of the remaining values could be used as the earliest lsn that we keep cached in memory (provided we can still read it from the replication slot). But again, it's not clear to me if it's worth it or whether filling up the whole available cache space is actually a better approach in practice.

2024-04-17 10:46 UTC, icehaunter requested changes
Thank you for addressing my questions! I've a couple more nitpicks, and one important question in my opinion

2024-04-17 10:46 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +          Client.with_pool(origin, fn ->
nitpick: this should probably be `with_transaction` or something like that. I'd rather these writes be atomic

2024-04-17 10:46 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +
Nitpick: wrap in txn and same connection checkout?

2024-04-17 10:46 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +            store_client_actions(pending_actions)
nitpick: I'd appreciate a `!` in this function name, because my mind went immediately to the question of error handling in `with_pool/2` return value, but this uses a `query!` which will fail loudly instead - which I agree with, just want a pointer that this is what happens

2024-04-17 10:46 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +    {@additional_data_ets, {client_id, {:ord, order}}}
I see you're using order here as a unique key, but that's incorrect. Order was meant to be a ternary item to sort additional data insertions that have the same `xmin`. Primary key on that table should be `(client_id, min_txid, ord)`, and the deletion here should use that tuple too. Original logic relies on full key deletion because we care about last element of the tuple as the fully disambiguating element, but `(client_id, min_txid, ord)` tuple is also enough. This also addresses your "persist `move_in_next_ref`" concern, as `min_txid` is guaranteed to be advancing.

2024-04-17 10:46 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +      Client.pooled_query!(origin, @delete_additional_data_for_client_query, [client_id])
nitpick: can we wrap this with `advance_checkpoint` call higher up with a `checkout` or a `transaction` call? That should work with nested `checkout` call within `advance_checkpoint` if I remember `Ecto.Repo` docs correctly.

2024-04-17 10:50 UTC, icehaunter commented on components/electric/lib/electric/postgres/repo.ex
> +  use Ecto.Repo, otp_app: :electric, adapter: Ecto.Adapters.Postgres
I'd maybe argue for per-client cache filling earlier rather than later, because it gives us a better resiliency pattern: when a query in this module fails (which it definitely can with timeouts, as our demos have shown), WS connection will close, but ETS writes have already been done, which leaves the cache and DB in an inconsistent state. If we cleared the ETS part of the cache for this client when error in this module occurs, disconnected the client, and refilled from PG on reconnection, that would give us more consistent error handling per client instead of all-or-nothing we have right now.

2024-04-17 12:31 UTC, alco commented on components/electric/lib/electric/postgres/repo.ex
> +  use Ecto.Repo, otp_app: :electric, adapter: Ecto.Adapters.Postgres
Good point!

Still, I wouldn't put that into this PR as this will likely delay its merging by one or more days. There's always more nuance to adding a feature than seems at first.

To address the inconsistency you've described, we can reorder ETS and DB writes such that DB writes happen first. If one fails, the match ETS tables will remain unchanged. It's not perfect but can be addressed in this PR before it's merged.

2024-04-17 12:37 UTC, icehaunter commented on components/electric/lib/electric/postgres/repo.ex
> +  use Ecto.Repo, otp_app: :electric, adapter: Ecto.Adapters.Postgres
Sure, I'm not against a separate PR, just arguing for not delaying it because it can be very important for correctness. I also don't think reordering ETS writes will be super easy, given we do them in a loop while aggregating DB writes

2024-04-17 12:38 UTC, icehaunter commented on components/electric/lib/electric/postgres/repo.ex
> +  use Ecto.Repo, otp_app: :electric, adapter: Ecto.Adapters.Postgres
My personal gut feeling is that per-client loading is less work than reordering and rewriting parts of the algrithm, but you're welcome to take it however you want

2024-04-18 08:27 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +      Client.pooled_query!(origin, @delete_additional_data_for_client_query, [client_id])
I have moved this part into the `advance_checkpoint()` function that already has a `pooled_transaction` block.

2024-04-18 08:27 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +    {@additional_data_ets, {client_id, {:ord, order}}}
Thanks, fixed.

2024-04-18 08:29 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +            store_client_actions(pending_actions)
Would you like to see all functions that call `Client.query!()`  inside to also have the ! in their name?

2024-04-18 08:29 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +
Done.

2024-04-18 08:30 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +          Client.with_pool(origin, fn ->
Good point. I've moved the functions that work with a repo into a separate module named `Electric.Postgres.Repo.Client`, updated their names, and added one that executes the anonymous function in a transaction.

2024-04-18 09:05 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +            store_client_actions(pending_actions)
Yes, preferrably, just to have a reminder of how error handling is done here

2024-04-18 09:15 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +            store_client_actions(pending_actions)
If I do it transitively, almost every function in this module would get a `!` in its name.  I'm thinking of only applying this naming change to public functions, so that uses of this module's API in other modules communicate their error behaviour at a glance, while for private functions inside the module it can be seen from their implementation.

2024-04-18 12:21 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +            store_client_actions(pending_actions)
Just noting here that I've pushed a new commit that adds `!` to public function names only.

2024-04-18 12:24 UTC, icehaunter approved these changes
Great work, and thanks for addressing my concerns!
I've one more nitpick, but feel free to ignore if you don't agree.
I'll be waiting for the PR on per-client cache filling :D

2024-04-18 12:26 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol.ex
Especially when all other function calls hide this inside

2024-04-18 13:07 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol.ex
Awesome, thanks!

2024-04-18 14:26 UTC, merged