docs: updates for shapes
electric-sql/electric pull request #1129
Opened 2024-04-05 14:34 UTC by icehaunter

2024-04-05 14:40 UTC, KyleAMathews commented on docs/usage/data-access/shapes.md
> +Local apps ask the server for a specific set of related data that gets synced to the local device. The central Postgres instance will always have too much data to fit on any one device, so shapes all
```suggestion
Local apps ask the server for a specific set of related data that gets synced to the local device. The central Postgres instance will often have too much data to fit on any one device, so shapes allow us to sync only a required subset of data onto the device. There is a balance between local data availability and storage usage on the device that is unique to every application, and shapes allow you to balance those properties while maintaining required guarantees.
```

2024-04-05 15:00 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +You can filter data at the top of the shape, or when including data over a one-to-many relation using a `where` clause on the request object. Shape `where` clauses may be either an object, or a strin
```suggestion
You can filter data at the top of the shape, or when including data over a one-to-many relation using a `where` clause on the request object. Shape `where` clauses may be either an object, or a string. They may only reference the columns on the filtered table itself.

It's important not note that many-to-one relations cannot be filtered that way (e.g. you cannot do `comments: { include: { author: { where { id: true }}}}`), because if a
```

2024-04-05 15:01 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +TypeScript type of the object accepted in `.sync` call may be wider than what is actually supported.
```suggestion
The TypeScript type of the object accepted in `.sync` call may be wider than what is actually supported.
```

2024-04-05 15:04 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +Because the where clause will be applied on Postgres and on the ElectricSQL server, you can drop down to a string representation that's close to PostgreSQL `WHERE` clause on a regular query. You can
```suggestion
As the where clause will be applied on Postgres and on the ElectricSQL server, you can drop down to a string representation that's close to that of a SQL `WHERE` clause on a regular query. You can use the usual PostgreSQL syntax, although not all functions are supported. The columns of the table you're filtering can be referenced using `this.` prefix:
```

2024-04-05 15:08 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +This allows for more flexibility (i.e. not entire supported PostgreSQL subset can currently be expressed via a Prisma-like API), but you have to be more careful with interpolating your own values in
```suggestion
This allows for more flexibility as the Prisma-like does not support the all possible expressions supported by the Electric sync engine. However, you need to be more careful with interpolating your own values in the string to ensure that PostgreSQL would accept for the expected type.
```

2024-04-05 15:10 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +Full current list of supported Postgres functions is easiest found [in code](https://github.com/electric-sql/electric/blob/main/components/electric/lib/electric/replication/eval/env/known_functions.e
I don't like this, we should never be pointing people to source code to see a list of supported features. Even if it's verbose it should be here.

True, it's a maintain burden to keep the docs up to date, but the friction of link to source is too high.

2024-04-05 15:12 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +Current filtering implementation does not support non-deterministic functions. You cannot have `now()` PostgreSQL function in the where clause, because there's currently no way for us to garbage-coll
```suggestion
The current filtering implementation does not support non-deterministic functions. For example it's not possible to use the PostgreSQL `now()` function in the where clause.
```

We don't need to try and explain why it's not supported at this point.

2024-04-05 15:15 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +Once a subscription is established, it remains statefully in SQLite database even when you change the code. For example, doing `db.projects.sync({ where: { id: 1 }})`, starting the application, then
```suggestion
Once a subscription is established, it remains statefully in the local SQLite database even when you change the code. For example, doing `db.projects.sync({ where: { id: 1 }})`, starting the application, then changing the code to `db.projects.sync({ where: { id: 2 }})` will result in **2 subscriptions** established, with both projects synced to the device. We're working on lifting this limitation.
```

2024-04-05 15:21 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +
```suggestion
#### Move-in lag

Due to consistency considerations, when additional rows move into a shape as a result of following a one-to-many relation these will show up on the device slightly later than the parent row itself. It's important to keep this in mind when designing the UI.

For example, with this this shape:

```ts
await db.projects.sync({
  where: { status: "active" },
  include: { issues: true },
});
```

If a project were to have its status changed to `active`, the client would now be eligible to see it, along with its issues. However, the project will be synced to the local database before the issues.
```

2024-04-05 15:22 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +- `DELETE` of the top row on the client without having synced all the children may not result in a `DELETE` on the server and the row will be restored
I think this is referring to cascades, I think it needs a clearer explanation of what the issue is.

2024-04-05 15:22 UTC, samwillis commented on docs/usage/data-access/shapes.md
> +- Recursive and mutually recursive tables are not supported at all for now. A FK loop will prevent the shape subscription from being established.
```suggestion
- Recursive and mutually recursive tables are not supported at all for now. A foreign key loop will prevent the shape subscription from being established.
```

2024-04-05 15:35 UTC, icehaunter commented on docs/usage/data-access/shapes.md
> +Full current list of supported Postgres functions is easiest found [in code](https://github.com/electric-sql/electric/blob/main/components/electric/lib/electric/replication/eval/env/known_functions.e
I get that, but also that list will be so large later on... Probably deserves it's own page.

2024-04-05 15:38 UTC, icehaunter commented on docs/usage/data-access/shapes.md
> +Full current list of supported Postgres functions is easiest found [in code](https://github.com/electric-sql/electric/blob/main/components/electric/lib/electric/replication/eval/env/known_functions.e
I'm not sure still it's worth it to do right now, and how to do that exactly. I'd rather not duplicate PG docs here either...

2024-04-05 15:38 UTC, icehaunter commented on docs/usage/data-access/shapes.md
> +- `DELETE` of the top row on the client without having synced all the children may not result in a `DELETE` on the server and the row will be restored
willdo

2024-04-05 18:35 UTC, balegas approved these changes
Great pass.

2024-04-05 18:35 UTC, balegas commented on docs/usage/data-access/shapes.md
> +Local apps ask the server for a specific set of related data that gets synced to the local device. The central Postgres instance will often have too much data to fit on any one device, so shapes allo
- Local apps and local device seem a little redundant.
- I preferred more the language of syncing a subset of the larger database than saying the Postgrew will 'often' have much more data than fits on one device. Shapes are there for getting only the data the user needs into the device.

2024-04-05 18:35 UTC, balegas commented on docs/usage/data-access/shapes.md
> +### Foreign key and query consistency
nit: we don't need to talk following FKs to explain we fetch all data that is necessary for maintaining integrity. I'm also okay if you prefer expressing this way.

- I'd move this down and call it "Maintaining [Foreign Key] Integrity". 
- Maybe we can talk oversynching pattern

2024-04-05 18:35 UTC, balegas commented on docs/usage/data-access/shapes.md
> +:::danger Potential foot-gun in development
can we not use foot-gun in public docs :)

2024-04-05 18:35 UTC, balegas commented on docs/usage/data-access/shapes.md
> +As the where clause will be applied on Postgres and on the ElectricSQL server, you can drop down to a string representation that's close to that of a SQL `WHERE` clause on a regular query. You can us
> As the where clause will be applied on Postgres and on the ElectricSQL server, you can drop down to a string representation that's close to that of a SQL `WHERE` clause on a regular query
Could just say that we can do raw where clauses.

2024-04-10 09:59 UTC, thruflo requested changes
Great stuff 👍 left some comments.

2024-04-10 09:59 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +Local apps ask the server for a specific set of related data that gets synced to the local device. The central Postgres instance will often have too much data to fit on any one device, so shapes allo
Yup, I would request reverting the deletion here. This high level context is important for building the mental model of the developer. I think the added para could happily be added after as additional context.

2024-04-10 09:59 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +    id: "abcd",
Just on the syntax changes across these code samples:

1. single quotes are fine, no need to change to double quotes
2. trailing commas and semicolons -- we don't use these in the docs or the code samples

I'm not sure if there's a difference in editor settings but certainly when I was working on this the linting config was compatible with single quotes and the absence of commas and semicolons.

2024-04-10 09:59 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +### Foreign key and query consistency
Yes, it's great that we're clear about this but I would move this section down to the limitations section. I think we should be explicit that this means that data you may not want to end up on the client will end up on the client. I.e.: project belongs to a user, so the user gets synced, even if the user has a password field ...

Is this behaviour explicit or implicit? I.e.: if the relation is required in the shape, do we force the shape to define it, so you have to specify in the include tree? Or do we sync by magic in the background? It strikes me that explicit would be clearer, as it at least forces the developer to be aware of the behaviour.

2024-04-10 09:59 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +You can filter data at the top of the shape, or when including data over a one-to-many relation using a `where` clause on the request object. Shape `where` clauses may be either an object, or a strin
I think this would really benefit from a code sample showing use of a where clause in an include object.

I'm not sure in this sentence what the `request` object is.

2024-04-10 09:59 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +:::danger Potential foot-gun in development
I think it's fine myself. It's clear, there is a a foot gun here. Foot guns exist.

2024-04-10 09:59 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +## Limitations and issues
I suggest moving the updating shapes and move-in lag sections into limitations. I also think an explicit "you can't currently delete a subscription" section would be valuable.

2024-04-10 10:00 UTC, thruflo commented
Another note on this: the shapes section in the roadmap limitations page needs to be updated. It still states that shapes are whole table only.

2024-04-10 10:11 UTC, icehaunter commented on docs/usage/data-access/shapes.md
> +    id: "abcd",
Yeah, autoformatter got me at some point

2024-04-10 11:21 UTC, thruflo approved these changes
Thanks -- left a couple more minor suggestions.

2024-04-10 11:21 UTC, thruflo commented on docs/reference/roadmap.md
> +[Shape-based sync](../usage/data-access/shapes.md) using the [`sync()` function](../api/clients/typescript.md#sync) is currently supported with some [limitations](../usage/data-access/shapes.md#limit
`s/Biggest/The biggest`.

2024-04-10 11:21 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +- `.sync` method has a wider type signature in TypeScript than what's really supported. In particular, `limit`, `sort` and other keywords under `include` should not be there.
Could hyperlink the sync method to that section of the client api doc.

2024-04-10 11:21 UTC, thruflo commented on docs/usage/data-access/shapes.md
> +- Shape unsubscribe is not available, which means any `.sync` method (in development in particular) is going to be statefully persisted regardless of code changes.
"any `.sync` method" <- I think we should refer to a shape subscription, i.e.: any shape subscription established by calling `sync()` is going to be statefully ...

2024-04-11 09:59 UTC, merged