Alco/vax 1804 scope client reconnection info
electric-sql/electric pull request #1188
Opened 2024-04-23 14:30 UTC by alco

2024-04-24 12:29 UTC, icehaunter requested changes
I like the approach, thanks for addressing these concerns! I do have two discussion points that I think warrant solving before merge

2024-04-24 12:29 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol.ex
> +
This `send` kinda doesn't guarantee that: the `:subscribe` message from `SatelliteCollectorConsumer` stage (started from `ClientManager.register_client/3` call chain) hasn't arrived already. After the `SatAuth` RPC call only the `SatInStartReplicationReq` call is allowed to come from the client (let's put aside replication data coming from the client to the server for a moment). Handler for that call is essentially the first place to use the cache -- why not fill it there? Technically the client may send `SatAuthReq` and `SatInStartReplicationReq` in the same frame (ours doesn't, but, you know) - it would be perfectly valid order of operations if `SatAuthReq` passes successfully and we move on to handle replication request with a new, authorized state. I'd rather load the cache in the `SatInStartReplicationReq` handler, because the cache is wrong at the time of loading, until you advance it to the point of client reconnection LSN

2024-04-25 11:42 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +      |> debounce()
> a possible optimization here to not load cache from DB at all if it's already in memory, and clear it only if one of the writing functions in this module failed

I like this approach. Can't remember why I decided not to pursue it but your comment has reaffirmed that it is a viable option: load data for all clients at startup, then reload on a per-client basis if any of that client's writes to replication info fails.

To be honest, 1 second delay does not seem long to me, given the fact that the load is happening in background. So if a client is on a spotty network, loading of its reconnection info might already be in progress by the time it sends a startReplication() message, provided we start loading the data early on after the client has connected.

It's all about trade-offs. We'll need to keep an eye on these data going forward to be able to make an informed decision with regards to whether it's OK to keep it in main memory for all clients (if graphs don't grow too large) or whether it's better to load and unload it to only maintain in-memory cache for connected clients.

2024-04-30 08:15 UTC, alco commented on components/electric/lib/electric/satellite/protocol.ex
> +
> Handler for that call is essentially the first place to use the cache -- why not fill it there?
Agreed.

2024-05-06 07:49 UTC, icehaunter approved these changes
LGTM with one nitpick to remove a piece of code

2024-05-06 07:49 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol.ex
> +    ClientReconnectionInfo.clear_all_data!(state.origin, state.client_id)
Why do we need to add this here, given `:perform_initial_sync_and_subscribe` handler will call `ClientReconnectionInfo.store_initial_checkpoint!/4` that will clear all this data atomically anyway?

2024-05-06 07:49 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol.ex
> +  defp restore_subscriptions(subscription_ids, %State{} = state) do
nitpicky question: what's with function reordering here? Makes it harder to compare diffs

2024-05-06 07:56 UTC, alco commented on components/electric/lib/electric/satellite/protocol.ex
> +  defp restore_subscriptions(subscription_ids, %State{} = state) do
I simply moved this function definition up because it is called first in `restore_client_state()`, and `restore_graph()` is called after it.

2024-05-06 08:11 UTC, alco commented on components/electric/lib/electric/satellite/protocol.ex
> +    ClientReconnectionInfo.clear_all_data!(state.origin, state.client_id)
It's a fair point. I added this call because it looked like a logical thing to do for this module if you don't take into account that `ClientReconnectionInfo.store_initial_checkpoint!()` calls it internally.

I know that one is required to know what happens in all three modules--WebsocketServer, Protocol, ClientReconnectionInfo--in order to be able to make sense of the data flow for any given client, but I would still argue that having this call here does more good than harm since it's handling an edge case. At some point some implementation detail may change elsewhere that could affect the part of logic defined here, in Protocol. Better be prepared for that than sorry.

2024-05-06 09:35 UTC, merged