feat!: server-driven unsubscribes
electric-sql/electric pull request #1240
Opened 2024-05-08 11:47 UTC by icehaunter

1. Adds new boundary messages to the protocol allowing the server to send a GONE batch - a set of messages for the client to know that those rows will not receive further updates after an unsubscribe call.
2. Server is the source of truth on which rows the client should have
3. Only while-online unsubscribes are possible
4. Client may reconnect at any point after sending the unsubscribe call and the server will adjust seen rows correctly and send a GONE batch if we don't believe the client had seen that -- see tests in `subscriptions_test.exs`.

Missing is a public API for unsubscribes, that's in the next PR.

2024-05-08 13:37 UTC, kevin-dp reviewed
Overall LGTM, left some comments here and there but nothing major.

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/src/satellite/client.ts
> +    // TODO: real removeListener implementation, because the old one for txns doesn't work
Why can't we implement it as `this.emitter.removeListener('goneBatch', callbackFn)`?
(assuming we store the callback functions such that we can reference them here)

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/src/satellite/client.ts
> +    } else if (this.inbound.receivingUnsubsBatch) {
Are we sure that `this.subscriptionsDataCache.isDelivering` and `this.inbound.receivingUnsubsBatch` can never be true at the same time?
Otherwise we could be getting an unsubs message that would pass the first if test and get processed by `processOpLogMessage`.
I have the impression that instead of testing for `this.inbound.receivingUnsubsBatch` we may want to track this in the `subscriptionsDataCache` or in the subscriptions manager.

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/src/satellite/client.ts
> +    const subscriptionIds = [...this.inbound.receivingUnsubsBatch]
Are we making a copy here? If yes, let's make this explicit through a comment.
Not sure why we are making a copy though since on L1018 we're setting `this.inbound.receivingUnsubsBatch = []` so doesn't seem to matter if we would mutate the original array.

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/src/satellite/client.ts
> +      [...this.inbound.goneBatch],
same, not sure why we need to copy it

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/src/satellite/shapes/manager.ts
> +  unsubscribe(subIds: SubscriptionId[]): void {
Where is `unsubscribe` used? I only found the version with GC being used.

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/src/util/proto.ts
> +  SatUnsubsDataBegin: [24, Pb.SatUnsubsDataBegin],
Both have number 24, is that normal? Just to sanity check as i'm not sure what these represent

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/src/util/types.ts
> +  receivingUnsubsBatch: false | string[]
not particularly a fan of using this variable to do 2 things: 1) as a flag indicating whether we are not currently receiving unsubscription messages, and 2) to store an array of unsubs messages. Feels like an option type would be a cleaner abstraction here but yeah... we're doing JS, this is poor man's option type ;D

2024-05-08 13:37 UTC, kevin-dp commented on clients/typescript/test/satellite/process.ts
> +    const { runMigrations, authState, token } = t.context
let's move this into a single destructuring assignment

2024-05-08 13:44 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +  public makeQT(tablename: string): QualifiedTablename {
Counter nit: I don't like verbosity of `QualifiedTablename` class name everywhere, and would maybe shorten it to QT or QTN across the codebase :D

2024-05-08 13:46 UTC, icehaunter commented on clients/typescript/src/satellite/client.ts
> +    // TODO: real removeListener implementation, because the old one for txns doesn't work
Because we rewrite the provided cb function to call an ack at the end, see above, so calling off with original callback will do nothing, but it was written like that before. I removed the buggy implementation some time ago, but didn't put anything on instead because we actually dont use the unsubscribe functions

2024-05-08 13:47 UTC, icehaunter commented on clients/typescript/src/satellite/client.ts
> +    } else if (this.inbound.receivingUnsubsBatch) {
Yes, server impl will never interleave batches of any kind

2024-05-08 14:06 UTC, icehaunter commented on clients/typescript/src/util/types.ts
> +  receivingUnsubsBatch: false | string[]
Me too, but we don't have options and I don't want to manage 3 fields instead

2024-05-08 14:06 UTC, icehaunter commented on clients/typescript/src/util/proto.ts
> +  SatUnsubsDataBegin: [24, Pb.SatUnsubsDataBegin],
Good catch

2024-05-08 14:08 UTC, icehaunter commented on clients/typescript/src/satellite/shapes/manager.ts
> +  unsubscribe(subIds: SubscriptionId[]): void {
https://github.com/electric-sql/electric/blob/ilia/vax-1289-unsubscribe-handling/clients/typescript/src/satellite/process.ts#L460

2024-05-08 14:10 UTC, icehaunter commented on clients/typescript/src/satellite/client.ts
> +    } else if (this.inbound.receivingUnsubsBatch) {
Our interaction with protocol is a FSM, but current code spreads that fact over 2 files already. I think this is reasonable enough because interleaving is not intended by the protocol

2024-05-08 14:12 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +    const pos = (i: number) => `${this.makePositionalParam(i)}`
This is a copy of your own code above! :D

2024-05-08 15:38 UTC, magnetised requested changes
excellent work. you do need to fix those protobuf id conflicts tho.

2024-05-08 15:38 UTC, magnetised commented on components/electric/lib/electric/satellite/protobuf.ex
> +    SatUnsubsDataEnd => 25
see @kevin-dp's point re duplicated 24s

2024-05-09 08:42 UTC, icehaunter commented on clients/typescript/src/migrators/query-builder/builder.ts
> +      positionalParam = 1 // start counting parameters from 1 again
Yes but we''d be recreating the closure for a function. I feel like `= 1` for this very bounded block of code is easy enough to read while being more performant

2024-05-09 10:12 UTC, icehaunter commented on clients/typescript/src/satellite/client.ts
> +    const subscriptionIds = [...this.inbound.receivingUnsubsBatch]
It matters 10 lines down in the ack callback function. It will close over `this` and not over value of `this.inbound.receivingUnsubsBatch`, meaning that at the point when the callback will be called it will use already-cleared value of that fields instead of a full list.

2024-05-09 10:12 UTC, icehaunter commented on clients/typescript/src/satellite/client.ts
> +      [...this.inbound.goneBatch],
here we don't

2024-05-09 10:18 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +          {{client_id(), sub_id :: String.t(), wal_pos :: non_neg_integer()}}
I really don't want to. I structured the rest of the file like this (and you [had approved](https://github.com/electric-sql/electric/pull/899/files#diff-a62b6f57d365fae49cdd32774a3cc1c3f209357b5522b62467ddf2fc1705c86fR163-R189) it before) because for me it's easier to see name of the ETS table paired immediately with the row structure in the type.

2024-05-09 10:22 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +      # FIXME: this needs to clear all that from the future, which is now done not in this function!!!!!!!
Actually forgor :skull: 
I'll fix that in this PR

2024-05-15 09:26 UTC, alco commented on components/electric/lib/electric/postgres/extension/migrations/20240501000000_client_reconnection_unsub_points.ex
> +        wal_pos BIGINT NOT NULL,
I remember you raised an issue with this `BIGINT` type. It's not too late to change it here. Making the same change in the older migration can be done in a separate PR (I can handle that).

2024-05-15 09:26 UTC, alco commented on components/electric/lib/electric/replication/shapes/shape_request.ex
> +    # It's important to get of that fake root later.
I'm not sure what this says. "Get off that fake root"? At what point later?

2024-05-15 12:50 UTC, magnetised approved these changes
fantastic stuff

2024-05-15 21:23 UTC, alco approved these changes
:trophy:

2024-05-16 08:49 UTC, merged