feat: data access library
electric-sql/electric pull request #128
Opened 2023-04-20 15:17 UTC by kevin-dp

This PR integrates the data access library in the typescript-client.
Fixes VAX-526, VAX-587, VAX-613 and VAX-623

*Code structure:*

- The DAL source files reside in `src/client`.
The main functionality is implemented by `src/client/model/table.ts` which represents a table from the DB and provides a Prisma-inspired API for CRUD operations on that table.

- The entry point of the DAL is the static `ElectricClient.create` method which takes a description of the DB (generated by our custom Prisma generator) as input and generates a namespace that extends the electric namespace with a property for each table.

- The `src/client/input` folder defines the input types that are accepted by the different methods of the API of a table.

- The `src/client/execution/executor.ts` file defines an `Executor` class wraps a DB adapter and a notifier and provides methods to execute queries and transactions while also calling `potentiallyChanged` on the notifier.

*Notes about the code:*

The main code is located in `src/client/model/table.ts`.
This `Table` class implements the API of the DAL.
The queries are executed using one of the supported drivers.

However, drivers have subtle differences: some are synchronous (e.g. better-sqlite3) some are async (e.g. wa-sqlite). Within the async drivers, some support promises, others do not support promises and require continuation passing style using callbacks.

For this reason, the unified adapter API also requires passing callbacks and thus writing code in continuation passing style.
**As a result, the `Table` class is also implemented in continuation passing style.** Thus, internally, we can compose API calls but have to pass callbacks around.

2023-04-24 13:01 UTC, icehaunter commented on clients/typescript/src/client/model/table.ts
> +      this._dbDescription.getTableDescription(tableName).deleteManySchema
nitpick: Why do we do a function call so many times instead of assiging to a varible once?

2023-04-24 13:22 UTC, icehaunter commented on clients/typescript/src/client/validation/validation.ts
> +    Object.keys(obj).map((key) => {
```suggestion
    Object.keys(obj).foreach((key) => {
```

since we're not using `return` in the function

2023-04-24 13:23 UTC, icehaunter commented on clients/typescript/src/client/validation/validation.ts
> +  function deepOmit(obj: Record<string, any>) {
nitpick: Can we actually pull this out into a non-exported function here? we're not using any values from the closure anyhow

2023-04-24 13:24 UTC, icehaunter commented on clients/typescript/src/client/validation/validation.ts
> +  deepOmit(parsedObject) as I
nitpick: I'm not sure why an assertion is required here at all

2023-04-24 13:25 UTC, icehaunter commented on clients/typescript/src/client/model/builder.ts
> +    const selectedFields = Builder.getSelectedFields(i.select!)
`i.select` is `any` here anyway, no reason to do a non-null assertion.

2023-04-24 13:26 UTC, icehaunter commented on clients/typescript/src/client/model/builder.ts
> +type AnyFindInput = FindInput<any, any, any, any, any>
types: I don't love that everything here just takes `any`. Makes leaking `any` into calling scope very easy. Can we at least use `unknown` instead wherever possible? Or is that too much trouble?

2023-04-24 13:29 UTC, icehaunter commented on clients/typescript/src/client/model/table.ts
> +        fromField,
question: are you sure these are in the correct order? `fetchRelated` defines `from` and `to` in the reverse order from these. If this is correct, add a note please

2023-04-24 13:37 UTC, icehaunter commented on clients/typescript/src/client/model/table.ts
> +                        const updateManyObject = relationActions.updateMany
codestyle: I am scared of 12(!) levels of indentation here.  Is there absolutely no way to simplify this or spread over a couple of well-named functions?

2023-04-24 13:41 UTC, icehaunter commented on clients/typescript/src/client/model/table.ts
> +   *  })
codestyle: There's a special `@example` JSDoc tag just for this :) https://jsdoc.app/tags-example.html

2023-04-24 13:42 UTC, icehaunter requested changes
Amazing work. Usage example seem to show that this works quite well, so consider most of these as nitpicks.

One meta-note is that we need to utilize proper docstrings much much more in place of regular comments, especially for exported and public functions, doubly so for any exported or public functions that are part of the API. 

I can't say that I read attentively each of 1400 lines in `table.ts`,  but I followed the more complicated segments and looked at the general codestyle. Is the continuation-style API required because of that one driver that requires continuation-style calls to run multiple statements in the same transaction? Can we discuss the complexity cost of keeping it around?

2023-04-24 14:43 UTC, kevin-dp commented
> Is the continuation-style API required because of that one driver that requires continuation-style calls to run multiple statements in the same transaction? Can we discuss the complexity cost of keeping it around?

Yes, it's because of that. This is a problem of both cordova-sqlite storage (cf. [this issue](https://github.com/storesafe/cordova-sqlite-storage/issues/832)) and react-native-sqlite-storage (cf. [this issue](https://github.com/andpor/react-native-sqlite-storage/issues/117)).

2023-05-02 14:31 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +  private static addFilters<T, Q extends QueryBuilder & WhereMixin>(
I don't think that turning those static methods into regular functions will remove the need for `bind` because we're using `bind` to partially apply the function.

2023-05-04 07:05 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +type AnyFindInput = FindInput<any, any, any, any, any>
I've tried but it is too much, propagates everywhere internally.
We can do this improvement later but it would take too long right now.

2023-05-04 10:55 UTC, kevin-dp commented on clients/typescript/src/frameworks/react/hooks.ts
> +// Main reactive query hook for React applications. It needs to be
Fixed this as suggested by @thruflo.
Removed `useElectricQuery` in favor of using `useLiveQuery` in combination with a new `liveRaw` query.

2023-05-04 12:29 UTC, kevin-dp commented on clients/typescript/src/client/model/table.ts
> +                        const updateManyObject = relationActions.updateMany
Welcome in the callback hell...

2023-05-08 10:13 UTC, alco approved these changes

2023-05-08 10:18 UTC, icehaunter approved these changes
Thanks for accommodating my comments

2023-05-08 11:46 UTC, merged