chore(client): Drop node 16 support
electric-sql/electric pull request #1378
Opened 2024-06-17 14:01 UTC by msfstef

Node 16 has been [dead for a while](https://nodejs.org/en/blog/announcements/nodejs16-eol) and we are not testing more modern Node LTS versions.

Most prominently, the better-sqlite3 we were using in the client does not support Node v22 as raised by @robacourt  and others (https://github.com/electric-sql/electric/issues/1301)

I've updated the CI workflows to use Node v22 and the matrices to test v18 v20 and v22

2024-06-17 14:48 UTC, msfstef commented on clients/typescript/src/drivers/better-sqlite3/mock.ts
> +  // @ts-ignore annoying typings for mock
I'm unsure whether this is a TS issue or I'm failing to conform to the types, but the typings are so obtuse that I refuse to spend more time on this mock

2024-06-17 15:54 UTC, alco approved these changes
:+1:

2024-06-18 09:19 UTC, kevin-dp commented on clients/typescript/src/drivers/better-sqlite3/mock.ts
> +    return mockStatement as Statement<T, Result>
This type error can easily be "avoided", we know that this is a wrong typecast that is only valid for mocking, so we need to make it an unsafe typecast:
```ts
return mockStatement as unknown as Statement<T, Result>
```

2024-06-18 09:23 UTC, kevin-dp requested changes

2024-06-18 09:23 UTC, kevin-dp commented on clients/typescript/src/drivers/better-sqlite3/mock.ts
> +  // @ts-ignore annoying typings for mock
I don't really like this but the typings are indeed insane. I spent some time on it trying to figure it out but i didn't succeed. Would need more time to figure it out...
Not sure whether we should spend the time or not.

2024-06-18 09:23 UTC, kevin-dp commented on clients/typescript/test/drivers/better-sqlite3.test.ts
> +  //@ts-ignore issue with typechecking
I don't think it is acceptable that we have to `ts-ignore` every instantiation of the DB adapter with a mock database.
We can apply a dirty fix that solves this problem by modifying the `MockDatabase`: instead of defining the `prepare` method we can define a `prepare` constant and just do an unsafe typecast of the arrow function to the expected type.

2024-06-18 10:01 UTC, kevin-dp approved these changes
Much better!
Good to go for me.

2024-06-18 10:03 UTC, merged