fix(client): Fix batch deletes
electric-sql/electric pull request #1394
Opened 2024-06-20 15:00 UTC by msfstef

Addresses [VAX-1985](https://linear.app/electric-sql/issue/VAX-1985/large-unsubscribes-lead-client-with-wa-sqlite-driver-to-a-stack)

Apparently the method we were using, where we chained `OR` and `AND` clauses in the `WHERE` clause, led to:
1. SQLite call stack overflow (at least with `wa-sqlite`) at around 6k `OR` clauses, far below the max parameter limit
2. Sub-optimal performance in both SQLite and PGlite

I've converted the batching to use `IN` statements for both single-column queries and multi-column ones, like with composite primary keys. The performance is significantly improved and has room for more improvement:

#### Old Batching
##### Shadow Table 30k deletes
- ~4700ms pglite
- ~500ms wa-sqlite (arbitrary small batching to avoid overflow)

##### Comment 9k deletes
- ~700ms pglite
- ~2000ms wa-sqlite (max 6k batches)

#### New Batching
##### Shadow Table 30k deletes
- ~100ms pglite
- ~450ms wa-sqlite

##### Comment 9k deletes
- ~40ms pglite
- ~700ms wa-sqlite

While the shadow table deletes take similar time for wa-sqlite (~500ms), the shadow table uses a triple composite key of 3 string columns. There's room for significant optimization there, concatenating the parameters and deleting based on the concatenated PK columns reduced the time to execute from ~500ms to ~50ms - pglite also had a very small improvement but hard to measure.

I think it's possible to avoid having a composite primary key for the shadow table since we know it's 3 string columns and they can be collapsed into one if that proves to be a significant optimization, but that is outside of the scope of this fix, just raising it here as a potential optimization.

2024-06-24 12:48 UTC, kevin-dp requested changes
I left some comments, mainly simplifications for the unit tests.
Also don't forget to add a changeset.

2024-06-24 12:48 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/builder.ts
> +    columns: string[],
I'd argue to keep the type parameter `T` because that way we can be sure that the provided columns are actual keys of the provided records.

2024-06-24 12:48 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/builder.ts
> +    columns: string[],
If we want we can do `T extends Row`

2024-06-24 12:48 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/pgBuilder.ts
> +    const useTuples = typeof args[0] === 'object'
Could you add a comment here explaining what's going on when the `args` array is 2-dimensional?
In which case would you pass a 2-dimensional array? of args?

2024-06-24 12:48 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/sqliteBuilder.ts
> +    return `(${columns.map((c) => `"${c}"`).join(`, `)}) IN (${
can map `quote` as you did in the PG query builder.

2024-06-24 12:48 UTC, kevin-dp commented on clients/typescript/test/migrators/builder.ts
> +        sql: `DELETE FROM test WHERE ("a", "b") IN (${
would be cleaner to modify the constant directly:

```ts
const withValues = builder.dialect !== 'SQLite' ? ' VALUES ' : ''
```

And then here and in the strings below:
```ts
`DELETE FROM test WHERE ("a", "b") IN (${withValues}(...))`
```

2024-06-24 12:48 UTC, kevin-dp commented on clients/typescript/test/migrators/builder.ts
> +      builder.dialect === 'SQLite'
This is not the way to do it. This won't work if tomorrow we add another dialect.
The query builder abstraction has a `makePostionalParam` method.
So you can use `builder.makePositionalParam(i)` instead.
Also don't think this `posArgs` array is needed here. Can just inline it in the SQL statement.
Please also fix this in the rest of these tests.

2024-06-24 12:48 UTC, kevin-dp commented on clients/typescript/test/migrators/builder.ts
> +        sql: `DELETE FROM test WHERE ("a", "b") IN (${
Note that the query builder abstraction has a method `abstract pgOnly(query: string): string` that you can use for doing exactly this.

```ts
`DELETE FROM test WHERE ("a", "b") IN (${builder.pgOnly(" VALUES ")}(...))`
```

This comment applies to most tests you introduced here.

2024-06-25 07:42 UTC, msfstef commented on clients/typescript/src/migrators/query-builder/pgBuilder.ts
> +    const useTuples = typeof args[0] === 'object'
I will add an explanatory comment on the abstract method's docstring to cover all cases - `args` is 2-dimensional if we're comparing  multiple columns against a list of rows basically.

2024-06-25 10:20 UTC, icehaunter requested changes
small nitpicks, but GJ otherwise!

2024-06-25 10:20 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      fakeOplogEntries as unknown as Record<string, string>[],
I'm not a fan of a forced cast here - we lose any benefit of a generic with a `keyof`. There is a better way to fix this by specifying `OplogEntry` to be a `type` instead of an interface.

```diff
diff --git a/clients/typescript/src/satellite/oplog.ts b/clients/typescript/src/satellite/oplog.ts
index bc748c02d..d88991fec 100644
--- a/clients/typescript/src/satellite/oplog.ts
+++ b/clients/typescript/src/satellite/oplog.ts
@@ -24,7 +24,7 @@ export type Tag = string
 export type ShadowKey = string
 
 // Oplog table schema.
-export interface OplogEntry {
+export type OplogEntry = {
   namespace: string
   tablename: string
   primaryKey: string // json object
diff --git a/clients/typescript/src/satellite/process.ts b/clients/typescript/src/satellite/process.ts
index 64523c32b..7b66cbde1 100644
--- a/clients/typescript/src/satellite/process.ts
+++ b/clients/typescript/src/satellite/process.ts
@@ -40,6 +40,7 @@ import {
   ReplicatedRowTransformer,
   DataGone,
   ServerTransaction,
+  Row,
 } from '../util/types'
 import { SatelliteOpts } from './config'
 import { Client, Satellite } from './index'
@@ -1566,8 +1567,7 @@ export class SatelliteProcess implements Satellite {
     const stmts = this.builder.prepareDeleteBatchedStatements(
       `DELETE FROM ${this.opts.shadowTable} WHERE`,
       ['namespace', 'tablename', 'primaryKey'],
-      // force casting as only the three string entries will be used
-      fakeOplogEntries as unknown as Record<string, string>[],
+      fakeOplogEntries,
       this.maxSqlParameters
     )
 
@@ -1589,7 +1589,7 @@ export class SatelliteProcess implements Satellite {
         ...this.builder.prepareDeleteBatchedStatements(
           `DELETE FROM ${fqtn} WHERE`,
           pkCols,
-          gone.map((x) => x.oldRecord) as Record<string, SqlValue>[],
+          gone.map((x) => x.oldRecord as Row),
           this.maxSqlParameters
         )
       )
```

2024-06-25 11:16 UTC, msfstef commented on clients/typescript/test/migrators/builder.ts
> +        ).join(', ')})`,
I see your point (which is why I had it more hardcoded before) as this also introduces a dependency to `makePositionalParam`, but it does make the test more adaptable and ultimately what is being tested (the correct grouping of the positional parameters in an `IN` clause) is still covered so I think I'll leave it as is

2024-06-26 07:52 UTC, kevin-dp approved these changes
Great job, left a few minor comments.

2024-06-26 07:52 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/builder.ts
> +    columns: Extract<keyof T, string>[],
Extracting only the keys that are strings is neat but it seems unnecessary since `T extends Row` and `Row` is defined as `type Row = { [key: string]: SqlValue }`. But if you think it's best to have it for robustness in case we extend the definition of `Row` later, i'm fine with that too.

2024-06-26 07:52 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/builder.ts
> +    columns: Extract<keyof T, string>[],
What i meant with my previous comment was to define this function like this:
```ts
prepareInsertBatchedStatements<T extends Row>(
  baseSql: string,
  columns: Array<keyof T>,
  records: T[],
  ...
)
```

This makes sure that the strings in `columns` correspond to the keys of the rows passed in `records`.

2024-06-26 07:52 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/sqliteBuilder.ts
> +    args: (string | string[])[]
This type is different from the type of `args` in `createInClause` in `pgBuilder.ts`. Is this intentional?

2024-06-26 07:52 UTC, kevin-dp commented on clients/typescript/test/migrators/builder.ts
> +        ).join(', ')})`,
Indeed, we could have a separate unit test to ensure correct working of `makePositionalParam`.

2024-06-26 07:52 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/builder.ts
> +   * columns have a value present in the given tupleArgs array
i don't see a "tupleArgs array" on an "args" array.
So the `args` is basically either a row or a list of rows right?
And we check that the columns array matches one of those rows.

2024-06-26 08:01 UTC, msfstef commented on clients/typescript/src/migrators/query-builder/builder.ts
> +   * columns have a value present in the given tupleArgs array
whoops I'll fix the docstring!

yep the args are either a list of values or a list of rows, depending on whether you're inserting data to a single column or multiple columns

2024-06-26 09:12 UTC, kevin-dp commented on clients/typescript/src/migrators/query-builder/builder.ts
> +   * columns have a value present in the given tupleArgs array
Could you add this phrase to the docstring please? Found this more comprehensible :)

2024-06-26 09:17 UTC, msfstef commented on clients/typescript/src/migrators/query-builder/builder.ts
> +    columns: Extract<keyof T, string>[],
Although this works for `prepareInsertBatchedStatements` it does not work for `prepareDeleteBatchedStatements` because I want the columns to be `string`, and TS casts `keyof Record<string, any>` to also include `number` and `symbol`.

For the delete batching I'll enforce the columns to be strings - the only reason this is not the case in the insert batching is because the insert batching adds the column names in the `sqlBase` already.

2024-06-26 09:23 UTC, msfstef commented on clients/typescript/src/migrators/query-builder/builder.ts
> +   * columns have a value present in the given tupleArgs array
The docstring is expanded below to describe the case for single and multiple columns as well

2024-06-26 09:25 UTC, msfstef commented on clients/typescript/test/migrators/builder.ts
> +        ).join(', ')})`,
added a simple test for `makePositionalParam` so this should now be covered

2024-06-26 10:47 UTC, merged