Server to client error messages
electric-sql/electric pull request #1406
Opened 2024-06-27 12:26 UTC by robacourt

2024-06-28 08:54 UTC, alco requested changes

2024-06-28 08:54 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +    _ -> raise DataValidationError, message: "Unexpected value for :date column: #{inspect(val)}"
This ignored the specific error message from any of the function calls above and substitutes that with this generic message. That's not a problem, IMO, but then we don't need those extra catch-all clauses you added below, such as `Month our of range` and others.

Also, this needs to be a `reraise` to preserve the original stacktrace:
```suggestion
    _ -> reraise DataValidationError, [message: "Unexpected value for :date column: #{inspect(val)}"], __STACKTRACE__
```

2024-06-28 08:54 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +        raise DataValidationError, message: "Non integer value given for #{type} column: #{val}"
```suggestion
        raise DataValidationError, message: "Non-integer value given for #{type} column: #{val}"
```

2024-06-28 08:54 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +    _ -> raise DataValidationError, message: "Unexpected value for :time column: #{inspect(val)}"
The same considerations as for the other use of `rescue` above apply here 

```suggestion
    _ -> reraise DataValidationError, [message: "Unexpected value for :time column: #{inspect(val)}"], __STACKTRACE_
```

2024-06-28 09:51 UTC, kevin-dp commented
Minor comment but i think the error that is displayed on the client should make very clear that this is a server-side error, otherwise it will confuse people and they will think there is a problem with the client.

2024-07-01 09:52 UTC, robacourt commented on components/electric/lib/electric/satellite/serialization.ex
> +    _ -> raise DataValidationError, message: "Unexpected value for :date column: #{inspect(val)}"
Great points. I've left the raise in `assert_valid_year!/1` since that is used without being rescued in `decode_column_value!/2`

2024-07-01 10:08 UTC, robacourt commented
> Minor comment but i think the error that is displayed on the client should make very clear that this is a server-side error, otherwise it will confuse people and they will think there is a problem with the client.

The error message is now:

`an error occurred in satellite: INVALID_REQUEST Server error: Unexpected value for int2 column: 32769`

Hope that's clean enough @kevin-dp ?

2024-07-03 12:22 UTC, merged