Remove auth token management from Satellite client
electric-sql/electric pull request #141
Opened 2023-05-03 15:47 UTC by alco

Fixes VAX-660.

See individual commit messages for more details.

2023-05-22 13:22 UTC, kevin-dp reviewed
Great work!
I left some minor comments here and there, mainly questions.

2023-05-22 13:22 UTC, kevin-dp commented on clients/typescript/src/satellite/process.ts
> +    if (!authState) {
Are you sure this is what you want to test?
The previous test `authState !== undefined` would succeed if the `authState` variable is not undefined.
This new test will succeed if `authState` is a falsy value (e.g. `false`, `undefined`, or anything that JS considers to be falsy).

2023-05-22 13:22 UTC, kevin-dp commented on clients/typescript/test/client/model/table.test.ts
> +  { clientId: '', token: 'test-token' }
The `authState` argument is defined as optional.
Why do we need to provide it in this test (and some of the other tests) ?
Either it is not really an optional argument (in which case we should change the type to reflect that) or it is really optional and we can simply remove it here and in the other tests.

2023-05-22 13:22 UTC, kevin-dp commented on clients/typescript/test/satellite/process.timing.test.ts
> +  const { dbName } = t.context as any
I would prefer that you extend the `ContextType` with `token` rather than removing it and replacing it by `any`.
I know that many of these tests just use `any`, but we should eventually fix it and type it correctly; `ContextType` is a first step towards typing it correctly and it would be good to at least use that type whenever we modify or create new tests. At some point we should take the time to use it in all tests.

2023-05-22 13:22 UTC, kevin-dp commented on e2e/satellite_client/src/client.ts
> +  const mockKey =
Why are we using mock keys and a test user id in this production code?
Is it because it is not yet fully supported?

2023-05-23 14:52 UTC, alco commented on clients/typescript/src/drivers/better-sqlite3/index.ts
> +  authState?: AuthState,
I've refactored the code and introduced a separate interface called `AuthConfig`. It defines `clientId` to be optional and is used in user-facing `electrify()` functions.

The `AuthState` interface has the same two fields: `clientId` and `token` but both are required.

2023-05-23 14:55 UTC, alco commented on clients/typescript/test/satellite/process.timing.test.ts
> +  const { dbName } = t.context as any
After you left this comment, I tried updating all instances of `as any` to `as ContextType` but that results in errors due to the tests calling some private APIs on `satellite`. So I've had to leave some insances of `as any` unchanged.

2023-05-23 14:59 UTC, alco commented
@kevin-dp Check out the two new commits I've just pushed.

You'll notice that `authConfig` is optional in some methods defined in `src/satellite/registry.ts`. That's because if I change any of those instances of `authConfig?` to `authConfig`, type issues appear in `registry.test.ts` in all instances of `await mockRegistry.ensureStarted(`. I'm not sure if I need to add a stub `authConfig` argument to all those calls. The tests pass fine without it and I don't have sufficient understanding of what's going on there to judge.

2023-05-24 08:12 UTC, kevin-dp requested changes
Changes look good. Left some very minor comments.

2023-05-24 08:12 UTC, kevin-dp commented on clients/typescript/src/satellite/mock.ts
> +  async start(_authConfig?: AuthConfig): Promise<ConnectionWrapper> {
In the `Satellite` interface this argument is required, here it is optional.
Is this normal?

2023-05-24 08:12 UTC, kevin-dp commented on clients/typescript/test/satellite/process.tags.test.ts
> +  const authState = { clientId: '', token: 'test-token' }
I believe we can just provide the `token` without a `clientId` here.

2023-05-24 08:12 UTC, kevin-dp commented on clients/typescript/test/satellite/process.test.ts
> +  const authState = { clientId: '', token: 'test-token' }
Same, don't think we need `clientId` here.

2023-05-24 08:12 UTC, kevin-dp commented on clients/typescript/src/satellite/process.ts
> +        : await this._getClientId()
If we provide the empty string as `clientId` it is the same as not providing any `clientId` right?
Later in the tests we often provide `clientId: ''`, we can then remove all of those.

2023-05-24 09:22 UTC, kevin-dp approved these changes

2023-05-24 13:05 UTC, merged