feat: clean shapes on PITR
electric-sql/electric pull request #1541
Opened 2024-08-19 13:32 UTC by kevin-dp

Postgres supports Point In Time Recovery (PITR) whereby the DB is recovered to a certain point in time. If someone performs a PITR, the current state of Electric does not match the state on PG.

Postgres has the concept of timelines. When performing a PITR, the timeline ID changes. Thus, in this PR we modify Electric to keep track of the Postgres timeline ID. Every time the connection to PG is restarted, we check the Postgres timeline ID. If it is different from the one Electric knows, then we clean all shapes and update the timeline ID in our cache.

Limitations and TODOs:
- Currently, i only implemented an **in-memory** timeline cache.
- @magnetised is working on persistent storage, he may want to add a persistent timeline cache atop his persistent storage mechanism such that the unit tests use the in-memory cache (as is the case now) but actual apps use the persistent timeline cache. Note that this will require the introduction of a timeline storage behavior (which is not yet present in this PR).

2024-08-26 09:09 UTC, balegas commented
Closes #1516

2024-08-27 09:46 UTC, kevin-dp commented
Fixes https://github.com/electric-sql/electric/issues/1506.

@balegas this PR does not seem to address #1516 as that one is about handling timelines in a smarter way, whereas this PR implements a blunt approach that cleans all shapes when a PITR is detected.

2024-08-28 12:26 UTC, balegas commented
We only want to do the blunt approach for the time being. Would the PR be up to review in that case?

2024-08-28 13:31 UTC, kevin-dp commented
> We only want to do the blunt approach for the time being. Would the PR be up to review in that case?

Unfortunately, not yet. I'm waiting for Garry's work on the revised storage to land before adding persistent storage of timeline information to this PR.

2024-09-03 11:12 UTC, magnetised requested changes
I think this would be simpler as a single module if possible, but critically pls see my comments re writing to the kv.

2024-09-03 11:12 UTC, magnetised commented on packages/sync-service/test/test_helper.exs
> +Mox.defmock(Electric.ShapeCacheMock, for: Electric.ShapeCacheBehaviour)
I added a `Support.Mocks` module to avoid duplicate mock defs in a previous PR - they were spread all over the place and were causing sporadic errors on compilation. Could you put this there pls

2024-09-03 11:12 UTC, magnetised commented on packages/sync-service/lib/electric/timeline.ex
> +    Shapes.clean_all_shapes(opts)
this is going to conflict so badly with my open pr... 😭

2024-09-03 11:52 UTC, kevin-dp commented on packages/sync-service/lib/electric/timeline_cache.ex
> +    PersistentKV.set(kv, @timeline_key, timeline_id)
Right, that's what i wanted to ask you this morning but then it seemed to work by just writing an integer. The KV store should definitely have the same behavior across all implementations to avoid such corner cases :)

Re "load", yes naming is not ideal. It basically stores if provided and otherwise loads from storage.

2024-09-04 09:42 UTC, magnetised requested changes
Am I being annoying? Sorry. I think this feature could take up less space -- it's pretty self-contained.

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/lib/electric/timeline.ex
> +    PersistentKV.set(kv, @timeline_key, timeline_id)
```suggestion
    :ok = PersistentKV.set(kv, @timeline_key, timeline_id)
```

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/lib/electric/timeline.ex
> +    kv_backend = Keyword.fetch!(opts, :persistent_kv)
could we dry this up a touch. the duplication of creating the kv instance here and in `load_timeline/1` makes it easy for the two versions to drift out of sync.

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/lib/electric/timeline.ex
> +    Shapes.clean_all_shapes(opts)
if we're passing the shape cache in the opts here, why the indirection via `Shapes` - we could just directly use the shape cache value here and call `shape_cache.clear_all_shapes`.

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/lib/electric/timeline.ex
> +    handle(pg_timeline, electric_timeline, opts)
`handle` would be better called `verify` or `validate` to be clear about what it's doing.

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/test/electric/timeline_test.exs
> +      kv = Electric.PersistentKV.Memory.new!()
could we add a very simple read/write check with a real kv backend. I'd feel better knowing that we're going to read what we write...

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/lib/electric/timeline.ex
> +  defp handle(pg_timeline_id, electric_timeline_id, _opts)
bit of elixir technique, if you want to match on two values being identical, you just have to use the same name twice, that way the match only happens if the two values are the same, so in this case you could replace this function + when clause with 

`defp handle(timeline_id, timeline_id, _opts) do`

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache.ex
> +    #        ideally we'd want an `:ets.select_delete` where the pattern matches any `shape_id` that is in the `shape_ids` list
do we need this comment? we need to delete the shape information from the kv store, so we either need to iterate them here or have a dedicated function in ShapeStatus that deletes everything in a single ets call plus a single kv write.

But I think the iteration is fine considering the (rare) circumstances, the ShapeStatus behaviour is already complex enough

2024-09-04 09:42 UTC, magnetised commented on packages/sync-service/lib/electric/shapes.ex
> +    shape_cache.clean_all_shapes(server)
i don't think we need this function, but looking at the implementation we shouldn't be requiring that the `opts` has a `server` key, that's assuming a specific implementation of the shape cache -- the call should be `shape_cache.clean_all_shapes(opts)`

2024-09-04 11:57 UTC, kevin-dp commented on packages/sync-service/lib/electric/timeline.ex
> +    handle(pg_timeline, electric_timeline, opts)
I renamed it `verify_timeline`.

2024-09-04 12:03 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes.ex
> +    shape_cache.clean_all_shapes(server)
Fixed the implementation.
Couldn't we say the same thing about `clean_shape`?
All it does it call `shape_cache.clean_shape`.
I added this one to be consistent with the other ones + we can call this function anywhere we need it instead of having to every time fetch the shape cache out of the ops and then call it (and also more maintainable if later on we change the opt name for instance).

2024-09-04 12:15 UTC, kevin-dp commented on packages/sync-service/test/electric/timeline_test.exs
> +      kv = Electric.PersistentKV.Memory.new!()
My reasoning was that any storage implementation implements the `PersistentKV` abstraction and so they should all be equivalent.
I will change this to use the fylesystem storage backend but ultimately, don't we want to change the in-memory storage backend to behave the same as the filesystem one (i.e. only read and write strings) ?

2024-09-04 12:25 UTC, kevin-dp commented
@magnetised addressed most of your feedback. Few things that i didn't address yet, left some comments there asking for clarifications :-)

2024-09-06 07:39 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes.ex
> +    shape_cache.clean_all_shapes(server)
Moved it to the Timeline module as per your request 👍

2024-09-09 09:09 UTC, magnetised approved these changes
Looks great. I've added some very nit-picky comments. How hard would it be to do an end-to-end test of this?

2024-09-09 09:26 UTC, kevin-dp commented
@magnetised Doing an e2e test of this would definitely be a separate PR. I've done it once locally on my machine but it is very finicky as you need to do a PG dump, and need to configure PG to make backups to a certain folder and then restart in a mode that restores a certain backup, etc.

2024-09-09 11:53 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes.ex
> -
good catch!

2024-09-09 11:58 UTC, merged