Move to process- and storage-per-shape
electric-sql/electric pull request #1551
Opened 2024-08-21 13:20 UTC by magnetised

Fixes #1522

2024-08-21 22:43 UTC, balegas commented
We should be able to run some benchmarks against this PR to validate the assumptions. It all sounds quite sane, therefore it will be nice to see the speed up.

Let’s check with the team how to take those numbers.

2024-08-22 09:47 UTC, magnetised commented on packages/sync-service/test/support/mocks.ex
> +defmodule Support.Mock do
I've moved these mocks to a shared module because I was getting sporadic errors caused by multiple test modules trying to generate the same mocks simultaneously.

2024-08-26 13:21 UTC, kevin-dp approved these changes
I went through the code changes (skipped most of the changes in the tests though).
Changes look good to me, the `GenStage` refactoring made it sometimes a bit hard to understand what's going on from the diffs as a lot of code has moved.

2024-08-26 13:21 UTC, kevin-dp commented on packages/sync-service/lib/electric/shape_cache/storage.ex
> +  # TODO: remove this, or assert that opts are per-shape?
Is this TODO still relevant?

2024-08-26 13:21 UTC, kevin-dp commented on packages/sync-service/lib/electric/shape_cache/storage.ex
> +  # @doc "Store a relation containing information about the schema of a table"
Can remove these commented functions

2024-08-26 13:21 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes/shape.ex
> +  # TODO: test this machinery of cleaning shapes on any migration
Can remove this comment. We decided to just go with blunt clean on any migration approach.

2024-08-26 13:27 UTC, magnetised commented on packages/sync-service/lib/electric/persistent_kv/filesystem.ex
> +      with file_path = mkdir(fs, key),
The keys - at least ATM - are not from user or app data, they're created by us so there's no particular need for input sanitising.

2024-08-26 13:31 UTC, magnetised commented on packages/sync-service/lib/electric/persistent_kv.ex
> +defprotocol Electric.PersistentKV do
I personally prefer protocols for this kind of interface as a protocol is basically implementation pointer plus (fixed) configuration. Our current impl is basically re-implementing this via behaviours. My rule of thumb about protocols vs behaviours is if the api mutates the config then use behaviours, if the config is static, use protocols, but as I say, this is just my personal choice. If this is going to confuse things I can re-write.

2024-08-26 13:37 UTC, magnetised commented on packages/sync-service/lib/electric/persistent_kv/memory.ex
> +        notify(memory, {:set, key, value})
> Or will an Agent always finish the current function set before get is executed because they are an abstraction on top of Erlang processes and thus this is not possible?

This. Plus this notify is a test-only thing (the whole implementation is a test-only thing)

2024-08-26 13:40 UTC, magnetised commented on packages/sync-service/lib/electric/postgres/inspector.ex
> +          type_mod: integer() | nil,
Ah, my bad. I was just updating the types based on usage in the code. There are also a bunch of refs to `type_modifier` - is this the same thing?

2024-08-26 13:48 UTC, magnetised commented on packages/sync-service/lib/electric/postgres/inspector.ex
> +          type_mod: integer() | nil,
Yeah, the `DirectInspector` returns both the `type_id` tuple and this `type_mod` so the type spec is accurate, at least in terms of the values coming out of the pg query

2024-08-26 13:49 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/storage.ex
> +  # TODO: remove this, or assert that opts are per-shape?
Mostly...

2024-08-26 13:56 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/inspector.ex
> +          type_mod: integer() | nil,
Yeah, `type_modifier` is on the replication stream. Should be the same thing, it just originates from a different place (replication stream vs explicit DB query by the inspector).

2024-08-27 14:38 UTC, icehaunter approved these changes
I like the changes, and what they give us in terms of potential scalability. I think this warrants a rewrite of the `Storage` api to better reflect a per-shape approach, wdyt?

2024-08-27 14:38 UTC, icehaunter commented on packages/sync-service/lib/electric/shapes/consumer.ex
> +    :ok = ShapeCache.Storage.add_shape(config.shape_id, config.shape, storage)
I don't understand the point of this or `list_shapes` call, if the storage is per-shape as it is right now. Can you explain this bit please?

2024-08-28 08:34 UTC, magnetised commented on packages/sync-service/lib/electric/shapes/consumer.ex
> +    :ok = ShapeCache.Storage.add_shape(config.shape_id, config.shape, storage)
Yeah, this is temporary. Didn't want to totally re-write the storage api in this pr. I've created #1563 which documents the requirements. This `list_shapes` call should be replaced with some "get the current position" function which gets the snapshot xmin and offset for the shape.

2024-08-28 08:35 UTC, magnetised commented
> I like the changes, and what they give us in terms of potential scalability. I think this warrants a rewrite of the `Storage` api to better reflect a per-shape approach, wdyt?

already planned: #1563

2024-08-28 08:55 UTC, icehaunter commented
So this PR doesn't bring that much performance benefits on it's own:
1. Snapshot creation is already done in separate `Task` process in `main`, so no benefits here
2. `CubDB` is used in a same way, so same overhead costs for open-close-rename files on each
3 `CubDb` transaction is NOT the answer, it turned out. I did a local test, and what it does is force you to accumulate changes in memory AND THEN write them in bulk, which is not what we want for large shapes.

It *should* bring perf benefits when we're fanning out a txn over 1k+ existing shapes, but I don't have a bench for that ready yet.

2024-08-28 08:58 UTC, icehaunter requested changes
Given the new process arch, a bug or failure-to-write to a log a particular shape becomes unrecoverable, right?
Current arch crashes the writer process, which crashes the replication client, which will continue from an unacknowledged txn, which will get re-written to all shapes, which is safe because we have a test that a write to the same offset in storage is idempotent
New arch crashes the writer process, which does nothing to the producer, and when it's back up it continues consuming transactions not knowing that some of those were missed.
I think we need to know how to address that before merging

2024-08-28 09:24 UTC, magnetised commented
Requirement for handling of crashed consumers documented here: https://github.com/electric-sql/electric/issues/1585

2024-08-28 09:24 UTC, icehaunter approved these changes
OK to merge, not OK to release until #1585 is addressed

2024-08-28 09:35 UTC, merged