Rob/support missing comparison predicates
electric-sql/electric pull request #1569
Opened 2024-08-27 12:06 UTC by robacourt

2024-08-28 09:31 UTC, icehaunter requested changes
LGTM, with one request about explicit casts

2024-08-28 09:31 UTC, icehaunter commented on packages/sync-service/lib/electric/replication/eval/env/explicit_casts.ex
> +  | unknown   | bool           | unknown_to_bool |
Why do we need that explicit cast? I believe that an explicit `::bool` cast shouldn't be special-cased here in this list, but instead should always work for a `NULL` value, as it always tries to work for text values

2024-08-28 09:31 UTC, icehaunter commented on packages/sync-service/lib/electric/replication/eval/parser.ex
> +  defp between_sym(expr, left_bound, right_bound, refs, env) do
Can you add a comment here about suboptimality of recalculating a subtree for both branches? We don't have to address it today, just for the futute

2024-08-28 10:42 UTC, robacourt commented on packages/sync-service/lib/electric/replication/eval/parser.ex
> +  defp between_sym(expr, left_bound, right_bound, refs, env) do
Out of curiosity, how would it be optimised? I thought of doing a seeing whether the left or right bounds were greater before doing the between but I'm didn't think that would be any quicker apart from in specific cases such as left bound and right bound being constants.

2024-08-28 12:12 UTC, robacourt commented on packages/sync-service/lib/electric/replication/eval/env/explicit_casts.ex
> +  | unknown   | bool           | unknown_to_bool |
Something like this? https://github.com/electric-sql/electric/pull/1569/commits/d18be4af952bd884ee8c20284e3e424532b43e0e

2024-09-02 19:09 UTC, robacourt commented on packages/sync-service/lib/electric/replication/eval/parser.ex
> +  defp between_sym(expr, left_bound, right_bound, refs, env) do
Done.

2024-09-02 19:18 UTC, merged