Resume crashed consumers at a consistent point
electric-sql/electric pull request #1594
Opened 2024-08-29 16:27 UTC by magnetised

Fixes #1585

Firstly this moves the replication client, shape cache, consumer supervisor and log  collector under a supervisor with strategy :one_for_all.               
                                                                       
Then a crashing client triggers the `handle_cancel/3` callback in the log  collector which terminates and causes the entire supervision tree to  restart.

Shape consumers are configured with `:manual` demand. Along with the `BroadcastDispatcher` this enables us to make the  `store_transaction/2` callback to be synchronous: it will only return when all consumers have processed/stored the transaction.

To make this work, I had to re-wire the relation handling to replace the previous use of event partitioning over the existing GenStage pipeline -- instead of pushing relation messages out of the log collector producer and having them consumed by the shape cache, they're instead sent directly to the shape cache via a call.

We could in theory write our own dispatcher implementation to manage this if we need the relation messages in the genstage pipeline (for consistency reasons) but for the moment just using a simple call seems like the right call.

2024-08-29 16:31 UTC, magnetised commented on packages/sync-service/lib/electric/application.ex
> +      connection_manager_opts = [
because of the way we've structured the postgres connection initialisation, the connection manager is responsible for starting the shape consumer pipeline via `Shapes.Supervisor`. This isn't great, but to restructure we'd have to re-write the connection configuration probing, which feels out of scope

2024-09-02 14:13 UTC, kevin-dp reviewed
Looks good to me!
The GenStage refactoring is above my paygrade though so an Elixir expert should review that. Also, `integration.test.ts` is said to have changed but there are only whitespace differences, this seems to be unintentional.

2024-09-03 10:26 UTC, magnetised commented
> Also, `integration.test.ts` is said to have changed but there are only whitespace differences, this seems to be unintentional

Actually that was intentional -- poking around to get the tests to pass and cleaned the ws in passing

2024-09-04 11:32 UTC, icehaunter requested changes
This is a bit more complicated than I expected, but I've wrapped my head around the logic here apart from one core question. I'll be happy to approve once that's documented. Also got a couple of questions/nitpicks

2024-09-04 11:32 UTC, icehaunter commented on packages/sync-service/lib/electric/shapes/consumer.ex
> +  end
I don't understand this. First, is this case even possible? Is `handle_events` ever called with an empty list? Second, wouldn't this put us in a position where we've not asked for more on a fullfilled demand, and thus we'll never recieve more?

2024-09-04 11:32 UTC, icehaunter commented on packages/sync-service/lib/electric/replication/shape_log_collector.ex
>      GenStage.call(server, {:new_txn, txn})
I don't see from the code how, as per PR description, 

> Shape consumers are configured with :manual demand. Along with the BroadcastDispatcher this enables us to make the store_transaction/2 callback to be synchronous: it will only return when all consumers have processed/stored the transaction.

Since this is essentially the core reason for this PR, can you elaborate here and in a comment in code as to how this is acheived?

2024-09-04 14:42 UTC, magnetised commented on packages/sync-service/lib/electric/shapes/consumer.ex
> +  end
With the `BroadcastDispatcher` handle events is called with an empty list if the selector function has filtered them all out. This guard was an attempt to manage consumer demand in that case, so we don't end up asking for more demand if we haven't received any txns. But that didn't work -- the broadcast dispatcher automatically requests demand for a consumer that has filtered out events -- so this guard made the unit tests pass but the e2e tests fail... Ultimately this was the reason for 1) dropping the shape cache from the genstage pipeline then 2) implementing a dispatcher that works how we need. 

I'll remove this as it's no longer needed

2024-09-04 14:45 UTC, magnetised commented on packages/sync-service/lib/electric/replication/shape_log_collector.ex
>      GenStage.call(server, {:new_txn, txn})
I'll explain in a comment

2024-09-04 14:53 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache.ex
> +  def handle_continue(:start_log_producer, state) do
I used a continue to make sure that the current process was subscribed before the producer started emitting events. I'll work on the naming though....

2024-09-04 15:57 UTC, icehaunter approved these changes
Great job!

2024-09-04 16:09 UTC, merged