Next.js SSR example
electric-sql/electric pull request #1596
Opened 2024-08-29 21:30 UTC by balegas

Basic example using SSR.

Server caches the `Shape`  and renders the Shape data for the initial client request.
This avoid an extra RTT after the page is loaded on the client.

**Discussion**
- [ ] Requires changing `Shape` API to accept initial set of values
- [ ] Example can use a `ShapeStream` instead of `Shape` for simplicity

2024-08-30 14:09 UTC, KyleAMathews reviewed
Left a few comments.

Don't you want to use either https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props or https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props here? Right now I don't see that any data is being cached during server rendering.

EDIT: Oh I see... this is RSC stuff

2024-08-30 14:09 UTC, KyleAMathews commented on examples/nextjs-ssr-example/app/page.tsx
> +  noStore()
why (again) no server rendering?

2024-09-01 23:17 UTC, balegas commented on examples/nextjs-ssr-example/app/Home.tsx
> +  // Can't render entries on the server because order of
If we want to provide an API to render shapes on the server/client, we need to des/serialise the payload into json deterministically. Right now, we use Maps, which don't ensure any order of key iteration.

I thought of ordering the elements. If we're doing the example and moving on, we should just educate what's happening on the example, otherwise we could fix this ourselves and people could use useShape out-of-the box.

Note that we need to patch react-hook anyways for this to work, so we might also solve the ser/deserialization ordering issues

2024-09-01 23:19 UTC, balegas commented on packages/typescript-client/src/client.ts
> +        url.searchParams.set(`_`, Math.random().toString())
I tried that with no great luck. I spent an evening figuring out what was going on. 
When I'm back I'll give another look and raise an issue with them.

2024-09-01 23:21 UTC, balegas commented on examples/nextjs-ssr-example/app/page.tsx
> +  noStore()
This turns static rendering on the server off. Was the best working solution I've found.

2024-09-01 23:29 UTC, KyleAMathews commented on examples/nextjs-ssr-example/app/Home.tsx
> +  // Can't render entries on the server because order of
Shapes in general don't have any order guarantees so we don't need to worry about serialization and deserialization messing with things.

2024-09-02 06:22 UTC, balegas commented on examples/nextjs-ssr-example/app/Home.tsx
> +  // Can't render entries on the server because order of
You do, because hydration on the client fails if elements are rendered in a different order from the server

2024-09-02 14:26 UTC, KyleAMathews commented on examples/nextjs-ssr-example/app/Home.tsx
> +  // Can't render entries on the server because order of
Ok sure. While browser engines don't guarantee orders of maps they all seem to serialize and deserialize the same.

2024-10-03 11:24 UTC, balegas commented on examples/nextjs-ssr-example/app/Home.tsx
> +  // Can't render entries on the server because order of
Doing server rendering of items now.
Ordering elements based on creation time, since serialization order is not guaranteed to hold

2024-10-03 11:26 UTC, balegas commented on packages/typescript-client/src/client.ts
> +        url.searchParams.set(`_`, Math.random().toString())
Moved this elsewhere. The problem still persists.

2024-10-03 11:29 UTC, balegas commented on examples/nextjs-ssr-example/app/page.tsx
> +const fetchClient: typeof fetch = (...args) => {
Still need to do this hack, despite nextjs [documentation](https://nextjs.org/docs/app/building-your-application/caching). Maybe someone has any idea

2024-10-03 11:33 UTC, balegas commented on examples/nextjs-ssr-example/app/page.tsx
> +  return <Home shapes={{ items: getSerializedShape(itemShape) }} />
When I came back to this example, my naive intention was to use the shapeCache in the React hook to be able to preload a shape and then in the client component, I would just load the shape.

I didn't find any way of passing server-side data to a client component without going through the component properties, which is not transparent. I think this code is quite clean, but I'm not sure if it's possible to do best.

I didn't want to investigate using external storage for that, since I considered that would be out of scope of the example.

2024-10-03 11:53 UTC, thruflo commented on examples/nextjs-ssr-example/app/page.tsx
> +  return <Home shapes={{ items: getSerializedShape(itemShape) }} />
I wonder how useful this pattern is.

Generally, we can sync data that is available for low latency / edge SSR.

Pushing that data to the client as serialised JSON in the html source seems … a bit old school and bloats the page that you’re trying to accelerate.

With default SSR you have to make sure the data is exactly the same. Unless we can somehow work around that.

I wonder if it’s better to have the server render and then have the client take over once the data is synced into the client. But only if we can make the pattern work?

2024-10-03 12:32 UTC, balegas commented on examples/nextjs-ssr-example/app/page.tsx
> +  return <Home shapes={{ items: getSerializedShape(itemShape) }} />
The client receives the rendered page (with the items) with the response.
That JSON object is used to hydrate the shape when the component renders in the client, which will allow it to resume shape sync at the position that the server was, instead of starting from scratch.

2024-10-08 16:44 UTC, thruflo commented
Great stuff @samwillis :)

On 2, I wonder if there's a way of supporting `order_by` and `limit` of the shape results? An arbitrary query is powerful but means the user needs to format the results in the same way as the shape data. This will become harder as and when we support nested associations. So is there an approach where the user could order/limit/(filter?) the shape when convenient and then drop down to a function when that's not expressive enough?

2024-10-25 11:34 UTC, balegas commented on examples/nextjs-ssr-example/app/page.tsx
> +  noStore()
That did the trick! thanks

2024-10-25 14:54 UTC, balegas reviewed
@samwillis inspired on your example and [Nextjs docs](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers), I gave another try. The idea here is to have a context around the component that takes the server-sent data from props and initializes the shapes on the client --- totally transparent on the client component!

 Left some comments

2024-10-25 14:54 UTC, balegas commented on examples/nextjs-ssr-example/app/ssr-shapes-provider.ts
> +    useShape({ ...shapeOptions, shapeData })
We don't need to call useShape, can refresh the cache directly

2024-10-25 14:54 UTC, balegas commented on packages/react-hooks/src/react-hooks.tsx
> -  return JSON.stringify(options, Object.keys(options).sort())
I needed this, but I think the sorted shapes can't be for all options of the shape, otherwise we can have multiple shapes depending on specific options for the call.

I think we need `headers` because of authorization

2024-10-25 14:54 UTC, balegas commented on examples/nextjs-ssr-example/app/page.tsx
> +    <SSRShapesInitializer serializedShapes={[{ data, serverOptions }]}>
I think this removes the problem of initializing shapes data  by passing the data on useShape and is more of an explicit pattern than injection

2024-10-25 14:54 UTC, balegas commented on packages/typescript-client/src/shape.ts
> +  constructor(stream: ShapeStreamInterface<T>, shapeData?: ShapeData) {
I can remove this now (by having a specific method to hydrate shape caches)

2024-10-25 14:54 UTC, balegas commented on examples/nextjs-ssr-example/app/Home.tsx
> +const shapeOptions: () => ShapeStreamOptions<Row> = () => {
I think this is still not great, we should have a single place to declare shape options, however the urls are different from _outer_ shape options. However, it is not a very bad pattern either thinking this is the shape for the component and is decoupled from the _wrapping_ we did for sending server data

2024-10-25 15:01 UTC, balegas commented
> Render a subset of the data on the server,

@samwillis, @thruflo my initial idea was to call the database directly on the server. This is a powerful pattern to show, but because of the problems with ordering and paging, I thought it would be better to build on Shapes on the server too and don't go into those problems. Note that there is a benefit with this that we build on caching again and don't put load on the database.

A naive way of rendering the subset of data on the server is to just drop it :)

2024-11-12 14:07 UTC, balegas commented
@samwillis , I did a DX refactoring addressing your concerns with it being simple to specify the shapes across server and client. Have a look at it or ping me to see together.

I also want to replace the base nextjs example with this one (cc @KyleAMathews)

2024-11-22 09:08 UTC, thruflo commented on .github/workflows/deploy_examples.yml
> +        working-directory: examples/nextjs-ssr-example
Just a naming nit: there's no need to suffix with `-example`, that's communicated by the parent folder name, so I would suggest `examples/nextjs-ssr`.

2024-11-22 09:10 UTC, thruflo commented on examples/nextjs-ssr-example/README.md
> +# Next.js SSR example
Generally, the README for an example should ideally communicate a bit about what it's trying to show you, i.e.: what is the example, why is it interesting, what can you achieve with the pattern it demonstrates, etc. Plus perhaps some signposts into key parts of the code.

2024-11-22 09:11 UTC, thruflo commented on examples/nextjs-ssr-example/public/logo.svg
We're purple nowadays/

2024-11-22 09:14 UTC, thruflo commented on packages/react-hooks/src/react-hooks.tsx
> +  shapeHandle: string | undefined
Another very minor nit but seeings how this is in the react-hooks library not just the example, I've been trying to move us towards just using `handle` rather than `shapeHandle`.

Below when you getSerialisedShape you can also just read it from `shape.handle` rather than `shapeStream.shapeHandle`.

2024-11-22 09:15 UTC, thruflo commented on packages/react-hooks/src/react-hooks.tsx
> +    offset: shapeStream.offset,
Does `offset` work? Is the property not `lastOffset`?

2024-11-22 09:15 UTC, thruflo commented on packages/typescript-client/src/client.ts
> +  get offset() {
I think this is duplicated now -- we already expose lastOffset as a public getter.

2024-11-25 09:24 UTC, balegas commented on examples/nextjs-ssr-example/README.md
> +# Next.js SSR example
Will work on that when we decide to publish

2024-11-25 09:25 UTC, balegas commented on packages/react-hooks/src/react-hooks.tsx
> +  shapeHandle: string | undefined
yep, i started this a while back, things like the offset were not public at the time. Will cleanup.

2025-01-07 11:43 UTC, gruckion commented
I’ve read over the comments on the front page. Not dug into the files changed yet.

I believe this approach should be using hydration and suspense.



https://react.dev/reference/react/Suspense

2025-01-07 12:43 UTC, gruckion requested changes
Nice work 👍

2025-01-07 12:43 UTC, gruckion commented on examples/nextjs-ssr-example/app/Home.tsx
> +"use client"
In nextJS the file naming conventions are lower kebab case. 

https://nextjs.org/docs/app/api-reference/file-conventions

https://x.com/kentcdodds/status/1361536960876085248?s=46

2025-01-07 12:43 UTC, gruckion commented on examples/nextjs-ssr-example/app/Home.tsx
> +import { v4 as uuidv4 } from "uuid"
Avoid external dependencies. You do not need one for a cryptographically secure uuid anymore.

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

https://x.com/benlesh/status/1857451931427352654?s=46

2025-01-07 12:43 UTC, gruckion commented on examples/nextjs-ssr-example/app/Home.tsx
> +  const { data: items } = useShape(getProxiedOptions(options)) as unknown as {
As unknown as any? Can generics not be used here?

2025-01-07 12:43 UTC, gruckion commented on examples/nextjs-ssr-example/app/Home.tsx
> +      {optimisticItems
Avoid using sort and map directly in the render response. Use a cost above with useMemo.

Also do not use index as the key.

https://react.dev/learn/rendering-lists#why-does-react-need-keys

2025-01-07 12:43 UTC, gruckion commented on examples/nextjs-ssr-example/app/shape-proxy/[...table]/route.ts
> +  const originUrl = new URL(
Cleaner to just throw if the environment variable is missing or use an escape guard.

2025-01-07 12:43 UTC, gruckion commented on examples/nextjs-ssr-example/app/utils.ts
> +    const controller = new AbortController()
Using fetch and AbortControllers adds a lot of bloat. Maybe use useQuery which has solved this problems already and provides a beautiful API.

Tanstack react query

2025-05-08 11:48 UTC, balegas commented
We're probably not going to work on this anymore

2025-05-08 11:48 UTC, closed without merging

2025-05-25 22:20 UTC, balegas commented
It does support SSR. You can come up with your own tailored SSR implementation.
#2232 is a follow up of this PR that has more convenient abstractions.

We're happy to help someone finish this work.