feat: Log chunking
electric-sql/electric pull request #1606
Opened 2024-09-02 16:17 UTC by msfstef

Addresses https://github.com/electric-sql/electric/issues/1581

Will outline work done tomorrow, need to add some more tests as well - also I have deviated from the original design due to [this thread](https://electric-sql.slab.com/posts/rfc-chunking-the-log-2zee9qad#thread-xqaece2t).

I have externalised the chunk index from within the log itself but have kept it in storage - this might have a non-trivial impact on performance due to the additional IO involved in 1) storing the checkpoints and 2) reading the checkpoints on every request.

The benefits of externalising the index is that it makes it queriable, so we can still immediately know the end offset of a chunk before actually streaming it, which allows parallelisation of requests etc.

2024-09-02 16:20 UTC, KyleAMathews commented
It could be neat to build https://github.com/electric-sql/electric/issues/1534 as part of this PR to check what the browser experience is like.

2024-09-03 12:40 UTC, robacourt requested changes
I think you've missed the InMemoryStorage, it still has an ETS table. But otherwise it looks great! Good job! 🚀

2024-09-03 12:40 UTC, robacourt commented on packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
> +    chunk_checkpoint_ets_table_name =
There shouldn't be an ETS table now, right?

2024-09-03 12:40 UTC, robacourt commented on packages/sync-service/test/electric/shape_cache/log_chunker.exs
> +      # assert :ok = LogChunker.add_to_chunk(large_string, threshold)
Why's this commented out?

2024-09-03 13:41 UTC, robacourt commented on packages/sync-service/lib/electric/shape_cache/in_memory_storage.ex
> +    chunk_checkpoint_ets_table_name =
Ahh, of course. Make sense.

2024-09-03 13:42 UTC, robacourt approved these changes
Approved! Nice work @msfstef !

2024-09-03 15:17 UTC, merged