feat (client): expose time elapsed since last sync
electric-sql/electric pull request #1625
Opened 2024-09-04 10:09 UTC by kevin-dp

This PR fixes https://github.com/electric-sql/electric/issues/1468 as it exposes a `lastSynced` getter on the `ShapeStream` and `Shape` classes which is the number of milliseconds since last sync with the server.

2024-09-04 10:11 UTC, icehaunter approved these changes
LGTM, but add a changeset pls

2024-09-04 10:21 UTC, kevin-dp commented
@icehaunter Thanks for the quick review!

Btw, this PR does not fully address the linked issue because @KyleAMathews was proposing to also put `isUpToDate` to false. But i'm uncertain about that and left [some comments](https://github.com/electric-sql/electric/issues/1468#issuecomment-2328477067) on the issue.

2024-09-04 10:24 UTC, msfstef approved these changes
Looks good! I see you've left a comment regarding the `isUpToDate` so will continue from there!

2024-09-04 16:15 UTC, KyleAMathews requested changes

2024-09-04 16:15 UTC, KyleAMathews commented on packages/typescript-client/src/client.ts
> +          this.connected = true
we also need to check if the user is subscribed — if not then they're never "connected"

2024-09-06 07:03 UTC, kevin-dp commented
@KyleAMathews i re-introduced the `isUpToDate` getter on the `Shape` class because it is being used by the react hooks which expose an `isUpToDate` field on the shape data: https://github.com/electric-sql/electric/blob/main/packages/react-hooks/src/react-hooks.tsx#L89

I'm not sure what we want to do with that. It seems that no example is currently using that `isUpToDate` field on the data and the name is misleading so i would drop it altogether. wdyt?

2024-09-06 07:14 UTC, kevin-dp commented on packages/typescript-client/src/client.ts
> +          this.connected = true
Why do we want to tie them together?
Connectivity status is not affected by subscriptions imo.
Note the `try.. finally` block i introduced around the `while` loop which ensures that when we stop fetching the shape, the `connected` flag is put to false. So if a user creates a shapestream with `subscribe: false` the flag will only be true for a very brief period of time, between L418 and the `finally` block.

2024-09-06 13:36 UTC, KyleAMathews commented on packages/typescript-client/src/client.ts
> +          this.connected = true
`connected` means you're subscribed and currently getting updates. It just doesn't mean anything if you're doing a one-time fetch. I guess it doesn't really matter though as someone wouldn't use `connected` anywhere in the case they're doing a one-off fetch.

2024-09-06 13:38 UTC, KyleAMathews commented
>  It seems that no example is currently using that isUpToDate field on the data and the name is misleading so i would drop it altogether. wdyt?

Yeah... it's really just an internal state. For consumers of the Shape, the shape is *always* up-to-date. If we're getting new data, we don't tell them about it until we've caught up with the Log. So not exposing it makes sense to me.

2024-09-06 14:30 UTC, kevin-dp commented on packages/typescript-client/src/client.ts
> +          this.connected = true
Ok, i added the extra check.

2024-09-06 14:53 UTC, KyleAMathews approved these changes
Great dx improvement, thanks!

2024-09-06 14:53 UTC, KyleAMathews commented on .changeset/brown-turtles-listen.md
> +"@electric-sql/client": patch
Technically this is a breaking change now so let's make this a minor (and update it to tell about the field we're removing).

2024-09-06 15:03 UTC, merged