[WIP] feat: `PersistedShapeStream` with generic storage interface
electric-sql/electric pull request #1630
Opened 2024-09-04 16:30 UTC by msfstef

Addresses https://github.com/electric-sql/electric/issues/1519

Opening PR for visibility - not done yet.

2024-09-06 12:46 UTC, kevin-dp requested changes
This PR introduces many changes which makes it hard to review and merge.

I'm mainly concerned with the way how the code changed to handle synchronous and asynchronous callbacks differently. The message processor used to handle every callback as an asynchronous callback (also synchronous ones). As a result, the code was clear and concise. However, this PR handles sync callbacks differently (mainly to avoid JS pushing synchronous continuations on the microtask queue). As a result, code is written in a continuation passing style everywhere which makes it harder to understand.

I had a brief discussion with @icehaunter which shared the concern and would also stick with `await` for now. If performance is a concern here, we should benchmark a sync storage with the old implementation (that always awaits) and with the optimized implementation that doesn't await.

2024-09-08 17:42 UTC, KyleAMathews commented
> an operation might be stored with offset 10_3, and the metadata fails to get stored because the app shuts down - so upon resuming the 10_3 operation is fed to the subscriber but then the stream is resumed from the previous latest offset that we managed to persist (e.g. 10_2), duplicating the change.

We could also filter out the extra operations to avoid the duplicates.

That seems better so that on loading we can immediately send the sync call and not have to wait to load all the old data first.

2024-09-09 02:59 UTC, KyleAMathews commented
How about we put this on the back burner for some time? Being able to persist the shape log will be a nice feature at some point but it's not particularly urgent until we get a lot more users and some that definitely need this. Most users won't need this and I don't think it's worth a lot of time to benchmark and fine-tune this — especially if it requires a big refactor.

2024-10-08 16:41 UTC, KyleAMathews commented
This is pretty out-of-date w/ main & not a priority so I'll close it for now.

2024-10-08 16:41 UTC, closed without merging