fix: correctly fetch shadow tag in migration tests
electric-sql/electric pull request #166
Opened 2023-06-01 07:26 UTC by kevin-dp

The migration tests start by populating the DB with 2 rows, one with id 1 and one with id 2.
Some migration tests would fetch the shadow tag for row 1 or 2 and then delete that row using the tag.
To fetch the tag we would first fetch the oplog entries and then fetch the shadow entry for the oplog entry corresponding to the insert of row 1 or 2.

However, the oplog entries were empty because in the setup of the test we acknowledge the initial insertions of row 1 and 2 and thus the oplog gets GC'ed (line 30 -> if you check `await satellite._getEntries()` before that line then you will see the 2 oplog entries, but after that line they are gone).

The problem can however easily be solved by fetching all shadow entries and then taking the one for row 1 or 2 depending which one we want to delete:
```
const shadowEntries = await satellite._getOplogShadowEntry()
const shadowEntryForRow2 = shadowEntries.find(entry => entry.primaryKey === 2)
```

2023-06-01 08:43 UTC, icehaunter approved these changes

2023-06-02 09:50 UTC, balegas requested changes
Blocking this to have the opportunity to discuss before merging.
I've been on the tail for gc race conditions and I want to know we're solving the right problem.

2023-06-02 09:50 UTC, balegas requested changes
Blocking this to have the opportunity to discuss before merging.
I've been on the tail for gc race conditions and I want to know we're solving the right problem.

2023-06-19 10:32 UTC, icehaunter commented
@balegas I've converted this to draft to not be in the "active PRs" list. Feel free to un-draft when that discussion actually happens.

2023-08-24 15:30 UTC, closed without merging