Add a SQLite backed storage implementation
electric-sql/electric pull request #1742
Opened 2024-09-23 10:54 UTC by magnetised

Alternative to the hybrid file + cubdb storage implementation.

Currently implemented with both snapshots and log written to sqlite, but we could always go back to the hybrid model if this is an issue.

To improve test reliability I upped some waits in the typescript client test. This is not because of slowness in the sqlite implementation afaict because the same tests were failing with the old file storage backend.

Naive benchmarking puts this at ~10-100x faster to append to the log than the cubdb version.

2024-09-23 11:26 UTC, magnetised commented on packages/sync-service/config/runtime.exs
> +# default_file_storage_impl = Electric.ShapeCache.SQLiteStorage
was hesitant to make this the default but then did make sqlite the default for the tests, so maybe should have just gone for it...

2024-09-23 11:32 UTC, magnetised commented on packages/sync-service/config/runtime.exs
> +# default_file_storage_impl = Electric.ShapeCache.SQLiteStorage
in fact maybe I should add an option to the env... on it

2024-09-23 11:53 UTC, magnetised commented
> hey, this looks nice! Would love to see the performance of this with our benchmarks. Particularly interested in knowing how it handles lots of shapes and lots of writes

It's basically a dupe of the cubdb storage, but with sqlite as the db and replacing the pure file-dump snapshot with a table in sqlite. Each shape will have its own db so this is basically the same characteristics as for cubdb but with faster writes (~10-100 microseconds for a log append as opposed to ~4ms)

>     * Do you handle log compaction, or have an idea on how we'd implement it?

No, haven't touched it, haven't thought about it. We could do it with say replacing within a range in the db. with sqlite we have the advantage of having multiple tables within the file, so there may be some kind of dupe table, compact, rename or overwrite table dance within isolated snapshots. we could use multiple concurrent tables and have some pointer? dunno, lots of options though
 
>     * The same questions for chunking. Is that just a range query :D?

I've replicated the cub db version, with chunk log offsets in a separate table and then the same log stream offset stuff.

2024-09-23 12:42 UTC, msfstef approved these changes
Looks good! Left a few questions here and there, one point about potentially wanting transactional writes for some things?

2024-09-23 12:42 UTC, msfstef commented on packages/typescript-client/test/integration.test.ts
> +    await sleep(100)
```suggestion
    await vi.waitFor(async () => {
      const res = await fetch(
        `${BASE_URL}/v1/shape/${issuesTableUrl}?offset=-1`
      )
      const body = (await res.json()) as Message[]
      expect(body.length).greaterThan(1)
    })
```

We use this approach elsewhere, probably better than fiddling with timeouts

2024-09-23 12:42 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +      if Keyword.get(opts, :readonly, false) do
Why not make this configuration part of the `storage_opts` and instead introduce an additional `opts` arg? The `storage_opts` are already different per storage implementation and we don't currently have a per shape options requirement?

2024-09-23 12:42 UTC, msfstef commented on packages/sync-service/lib/electric/replication/log_offset.ex
> +  @spec last?(t()) :: boolean()
nit: a doctest for good measure?

2024-09-23 12:42 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +         :ok <- Exqlite.Sqlite3.bind(conn, statement, params),
```suggestion
         :ok <- Sqlite3.bind(conn, statement, params),
```

2024-09-23 12:42 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +         {:read, {:row, row}} <- {:read, Sqlite3.step(conn, stmt)},
Why not this?
```suggestion
         {:row, row} <- Sqlite3.step(conn, stmt),
```

2024-09-23 12:42 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +  def select(%S{conn: conn}, query) do
nit: this is public and unused (?)

2024-09-23 12:42 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +    Enum.reduce(log_items, {append_stmt, chunk_stmt}, fn
should this all be done in a transaction? also, could it potentially be more efficient to split boundaries and log entries and write them sequentially (although I'm assuming that if it is done transactionally writes are optimized)?

2024-09-23 12:42 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +    stmts = [
should this all be done transactionally?

2024-09-23 13:04 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +         {:read, {:row, row}} <- {:read, Sqlite3.step(conn, stmt)},
I wanted to be absolutely sure that `else` condition below was definitely catching the case where we're reading from an empty db. Might be overkill but I wanted an explicit condition

2024-09-23 13:05 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +  def select(%S{conn: conn}, query) do
I'll leave some docs or something. It's just a way to query sqlite as a stream, otherwise there's no builtin way to get a list of results for a query and that will be annoying when debugging etc

2024-09-23 13:07 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +      if Keyword.get(opts, :readonly, false) do
aah yeah that makes sense thank you - might be worth adding a short comment here with a reference to the 1 writer multiple readers that make this necessary

2024-09-23 13:07 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +    Enum.reduce(log_items, {append_stmt, chunk_stmt}, fn
TX around this is a good idea. I started with txns but removed them to allow for partial reads from a snapshot but you're right.

No idea about splitting the two writes.

2024-09-23 13:24 UTC, kevin-dp commented
@balegas 

>     * Do you handle log compaction, or have an idea on how we'd implement it?

@marc-shapiro, @preguica, and I had a discussion regarding the format of the shape log and log compaction during last last week's on-site. Currently, we store the shape as a sequence of changes, where every change has an offset. After compaction, every PK will have a single entry in the log with the offset of the latest write (insert/update/delete) to that PK. The format where the shape log is stored as a sequence of changes seems good for storing in files on disk.

However, we can have an alternative representation for the shape log, that is more appropriate for storing in a DB. We could have a table per shape that for every PK that is part of the shape tracks its latest value and the "time"/"offset" at which that value was written. When a row is updated or deleted, we update its value and the offset in that shape's table. When a user requests a shape, starting at a given offset, we query the table for all rows with an offset > the provided offset.

The advantage of this approach is that we only ever store the compacted log (as for updates/deletes we effectively update the entry for that row in the DB). Another advantage is that we don't have to implement and maintain our own file-based storage system which is probably quite complex if we want to properly optimize that.

2024-09-23 13:33 UTC, robacourt approved these changes
Looks good to me. Nice work! I'm just in the process of running some benchmarks for it

2024-09-23 13:52 UTC, magnetised commented on packages/typescript-client/test/integration.test.ts
> +    await sleep(100)
I think this is a good idea but maybe not for this PR.

2024-09-23 14:08 UTC, kevin-dp requested changes
Great job, i like moving the storage to SQLite!
I left some comments in the code as well as a comment on this PR wrt the format of the shape log we store. While the shape log was a good format for storing e.g. in a file, i think it is not a good format for storing in a relational database. Instead, we could modify the format to be more like a dictionary (cf. my other comment). Ultimately, we would have to benchmark that change to see which format performs best.

2024-09-23 14:08 UTC, kevin-dp commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +            {:rows, rows} -> {List.flatten(rows), {:stream, conn, stmt}}
Wouldn't it be safer if we explicitly order the rows based on their offset?
This only works because the rows are inserted in the order of their offsets.
Also, i find it a bit strange that we are inserting a row per offset, just for the purpose of being able to find the end offset of a chunk.
Can't we save space by keeping only 1 row per `offset_tx` and always updating the `offset_op` to the largest `offset_op` we have seen for that `offset_tx` ?

2024-09-23 14:23 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +            {:rows, rows} -> {List.flatten(rows), {:stream, conn, stmt}}
@kevin-dp that would mean that you cannot chunk transactions, which is definitely something we want to be able to do?

2024-09-23 15:08 UTC, kevin-dp commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +            {:rows, rows} -> {List.flatten(rows), {:stream, conn, stmt}}
Not sure why not? This function's name suggests that it returns the last offset in the chunk, but i don't see any chunking related logic here. It seems to just return the next offset that is in the log.

2024-09-23 16:08 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/file_storage.ex
> +  def for_shape(shape_id, storage, opts \\ [])
@kevin-dp this pattern, where you define the function head but no body, allows you to define defaults for args. you need this when you're pattern matching on the args in other function heads.

2024-09-23 16:11 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +            {:rows, rows} -> {List.flatten(rows), {:stream, conn, stmt}}
> Wouldn't it be safer if we explicitly order the rows based on their offset?

The query does that, 

```elixir
"""                             
SELECT data                     
  FROM #{@log_table} #{where}   
  ORDER BY offset_tx, offset_op 
"""
```

2024-09-23 16:13 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +            {:rows, rows} -> {List.flatten(rows), {:stream, conn, stmt}}
@kevin-dp this is just a copy of the implementation for cubdb backed by sqlite. there may well be optimisations we can do on it to make it even faster but let's just figure out if the approach is faster for the same impl before we start optimising the details.

2024-09-23 16:19 UTC, magnetised commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +    %LogOffset{tx_offset: tx_offset_min, op_offset: op_offset_min} = offset
> But then numbering them makes it very confusing, would be less confusing if we use ? for all of them.

I disagree. I think numbering them makes it all very explicit and has the benefit of counting the params for us. 

However, i did try removing the duplication of the params. I didn't bother before, despite thinking about it, because, well, I got lazy as it seemed a very minor thing and I had other fish to fry. But it works if you have two `?1` params in the query. 

Will push an update

2024-09-23 16:21 UTC, magnetised commented on packages/sync-service/lib/electric/replication/log_offset.ex
> +  def last?(%LogOffset{tx_offset: @last_tx, op_offset: @last_op}), do: true
with that approach you put a little more stress on the GC as you're creating a new struct that will need to be garbage collected later. with my fiddly pattern matching version there's no garbage. i worry about the garbage.

2024-09-23 16:33 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +            {:rows, rows} -> {List.flatten(rows), {:stream, conn, stmt}}
@kevin-dp the `chunk_offset_table`, if that's what you're referring to, doesn't add an entry for every row, it adds an entry for every "chunk checkpoint" in order to be able to determine the chunk boundaries, so it is quite sparse.

I might be getting confused with what you're referring to, we can sort it out on a call.

2024-09-24 06:37 UTC, kevin-dp commented on packages/sync-service/lib/electric/replication/log_offset.ex
> +  def last?(%LogOffset{tx_offset: @last_tx, op_offset: @last_op}), do: true
isn't Elixir smart enough to recognize that this is in fact a constant and that only one `last()` struct should ever exist?

2024-09-24 06:41 UTC, kevin-dp commented on packages/sync-service/lib/electric/shape_cache/sqlite_storage.ex
> +            {:rows, rows} -> {List.flatten(rows), {:stream, conn, stmt}}
@magnetised right, my bad. Had missed the order by clause.

2024-10-08 16:42 UTC, balegas commented
We've decided not to move on with this approach while we have other performance gains to work on besides the speed of the storage backend. I'm closing the pull request.

2024-10-08 16:42 UTC, closed without merging