feat: Chunk prefetching in `ShapeStream`
electric-sql/electric pull request #1743
Opened 2024-09-23 11:33 UTC by msfstef

Followup to https://github.com/electric-sql/electric/pull/1731

Implemented a fetch wrapper that does not wait for the chunk bodies to be streamed to the client and processed by the subscribers, and instead prefetches a number of chunks from the network as soon as the available headers to determine the next chunk are available.

I also had to implement another response header on our api called `electric-chunk-up-to-date`, similarly to how we use `electric-chunk-last-offset`, which allows us to know all the necessary chunk metadata without having to read the actual body. If we do not know if a chunk is an `up-to-date` chunk, we don't know whether we should request the next one, and whether its caching policy should be adjusted on the CDN.

I've set the default for prefetching to 2 chunks, but we could increase this to the most commen [maximum browser connections to the same domain](https://www.geeksforgeeks.org/what-are-max-parallel-http-connections-in-a-browser/) in order to maximise parallelization.

2024-09-23 14:21 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> delete_resp_header("electric-chunk-up-to-date")
`delete_resp_header` is only used in live queries, right? Perhaps worth briefly documenting this.

2024-09-23 14:30 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> delete_resp_header("electric-chunk-up-to-date")
Added a comment

2024-09-23 14:49 UTC, kevin-dp requested changes
Nice work!
I left some comments, nothing major.

2024-09-23 14:49 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> put_resp_header("electric-chunk-up-to-date", "true")
do we need to put this to `true`? Can we just not assign a value to it or if not possible just the empty string?
The presence of this header serves as a flag so removing the value or making it smaller minimizes what needs to be sent over the network.

2024-09-23 14:49 UTC, kevin-dp commented on packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
> +      assert Plug.Conn.get_resp_header(conn, "electric-chunk-up-to-date") == ["true"]
We should also test that `electric-chunk-up-to-date` header is correctly removed when we are in live mode and a TX comes in which is split into several chunks (only the last chunk should have the header).

2024-09-23 14:49 UTC, kevin-dp commented on packages/typescript-client/src/client.ts
> +    const fetchWithPrefetchAndBAckoffClient = createFetchWithChunkBuffer(
Typo in this variable's name. The `A` in `BAckoff` shouldn't be capitalized.

2024-09-23 14:49 UTC, kevin-dp commented on packages/typescript-client/src/client.ts
> +    const fetchWithPrefetchAndBAckoffClient = createFetchWithChunkBuffer(
This variable is only used once so there's no real need to assign it here, can immediately assign it to `this.#fetchClient`.

2024-09-23 14:49 UTC, kevin-dp commented on packages/typescript-client/src/fetch.ts
> +      // ignore prefetch errors
aren't the errors already caught by `prefetchPromise.catch(...)`?

2024-09-23 14:49 UTC, kevin-dp commented on packages/typescript-client/src/fetch.ts
> +      return prefetchRes
Since we serve a prefetched result, don't we need to prefetch the next one now?

2024-09-23 14:49 UTC, kevin-dp commented on packages/typescript-client/src/fetch.ts
> +    // otherwise clear current prefetched responses (and abort active requests)
let's clarify here in the comment why we need to clear the prefetched responses.
I'm guessing because what is being requested does not match what has been prefetched so something's off?

2024-09-23 14:52 UTC, msfstef commented on packages/typescript-client/src/fetch.ts
> +      // ignore prefetch errors
The async errors from the `prefetchPromise` are caught by the `.catch` clause, but any sync errors caused before the promise is even returned are caught by the `try...catch`

2024-09-23 14:53 UTC, msfstef commented on packages/typescript-client/src/fetch.ts
> +      return prefetchRes
Aaah very good point - I'll add a test for this and implement the right thing

2024-09-23 14:55 UTC, msfstef commented on packages/typescript-client/src/fetch.ts
> +    // otherwise clear current prefetched responses (and abort active requests)
Yeah since we're using a map and also rely on the map size for the max prefetched responses, if any request comes through this wrapper that is not on the "chain" created by the current map we want to wipe the map clean and start again.

Obviously this wrapper is not super generic and is meant to be used expicitly with `ShapeStream` but I think having this escape hatch is safer - an example would be shape rotations

Will add a comment explaining this further

2024-09-23 15:07 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> put_resp_header("electric-chunk-up-to-date", "true")
We don't _need_ to, but it does enhance the semantics at the cost of 4 bytes - by this argument we could say that we should name headers `electric-ecutd` to save a few bytes on request header keys I think

2024-09-23 15:11 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> put_resp_header("electric-chunk-up-to-date", "true")
It also can make users believe it could be `false`, which is not the case.

2024-09-23 15:41 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> put_resp_header("electric-chunk-up-to-date", "true")
Right, but it indicates that it is a flag - which means that if it's missing it's false. This is similar to our `live` query parameter where we set `live=true`, although we could technically just do `live=` and it would still work

2024-09-23 16:38 UTC, msfstef commented on packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
> +      assert Plug.Conn.get_resp_header(conn, "electric-chunk-up-to-date") == ["true"]
Hmm at the moment live requests will never actually serve an incomplete chunk as we set the chunk last offset to serve to the latest available, received with a notification. Adding a test for a case that does not occur is a bit too verbose imo, and removing the safety net feels a bit unnecessary?

2024-09-23 16:40 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> put_resp_header("electric-chunk-up-to-date", "true")
Either way I removed the `"true"` value as it is unnecessary so I don't have a strong opinion on it either way

2024-09-24 06:52 UTC, kevin-dp commented on packages/sync-service/test/electric/plug/serve_shape_plug_test.exs
> +      assert Plug.Conn.get_resp_header(conn, "electric-chunk-up-to-date") == ["true"]
Ok, just a bit weird that we have a code path that cannot occur and that we cannot test either

2024-09-24 06:53 UTC, kevin-dp approved these changes

2024-09-24 11:55 UTC, KyleAMathews reviewed
This looks good in general. Our little simple client is growing up 😆 

Have you tested this manually on a site that does have a bunch of chunks? The tests look pretty through but seeing it live would be good to double-check everything is wired up correctly.

2024-09-24 11:55 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> assign(:up_to_date, [])
Also we should reduce the ttl for caching per https://github.com/electric-sql/electric/issues/1447

2024-09-24 11:55 UTC, KyleAMathews commented on packages/typescript-client/src/fetch.ts
> +    if (prefetchedRequest) return prefetchedRequest
could we use `{`s? That's the normal pattern so I my eye always gets confused for a bit when I see braceless code.

2024-09-24 12:08 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> assign(:up_to_date, [])
Yep that's on the chunking todo (determine ttl based on chunk type)

2024-09-24 12:09 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +      |> assign(:up_to_date, [])
cool 👍

2024-09-24 12:09 UTC, msfstef commented on packages/typescript-client/src/fetch.ts
> +    if (prefetchedRequest) return prefetchedRequest
Sure - we should probably add a lint rule, I won't do that for this PR, but I'll edit this

2024-09-24 12:40 UTC, msfstef commented
https://github.com/user-attachments/assets/bb67103d-4856-4726-ae58-20d715419d5b


@KyleAMathews  seems to be working fine with linearlite! You can see how with this prefetching I've made it so that the next request is fired off before the previous one has streamed all of its body yet (using the metadata in the headers) - this is >100k issues on linearlite initial sync

2024-09-24 13:15 UTC, kevin-dp approved these changes
Definitely better!

2024-09-24 13:15 UTC, kevin-dp commented on packages/typescript-client/src/fetch.ts
> +        this.#prefetchQueue.get(url)?.[0] ??
Under which circumstances can it be that the URL is already in the prefetch queue?

2024-09-24 13:24 UTC, KyleAMathews approved these changes
:shipit: 

Looks great @msfstef!

2024-09-24 14:10 UTC, msfstef commented on packages/typescript-client/src/fetch.ts
> +        this.#prefetchQueue.get(url)?.[0] ??
Removed it as it _should_ be unnecessary, although it is harmless and a good safety measure

2024-09-24 14:20 UTC, merged