fix: Handle replication slot conflicts
electric-sql/electric pull request #1762
Opened 2024-09-26 14:02 UTC by msfstef

Addresses https://github.com/electric-sql/electric/issues/1749

- Makes publication and slot names configurable via a `REPLICATION_STREAM_ID` env variable, which can ultimately be used for multiple electric deploys
- Quotes all publication and slot names to address potential issues with configurable names (alternative is to force downcase them when initialised to avoid nasty case-sensitive bugs)
- Adds one step to the replication connection state machine that tries to acquire an advisory lock based on the replication slot
  - If more than one Electric tries to connect to the same replication slot (with the same `REPLICATION_STREAM_ID`), it will make a blocking query to acquire the lock that will resolve once the previous Electric using that slot releases it - this addresses rolling deploys
  - Could potentially switch to `pg_try_advisory_lock` that is not a blocking query but immediately returns whether the lock could be acquired and implement retries with backoff, but since using `pg_advisory_lock` simplifies the implementation I decided to start with that and see what people think.
 

Things that I still need to address:

- Currently the publication gets altered when a shape is created (adds a table and potentially a row filter) but no cleanup occurs - so the publication can potentially grow to include everything between restarts and deploys even if it is not being used.
  - The way I want to address this is to change the `Electric.Postgres.Configuration` to alter the publication based on _all_ active shapes rather than based on each individual one, in that case every call will update the publication as necessary and resuming/cleaning can be a matter of calling this every time a shape is deleted and once upon starting (with recovered shapes or no shapes). Can be a separate PR.

2024-09-26 19:01 UTC, msfstef commented
@KyleAMathews in the case of a crash and a subsequent recovery, the new Electric would start consuming the replication slot so there shouldn't be a need to delete it (?) - the only case where the slot should be deleted would be when a cleanup needs to happen, which is either with a controlled shutdown of Electric (without a new one replacing it) or a separate orchestration mechanism that needs to clean up replication slots.

As for testing, I plan to add some integration tests with lux to simulate handoffs and shutdown and recovery, but at the moment I am facing an issue where if I try to acquire a lock with `pg_advisory_lock`, which results in a query that lasts until the lock is acquired, `Postgrex` blocks the connection pool process and I can't "query" it for it's status in order to reply to health checks.

Someone with more Elixir experience should be able to help with this (@alco feel free to look into this tomorrow if you want), I started working on a solution with `pg_try_advisory_lock` but I like the idea of Electric starting to consume the replication stream _as soon_ as the lock is released rather than having retries with backoffs.

2024-09-26 19:24 UTC, KyleAMathews commented
> the new Electric would start consuming the replication slot so there shouldn't be a need to delete it

Oh ok so if an instance does, postgres knows the replication slot doesn't have a listener so let's the new instance grab it?

2024-09-30 14:17 UTC, msfstef commented
> postgres knows the replication slot doesn't have a listener so let's the new instance grab it
We rely on the advisory lock to determine that, but essentially yeah, we leverage postgres locks to ensure we're the only ones consuming the replication lot - if we're not, we wait for the lock to be released and then become the sole consumer.

2024-09-30 14:45 UTC, msfstef commented on packages/sync-service/lib/electric/plug/health_check_plug.ex
> +      end
I was trying to more explicitly decouple the API results of the health check endpoint from the internal representations of the system state - so we can change internal status but safely keep the API the same or vice versa.

2024-09-30 14:47 UTC, msfstef commented on packages/sync-service/lib/electric/service_status.ex
> +      end
The idea was that the `ServiceStatus` package would collect information from more than just the connection manager to determine the status (e.g. storage services, anything else that's long running), and we'd combine the various service states to a final `ServiceStatus.status()` type.

In this case the connection status and service status are one and the same so it looks a bit odd, but I felt that it makes sense to keep the mapping more explicit

2024-09-30 14:49 UTC, msfstef commented on packages/sync-service/lib/electric/plug/health_check_plug.ex
> +        :stopping -> {500, "stopping"}
Yep I was thinking potentially to return 200 for all but figured a 5xx might be better for a stopping state.

We currently do not have a controlled shutdown of Electric so `:stopping` is never really accessed but I wanted the health check endpoint to be able to expose it as I think we should build a controlled shutdown path

2024-09-30 16:30 UTC, msfstef commented
Added integration test for rolling deploys as well - should be ready to review fully again now @alco

2024-09-30 16:31 UTC, msfstef commented on packages/sync-service/lib/electric/plug/health_check_plug.ex
> +      end
(added comment explaining this to both cases where the matching seems superfluous)

2024-10-01 08:47 UTC, robacourt requested changes
Great work! As discussed, I would really like a warning when it can't acquire the lock to aid with debugging the situation

2024-10-01 09:49 UTC, msfstef commented on packages/sync-service/lib/electric/connection_manager.ex
> +  def handle_cast(:lock_connection_acquired, %{pg_lock_acquired: false} = state) do
If we receive `:lock_connection_acquired` with `pg_lock_acquired` already set to true, it means that somehow the lock connection got restarted without the connection manager also restarting its state - this is not currently possible with the expected paths so I figured we'd rather see an explicit failed pattern match if it happens for whatever other reason

The alternative which I considered and remove is adding a second pattern match that basically does nothing - but since it should never get there I'd rather see an error pop up

2024-10-01 09:55 UTC, robacourt approved these changes
Great work!

2024-10-01 14:40 UTC, alco approved these changes
Stellar work! :1st_place_medal:

2024-10-01 14:40 UTC, alco commented on .changeset/poor-candles-fly.md
> +- Add `HealthCheckPlug` API endopint at `v1/health` that returns `waiting`, `starting`, `active`, and `stopping` statuses.
Nit: seems a bit misleading to me to mention `stopping` here while there's no state in which Electric would return that.

2024-10-01 14:40 UTC, alco commented on integration-tests/tests/crash-recovery.lux
> +  [sleep 2]
I'm not sure this is needed. The shape would have been created by the time a response is sent to the client request above.

2024-10-01 14:55 UTC, msfstef commented on integration-tests/tests/crash-recovery.lux
> +  [sleep 2]
good point!

2024-10-01 14:55 UTC, msfstef commented on .changeset/poor-candles-fly.md
> +- Add `HealthCheckPlug` API endopint at `v1/health` that returns `waiting`, `starting`, `active`, and `stopping` statuses.
fair enough, I'll remove the reference to it

2024-10-01 15:52 UTC, merged