feat: store incoming migrations in local DB
electric-sql/electric pull request #177
Opened 2023-06-12 15:42 UTC by kevin-dp

2023-06-13 09:43 UTC, alco commented
@kevin-dp Looks like you added `clients/typescript/.idea` to Git by accident.

2023-06-15 08:15 UTC, kevin-dp commented on clients/typescript/migrate.sh
Ignore this script.
It is outdated and will be replaced by the script in the web example app:
[https://github.com/electric-sql/electric/blob/1da282ed67780ad61c9ead1dfc57762f64aed5e5/examples/web-wa-sqlite/migrate.sh](https://github.com/electric-sql/electric/blob/1da282ed67780ad61c9ead1dfc57762f64aed5e5/examples/web-wa-sqlite/migrate.sh)

2023-06-19 12:05 UTC, icehaunter requested changes
LGTM with three nitpicks

2023-06-19 12:05 UTC, icehaunter commented on clients/typescript/src/migrators/index.ts
> +/*
[That's a lot of comments!](https://www.youtube.com/watch?v=IRl3r4q_dUY)
Let's maybe delete them for a nicer diff?

2023-06-19 12:19 UTC, kevin-dp commented on clients/typescript/src/satellite/client.ts
> +        //       or replace the `is_migration` field by an optional `version` field
Right, created a linear [issue](https://linear.app/electric-sql/issue/VAX-718/move-migration-version-field-to-satopbegin-in-protocol) for it and referenced the issue ID in this TODO in the code.

2023-06-19 12:20 UTC, kevin-dp commented on clients/typescript/src/migrators/index.ts
> +/*
Woops, yeah left them there in case i had to revert but this can go now. Thanks for catching this

2023-06-19 12:36 UTC, icehaunter approved these changes

2023-06-19 14:07 UTC, merged