fix (sync-service): let Postgres handle user-provided root table name
electric-sql/electric pull request #1776
Opened 2024-10-01 14:04 UTC by kevin-dp

This PR fixes https://github.com/electric-sql/electric/issues/1764 according to the approach that was decided by @KyleAMathews, namely to adhere to Postgres' way of handling identifiers. Therefore, this PR modifies Electric such that it passes the user-provided root table to Postgres which then returns the actual schema and table names. Which we then use throughout the rest of the code as before.

2024-10-01 14:29 UTC, KyleAMathews commented on packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
> +  def get_namespace_and_tablename(table, conn) do
I love going back to postgres as the final arbitrator on matching a name. I'm not sure though if there's caching here though? This looks like it gets called a lot which could add significant latency.

2024-10-01 14:58 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
> +  def get_namespace_and_tablename(table, conn) do
Yeah, we could modify the ETS inspector to cache the result like it does for the column info.

2024-10-03 13:24 UTC, KyleAMathews approved these changes
I gave a brief look through (gotta run to airport in a sec) and it looks great.

One thing we talked about yesterday also is including the sql statement in errors we send back — I'll make a separate issue for that.

2024-10-03 13:24 UTC, KyleAMathews commented on packages/sync-service/test/electric/plug/router_test.exs
> +                 ~s|Table "nonexistent" does not exist. If the table name contains capitals or special characters you must quote it.|
nice error message!

2024-10-08 08:52 UTC, msfstef requested changes

2024-10-08 08:52 UTC, msfstef commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
why not store everything under the same ETS table?

2024-10-08 08:52 UTC, msfstef commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    clean_column_info(relation, opts_or_state)
this could be done with a single `:ets.select_delete` statement - would we ever need to clean only columns or only relations? If not we could just keep a single `clean` API

2024-10-08 08:52 UTC, msfstef commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +            :ets.insert(state.pg_relation_table, {{relation, :relation_to_table}, table})
we can use the `pg_info_table` for both and insert them with a single `ets` call

2024-10-08 08:52 UTC, msfstef commented on packages/sync-service/lib/electric/shape_cache.ex
> +      inspector.clean({rel.schema, rel.table}, inspector_opts)
this is the only place `clean_column_info` is ever called, so why not remove all clean APIs and just keep this `clean` API for the whole relation?

2024-10-08 09:22 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
Because the tables have different semantics. The `pg_info_table` is a set whereas the `pg_relation_table` is a bag because each key (i.e. relation) has several values (namely the user provided identifiers). See comment on L110-111.

2024-10-08 09:23 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +            :ets.insert(state.pg_relation_table, {{relation, :relation_to_table}, table})
we can't, see my comment about sets vs bags before.

2024-10-08 09:39 UTC, msfstef commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
Ah I see - yep you're right, but I see that we only use this for the `tables_from_ets` API, but this PR doesn't use that anywhere? Why would we want to reverse search for the tables?

2024-10-08 09:47 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
For cleanup, when a certain relation is deleted we need to clean up the cache so we need to know all the names that were cached for that relation.

2024-10-08 09:50 UTC, msfstef commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
We could include the relation in the key of the `pg_info_table` entry like `{table, relation, :table_to_relation}` and then do a `:ets.select_delete` with a match spec like `{table, :_, :table_to_relation}` - no?

2024-10-08 09:56 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
@msfstef Conceptually i used two indexes for performance reasons. A forward index from user-provided identifier to the relation name, and a backward index from relation name to a list of identifiers. The backward index is not strictly needed as we could do a delete from the forward index of all keys where the value is the relation. But that's an expensive operation. I'm not familiar with ETS performance characteristics, but it seems to me that what you're suggesting would be more expensive as it requires searching for such keys, while in the approach with 2 indexes it's a simple lookup (no search needed).

2024-10-08 10:01 UTC, msfstef commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
Yep was thinking the same w.r.t. to performance - my only thought was that if it is an ordered set, then looking up based on a key that starts with `table` should be quick to find the match, especially given that the size of this would be small.

I understand the reasoning for the two indices, my instinct was just to keep it as a single one and change it if performance is an issue but since it's internal happy to resolve this

2024-10-08 10:03 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/inspector/ets_inspector.ex
> +    pg_relation_table = :ets.new(opts.pg_relation_table, [:named_table, :public, :bag])
Yeah, well constant vs log time complexity 😄

2024-10-08 13:27 UTC, robacourt approved these changes
Looks good to me! I just gave one nit-picky suggestion

2024-10-08 13:27 UTC, robacourt commented on packages/sync-service/lib/electric/postgres/inspector/direct_inspector.ex
> +        {:ok, {Enum.at(info, 0), Enum.at(info, 1)}}
```suggestion
        [[schema, table]] = result.rows
        {:ok, {schema, table}}
```

2024-10-08 13:40 UTC, msfstef approved these changes

2024-10-08 13:55 UTC, merged