feat: Add `columns` API query parameter to filter table columns
electric-sql/electric pull request #1829
Opened 2024-10-10 12:12 UTC by msfstef

Implements https://github.com/electric-sql/electric/issues/1804

### Overview
- I've picked `columns` as the query parameter name, as `select` might confuse people and get compared to SQL `SELECT`s, and `filter` is too close to what the `where` parameter does.
- The columns are comma separated column names, parsed at the validation stage
- If the parameter is specified, it *has to include* the primary key columns
  - We could make it such that the PK is always included, but it feels like it might be confusing - explicit is better?
  - For tables without a primary key, we treat _all_ columns as primary keys - we might want to revisit that w.r.t. to this feature
- Columns are validated also by ensuring that all specified column names match the ones in the schema
- The selected columns are stored in the `Shape` definition as an array of column names
  - We had the choice of potentially filtering the `table_info` data based on the selection of columns instead of storing them separately, but this might cause issues with relation change handling and generally I prefer the definition of the shape to contain all information related to it (i.e. the schema at the time of creation + what column filters where applied, rather than compacting the two)
- I modified `Shape` related APIs for converting changes etc to also apply the column filtering - this is all we need to ensure it works correctly for replication stream log entries
- In the `Snapshotter`, I modified a `get_column_names` method to also apply the filtering if present, which takes care of the snapshot log entries.

### Things to consider
- How do we want to handle column names with special names (quoted)? In my opinion the client needs to type them exactly as they are on postgres, otherwise they get a 400 validation error back telling them which columns are invalid, so it should be fairly easy to fix.
- Replication publication filtering of columns is available, but [updating it might cause errors](https://www.postgresql.org/docs/15/logical-replication-col-lists.html#LOGICAL-REPLICATION-COL-LIST-COMBINING) according to the PG docs, so I'm not sure if that's something we want to consider

2024-10-10 12:26 UTC, robacourt approved these changes
Neat!

2024-10-10 14:26 UTC, balegas commented
I agree with your choices. The only thing is that we can avoid the errors for PKs, but I prefer erroring.

> How do we want to handle column names with special names (quoted)? In my opinion the client needs to type them exactly as they are on postgres, otherwise they get a 400 validation error back telling them which columns are invalid, so it should be fairly easy to fix.

Please make sure it is same logic as table names, check with @kevin-dp 

> Replication publication filtering of columns is available

I think this is an important thing to have by the reasons we've discussed. Since we have a single subscriber and we know all the columns electric needs, maybe PG behaves. Please open a separate ticket to not block merging this one, but I think is one thing we want to validate it's working.

2024-10-14 08:28 UTC, kevin-dp requested changes
Some issues here:
- PG allows any character in column names if you quote them, e.g. `CREATE TABLE foo ("a,column""with-weird name" INT);`. Currently, the parser will misinterpret the comma as a separator. So we should allow column names to be quoted (is consistent with table naming parsing)
- The parser is case sensitive by default. This is inconsistent with schema and table names which are case insensitive unless you quote them.

This would be a good moment to implement https://github.com/electric-sql/electric/issues/1814 such that we have a parse function that we can use for parsing schema identifiers, table identifiers, and column identifiers.

2024-10-14 10:03 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes/querying.ex
> +  defp get_column_names(table_info, root_table, selected_columns) do
Why do you need to filter the `selected_columns` out of the column names you get from table info?
The column names are just the `selected_columns` argument itself.
I understand that this function will only return the column names in `selected_columns` that really exist in the table, but should that case be allowed?
I think we should throw a validation error in the shape plug if the user selects some columns that don't actually exist.
Then, here we can rely on the `selected_columns` and no need to get them out of the table info.

2024-10-14 10:32 UTC, kevin-dp requested changes
Well done!
I left some comments mostly asking for minor changes.

2024-10-14 10:32 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +        columns -> put_change(changeset, :columns, String.split(columns, ","))
We need additional validation to check that if the `columns` argument is provided, at least one valid column is specified.
For example, one could pass `columns=""` which would result in `[""] = String.split("", ",")` but the empty string is not a valid column name.
Probably this will be fixed with our own implementation of the PG identifier parser?

2024-10-14 10:32 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes/shape.ex
> +    {:ok, nil}
The returned tuple does not satisfy the return type in the spec.

2024-10-14 10:32 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes/shape.ex
> +      missing_pk_cols != [] ->
If someone provides a select with missing PK columns AND also invalid columns they will only get the missing PK error. Would be useful for them to also get the invalid columns error.

2024-10-14 10:32 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes/shape.ex
> +    |> Enum.map(&filter_change_columns(selected_columns, &1))
nit: i don't like the case expression being piped into `Enum.map` i would assign its result to a variable and pipe the variable into it.

2024-10-14 10:32 UTC, kevin-dp commented on packages/sync-service/lib/electric/shapes/shape.ex
> +      &case &1 do
nit: i would remove this lambda and introduce a function `filtered_columns_changed` which pattern matches directly against its argument:
```ex
defp filtered_columns_changed(%Changes.UpdatedRecord{old_record: record, record: record}), do: false
defp filtered_columns_changed(_), do: true
```

2024-10-14 10:32 UTC, kevin-dp commented on packages/typescript-client/src/client.ts
> +        if (columns)
Perhaps also check that it isn't the empty array.

2024-10-14 10:32 UTC, kevin-dp commented on website/electric-api.yaml
> +            as a comma separated list of column names exactly as they are on the database schema.
i think it should be "as they are **in** the database schema"

2024-10-14 10:49 UTC, msfstef commented on packages/sync-service/lib/electric/shapes/shape.ex
> +      missing_pk_cols != [] ->
I thought about it but eh, they will get the second error once they fix the first, IMO it's overkill

2024-10-14 12:50 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +        columns -> put_change(changeset, :columns, String.split(columns, ","))
This now gets validated in the PG identifier parser where zero-length identifiers are not allowed

2024-10-14 13:25 UTC, kevin-dp approved these changes
Brilliant!
Left a few very minor comments.
Ready to merge for my part 💯

2024-10-14 13:25 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/utils.ex
> +defmodule Electric.Plug.Utils do
Let's perhaps not introduce several utility files but keep everything in the outer `utils.ex` file?

2024-10-14 13:25 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/utils.ex
> +        # sort to keep selected columns identical
nit: sorting this list seems to be out of scope for this abstraction. This seems to be a concern of the plug rather than this parsing function

2024-10-14 13:25 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/utils.ex
> +      iex> Electric.Plug.Utils.parse_columns_param(~S|\"fo\"\"o\",bar|)
Why are the quotes escaped?
You're using a sigil so it should just be `~S|"fo""o",bar|` or am i missing something?

2024-10-14 13:25 UTC, kevin-dp commented on packages/sync-service/lib/electric/plug/utils.ex
> +      {:error, ~S|Invalid unquoted identifier contains special characters: "id|}
why is this saying "unquoted identifier" ? The sigil does contain quotes.
The problem should be that the quote inside the quote is not escaped (with a double quote).

2024-10-14 13:25 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/identifiers.ex
> +    |> String.replace(~r/""/, "\"")
nit: `"\""` is a bit confusing, `~s|"|` is easier to read

2024-10-14 13:25 UTC, kevin-dp commented on packages/sync-service/lib/electric/postgres/identifiers.ex
> +        result = String.slice(downcased_ident, 0, @namedatalen)
can remove this intermediate variable and just return `String.slice(...)`

2024-10-14 13:26 UTC, msfstef commented on packages/sync-service/lib/electric/plug/utils.ex
> +defmodule Electric.Plug.Utils do
I feel like this is not a general utility like the other ones and is more meant to be part of the Plug code - we already have a very long serve shae plug module which defines submodules, the idea is that parsing logic could move to this.

2024-10-14 13:28 UTC, msfstef commented on packages/sync-service/lib/electric/plug/utils.ex
> +        # sort to keep selected columns identical
It is important that the order does not matter as they are stored within the shape definition which generates a hash. You are right that this is probably not the right place to sort it, and a `MapSet` would be better here but it requires a significant refactor - I could sort it right before initializing the Shape though

2024-10-14 13:29 UTC, msfstef commented on packages/sync-service/lib/electric/plug/utils.ex
> +      {:error, ~S|Invalid unquoted identifier contains special characters: "id|}
The provided column was `"id` - so I'm treating this as an unquoted identifier that has included a special character `"`

2024-10-14 14:47 UTC, merged