docs: deployment guide, with supporting config and integrations.
electric-sql/electric pull request #1836
Opened 2024-10-11 14:53 UTC by thruflo

Fleshing out deployment guide. To support it, added a sync service config page in the api docs section and specific integrations pages for various deployment platforms.

Quite a lot to review here. Check out the:

- [Sync service config page at /docs/api/config](https://deploy-preview-1836--electric-next.netlify.app/docs/api/config)
- [Updated Typescript client page at /docs/api/clients/typescript](https://deploy-preview-1836--electric-next.netlify.app/docs/api/clients/typescript)
- [Deployment page at /docs/guides/deployment](https://deploy-preview-1836--electric-next.netlify.app/docs/guides/deployment)
- Individual integration pages in the "Integrations" section of the docs nav, e.g.: [AWS](https://deploy-preview-1836--electric-next.netlify.app/docs/integrations/aws), [React](https://deploy-preview-1836--electric-next.netlify.app/docs/integrations/react) and [Supabase](https://deploy-preview-1836--electric-next.netlify.app/docs/integrations/supabase)

Note that:

- Netlify has a one-click-deploy form that uses https://github.com/electric-sql/standalone-basic-example
- [Render](https://deploy-preview-1836--electric-next.netlify.app/docs/integrations/supabase) has a [Blueprint repo](https://github.com/electric-sql/render-blueprint) that also uses the same standalone-basic-example

As @KyleAMathews commented on Discord, these might be better to include in the monorepo and update using a GitHub action. Perhaps that can be a subsequent Issues / PR.

The integrations also include a [Phoenix page](https://deploy-preview-1836--electric-next.netlify.app/docs/integrations/phoenix) which is based on merging #1833 and publishing an updated release for https://hexdocs.pm/electric_phoenix/0.1.0-dev-2/Electric.Phoenix.html

Note that the deployment docs all assume a single `DATABASE_URL`, i.e.: this is pre multi-tenant.

2024-10-30 20:52 UTC, KyleAMathews requested changes
HUGE upgrade! Looks really nice! I can't claim to to have done a super detailed review as that would have taken 1 more hour but I did skim through every new page at least 😇 

I made a few suggestions here and there that should be quick to resolve.

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/api/config.md
> +  Port that the [HTTP API](/docs/api/http) is exposed on.
these markdown links aren't being rendered

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/guides/deployment.md
> +  <a href="/img/deployment/components.jpg">
We should add the API here & a section on it — most people will adopt Electric by migrating an API call which queries data with a shape call that the API proxies.

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/guides/deployment.md
> +  <a href="/img/deployment/components.jpg">
Some boilerplate for a cloudflare worker proxy would be great

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/integrations/cloudflare.md
> +For example, you could [validate an auth token](https://developers.cloudflare.com/workers/examples/auth-with-headers/) to protect access to a shape and then [proxy the request through to Electric](ht
this cloudflare auth link seems extraneous? People can auth in a million different ways so just saying "authenticate the shape request however you'd like and proxy it" seems enough

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/integrations/cloudflare.md
> +#### Sync example
```suggestion
#### Syncing data into the worker
```

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/api/config.md
> +> [!Warning] Advanced only
haha nice! Stay away PLEASE casual browsers!

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/api/http.md
>  Normative API documentation is published as an [OpenAPI](https://www.openapis.org/what-is-openapi) specification:
```suggestion
API documentation is published as an [OpenAPI](https://www.openapis.org/what-is-openapi) specification:
```

2024-10-30 20:52 UTC, KyleAMathews commented on website/docs/guides/deployment.md
> +  <a href="/img/deployment/components.jpg">
and link to the auth doc page

2024-10-30 21:10 UTC, KyleAMathews commented on website/docs/guides/deployment.md
> +You can use ***any standard Postgres***, version 15 and above.
```suggestion
You can use ***any standard Postgres***, version 14 and above.
```

We support 14 still https://github.com/electric-sql/electric/actions/runs/11601645519/job/32304875100#step:11:452

2024-10-31 00:13 UTC, balegas commented on website/docs/integrations/supabase.md
> +Make sure you untick the "Display connection pooler" option to get the direct access URL that works with logical replication. Note that this only works with IPv6, which means you will need to configu
You could explain why or link to #1885

2024-10-31 00:26 UTC, balegas commented on website/docs/integrations/gcp.md
> +## Electric and GCP
I tried running Electric in GCP and PG in Supabase and I ran into ipv6 issues because our VPC didn't have ipv6 enabled. 
- It's worth raising that it might be necessary to configure ipv6 for your VPC if not enabled by default. Either if we want to make it a specific to Supabase or in general.
- This [article](https://cloud.google.com/vpc/docs/subnets?_gl=1*4z9j5i*_ga*MzcwMDUwMDk0LjE3Mjg0MjMzMzU.*_ga_WH2QY8WWF5*MTczMDMzMjA2MC40Mi4xLjE3MzAzMzM4ODQuNTUuMC4w#ipv6-ranges) suggest that ipv6 support is only available in certain Premium Network Tier for GCP.

2024-10-31 12:16 UTC, thruflo commented on website/docs/guides/deployment.md
> +  <a href="/img/deployment/components.jpg">
Very good points 🙏

2024-11-01 15:26 UTC, KyleAMathews approved these changes
:shipit:

2024-11-04 19:39 UTC, samwillis approved these changes
This is all amazing, just a couple of comments. Great work!

2024-11-04 19:39 UTC, samwillis commented on website/docs/guides/deployment.md
> +Make sure you're connecting directly to Postgres and not via a PGBouncer-style connection pool. This is because Electric uses logical replication and connection poolers don't usually support it.
We could add a note that pgbouncer now does support replication connections: https://www.pgbouncer.org/changelog.html#pgbouncer-123x

It looks like Neon is on that version: https://neon.tech/docs/connect/connection-pooling but in transaction, not session, mode. I couldn't on first glance work out if pgbounder only supports replication in session mode. I do know though that it mark the allocated connect as allusive to that connection when it's used for replication, and is closed and disposed of after the client disconnects. That should mean that it could work in transaction mode.

2024-11-04 19:39 UTC, samwillis commented on website/docs/integrations/aws.md
> +We have an example Terraform repo at [electric-sql/terraform-aws](https://github.com/electric-sql/terraform-aws).
This is for the old electric, do we want to link to it without it being updated?

2024-11-04 19:39 UTC, samwillis commented on website/docs/integrations/supabase.md
> +### Sync into Edge Function
I'd be tempted to do an auth proxy example using the edge function and supabase auth?

2024-11-04 19:39 UTC, samwillis commented on website/.vitepress/config.mts
> +          collapsed: true,
I think we should have this expended for discoverability, done be scared of long nav lists. We shouldn't hide all this awesome stuff!!

```suggestion
          collapsed: false,
```

2024-11-05 14:23 UTC, KyleAMathews commented
@thruflo it was easier to just push the changes directly as the merge needed cleaning up

2024-11-05 17:33 UTC, thruflo commented on website/docs/integrations/supabase.md
> +### Sync into Edge Function
Yup, good idea. Future PR.

2024-11-05 17:56 UTC, merged