Set a much longer max-age for -1 offsets and don't return
electric-sql/electric pull request #1857
Opened 2024-10-15 22:34 UTC by KyleAMathews

Fix for https://github.com/electric-sql/electric/issues/1838

2024-10-16 08:36 UTC, msfstef requested changes
I think at this point it warrants encapsulating the caching logic in a small module where we have better visibility and control over the various parameters, and also add a couple of tests on these

2024-10-16 08:36 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
why remove this? this is breaking a bunch of tests and I can't easily see why we would remove it?

2024-10-16 08:36 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +    if conn.query_params["offset"] == "#{@before_all_offset}" do
this would be better and more idiomatically handled with multiple pattern matched clauses on `put_resp_cache_headers`

I think since we want different cache times for different responses this might warrant a small but separate module that also has defined aliases for the cache ages we want to use

2024-10-16 08:36 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +          "public, max-age=#{config[:max_age]}, stale-while-revalidate=#{config[:stale_age]}"
we are currently configuring a max age and stale age, but the way this is evolving the configuration is only for non-initial, non-live requests

perhaps it would be better to encapsulate this business logic in its own module and also perhaps it would be good to parametrize all cache times on these configurations?

2024-10-16 09:43 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
You can't have a long cache for a shape segment which also includes an up-to-date message.

2024-10-16 09:43 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
See the discussion on the attached issue

2024-10-16 09:46 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +    if conn.query_params["offset"] == "#{@before_all_offset}" do
A refactor sounds like a good follow up issue but it's beyond my elixir capacity and I don't think it should block this change.

2024-10-16 09:49 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +          "public, max-age=#{config[:max_age]}, stale-while-revalidate=#{config[:stale_age]}"
The only reason there's config for Max age and SWR is for tests. These aren't values that people need to tweak. So not opposed to a refactor but that's a separate PR.

2024-10-16 10:15 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
Then it makes more sense to pass the completed response through a dedicated piece of caching logic and check if the response contains an up to date and set the cache time appropriately? If we chunk the initial data as well you would only ever get a -1 request with an up to date if the initial request is small enough

Removing this here will break a ton of things, and it's not removing the header that also marks if something is up to date either

2024-10-16 10:24 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
What does this break?

The idea here is this is a quick intermediate step on the way to a more comprehensive solution

See https://github.com/electric-sql/electric/issues/1838#issuecomment-2409013618 and https://github.com/electric-sql/electric/issues/1447

2024-10-16 10:54 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
You can look at the test suites failing on CI, but generally the API so far has been assumed to include an up-to-date message when you receive all the latest data so I suspect a ton of tests will rely on that.

Also to make this have the correct behaviour it's better to put this logic in `determine_up_to_date` in line 314 rather than in the serving logic, so the headers are also correctly updated

2024-10-16 11:46 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
> the API so far has been assumed to include an up-to-date message when you receive all the latest data so I suspect a ton of tests will rely on that.

Sure yeah I'll fix any other tests affected. Just to be clear though, the previous logic was wrong — when fetching an immutable log, there's two concerns we're balancing — 1) we want as much as the log to be cached both on end clients and on intermediate http caches and 2) we want end clients to have strong confidence they're up-to-date with the log. You can't really combine the two into one request.

If you put `up-to-date` in the initial request, then you have to have a short max-age as otherwise, clients will think they have the latest data when they don't. Also CDNs are currently dropping their cache as well constantly so too many requests are going back to the server.

So the solution is to do two requests. The first is heavily cached so mostly gets resolves either in the client itself or on the CDN so is consistently very fast — and the second is a cheap almost-no-data-returned request that gets quickly resolved by the CDN or end electric server.

In my testing, even larger 4-5 MB requests load from the cache in < 100ms and then the 2nd "am I up to date?" request returns also in < 100ms for < 200ms total. For the current logic, because of the short max-age, for many visits to an app, both the client and CDN cache have expired which means a 5-6s slow download from Electric.

2024-10-16 11:47 UTC, KyleAMathews commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> -        [snapshot, log, maybe_up_to_date]
> Also to make this have the correct behaviour it's better to put this logic in determine_up_to_date in line 314 rather than in the serving logic, so the headers are also correctly updated

Ah thanks, I'll try that.

2024-10-16 22:38 UTC, KyleAMathews commented
@msfstef ok something is goofy here that I can't figure out. The elixir tests were pretty easy to modify as they do raw http calls but the typescript client, especially the prefetching is having a thing. I'm seeing `getNextChunkUrl` get called twice and two fetches get called concurrently.

Can we grab some time tomorrow to figure this out?

2024-10-16 23:28 UTC, KyleAMathews commented
Perhaps the typescript client doesn't like an empty initial response? All my manual testing things worked great but that was always with shapes that had rows in it.

2024-10-17 11:10 UTC, msfstef approved these changes
I've updated the tests for the client, there were some issues as now you always have 2 initial requests to get to up to date and also the cache tests were failing as initial requests are no longer using the configured max age and stale age.

2024-10-17 11:10 UTC, msfstef commented on packages/sync-service/lib/electric/plug/serve_shape_plug.ex
> +    if offset == @before_all_offset do
I think that `put_resp_cache_headers` should be the last in the plug pipeline, and instead on relying on `offset` to decide this it should rely on whether `conn.assigns.up_to_date` is present, since semantically that is really what we want.

The "don't send up to date for offset -1" logic is in the "determine up to date" call, here we should be checking if it is up to date.

2024-10-17 12:15 UTC, robacourt approved these changes

2024-10-17 21:15 UTC, KyleAMathews commented
Thanks @msfstef !

2024-10-17 21:15 UTC, merged