docs: wip on Writing your own client guide.
electric-sql/electric pull request #1892
Opened 2024-10-25 17:45 UTC by thruflo

2024-11-04 18:56 UTC, samwillis approved these changes
This is really great!! I think it provides an even better overview of how sync works than the HTTP API docs page.

Python client is good, and provides such a simple overview of how to use the api. We could offer an asyncio version as that seems to be where Python has moved with all this stuff, and removes the need for the blocking `sync()` call and multiple processing. (If only gevent had been picked over asyncio...)

2024-11-04 18:56 UTC, samwillis commented on website/docs/guides/writing-your-own-client.md
> +++++++++[>++++++++++>++++++++++++++>+++++++++++++++>++++>+++++++>+++++<<<<<<-]>-.>--.--.>+.>.<<--.+++++.----.--.+++++.-------.>>.>+++.>+.
Love this

2024-11-04 18:56 UTC, samwillis commented on website/docs/guides/writing-your-own-client.md
> +            raise "Must provide a table"
```suggestion
            raise ValueError("Must provide a table")
```

2024-11-04 18:56 UTC, samwillis commented on website/docs/guides/writing-your-own-client.md
> +            self.cursor = r.headers['electric-cursor']
```suggestion
            self.cursor = response.headers['electric-cursor']
```

2024-11-04 18:56 UTC, samwillis commented on website/docs/guides/writing-your-own-client.md
> +```python
This is great!

We could also offer an implementation (as a tab on the code block?) using asyncio (untested, but think its mostly correct):

```sh
python -m pip install aiohttp
```

```python
import aiohttp
import asyncio
from urllib.parse import urlencode

class Shape:
    """Async syncs a shape log and materializes it into a `data` dict."""

    def __init__(self, base_url='http://localhost:3000', offset=-1, handle=None, table=None, where=None):
        if table is None:
            raise ValueError("Must provide a table")

        # Request state used to build the URL.
        self.base_url = base_url
        self.cursor = None
        self.handle = handle
        self.live = False
        self.offset = offset
        self.table = table
        self.where = where

        # Materialiased data.
        self.data = {}

        # Accumulated messages (waiting for an `up-to-date` to apply).
        self.messages = []

        # Registered callbacks to notify when the data changes.
        self.subscribers = []

        # Task management for async syncing.
        self._sync_task = None  # Background task for the sync loop.
        self._stop_event = asyncio.Event()  # Event used to stop the sync loop.

    def subscribe(self, callback):
        """Register a callback function to be called whenever data changes."""
        
        self.subscribers.append(callback)

    async def start_sync(self):
        """Begin syncing in the background, without blocking."""
        # Only start if no existing sync task is running.
        if self._sync_task is None or self._sync_task.done():
            # Clear the stop event and create a new sync task.
            self._stop_event.clear()
            self._sync_task = asyncio.create_task(self._run_sync())

    async def stop_sync(self):
        """Stop the background sync task gracefully."""
        if self._sync_task and not self._sync_task.done():
            # Set the stop event to signal the sync task to exit.
            self._stop_event.set()
            await self._sync_task  # Wait for the task to complete.

    async def _run_sync(self):
        """Internal method to run the sync loop until a stop signal is received."""
        while not self._stop_event.is_set():  # Continue until stop is requested.
            await self.request()  # Perform a sync request.
            await asyncio.sleep(1)  # Add delay to avoid rapid polling.

    async def request(self):
        """Make an asynchronous request to `GET /v1/shape` and process the response."""
        
        # Build the request URL with current parameters.
        url = self.build_url()

        async with aiohttp.ClientSession() as session:

            # Fetch the response.
            async with session.get(url) as response:

                # This is a happy path example, so we just log error codes.
                # A real client should handle errors, backoff, reconnect, etc.
                if response.status > 204:
                    raise Exception(f"Error: {response.status}")

                # If the response is 200 then we may have new data to process.
                if response.status == 200:
                    self.messages.append(await response.json())  # Queue the new data.

                    # If we're up-to-date, switch into live mode and process
                    # the accumulated messages.
                    if 'electric-up-to-date' in response.headers:
                        self.live = True
                        await self.process_messages()

                # Set the shape handle, offset and optionally cursor for
                # the next request from the response headers.
                self.handle = response.headers.get('electric-handle')
                self.offset = response.headers.get('electric-offset')

                if 'electric-cursor' in response.headers:
                    self.cursor = response.headers['electric-cursor']

    # Snip... the rest is the same
```

2024-11-04 18:56 UTC, samwillis commented on website/docs/guides/writing-your-own-client.md
> +import unittest
A asyncio version (untested):

```py
import asyncio
import unittest

from client import Shape

class TestClient(unittest.IsolatedAsyncioTestCase):
    async def test_shape_sync(self):
        shape = Shape(table='items')
        data_received = []
        event = asyncio.Event()

        def callback(data):
            data_received.append(data)
            event.set()

        shape.subscribe(callback)
        await shape.start_sync()
        await asyncio.wait_for(event.wait(), timeout=5)
        self.assertEqual(type(data_received[0]), dict)
        await shape.stop_sync()

if __name__ == '__main__':
    unittest.main()
```

2024-11-04 19:29 UTC, thruflo commented on website/docs/guides/writing-your-own-client.md
> +```python
You and your fancy modern code ;)

I do think it's best to keep async/thread/process stuff out of the client. It just makes it much less readable and for me this is more intended to be read than run.

Perhaps we can use this as the basis for an actual Python client?

2024-11-04 19:37 UTC, thruflo commented on website/docs/guides/writing-your-own-client.md
> +import unittest
Will this work with the non asyncio client? I've tried it locally and for me it just runs and hangs forever, so I suspect not?

2024-11-04 19:40 UTC, samwillis commented on website/docs/guides/writing-your-own-client.md
> +```python
Yep, good call!

We probably ~~want~~ need to have both versions of the client.

2024-11-04 19:42 UTC, samwillis commented on website/docs/guides/writing-your-own-client.md
> +import unittest
Yep, this relies on the asyinio loop, I believe `unittest.IsolatedAsyncioTestCase` will start it.

Let's leave it out and use this in the actual client.

2024-11-05 13:18 UTC, KyleAMathews requested changes
Great stuff! This will be super helpful for all the engineers wanting to know how what's going on under the hood plus of course those wanting to build a new client in some other language.

2024-11-05 13:18 UTC, KyleAMathews commented on website/docs/guides/writing-your-own-client.md
> +If the previous response contains an `electric-cursor` header, then also set the `cursor` parameter to its value. (This is an extra cache-busting parameter used to normalise [request-coalescing](/doc
I've only seen the term "request collapsing" btw

2024-11-05 13:18 UTC, KyleAMathews commented on website/docs/guides/writing-your-own-client.md
> +### Brainfuck
hmm this is a bit esoteric / off-beat of a joke? I looked it up and it's "hello world"...? I'd guess this will confuse more people than it'll amuse so I'd take it out.

2024-11-05 13:48 UTC, thruflo commented on website/docs/guides/writing-your-own-client.md
> +If the previous response contains an `electric-cursor` header, then also set the `cursor` parameter to its value. (This is an extra cache-busting parameter used to normalise [request-coalescing](/doc
Ok, I'll standardise on that.

2024-11-05 13:51 UTC, thruflo commented on website/docs/guides/writing-your-own-client.md
> +### Brainfuck
I think the upsides of the humour outweigh the downside of potential confusion. This is at the bottom of the writing your own client guide. Not a location likely to be reached by the faint of heart.

2024-11-05 18:24 UTC, KyleAMathews approved these changes
:shipit:

2024-11-05 18:25 UTC, merged