feature(examples): Linear app with pnpm and ts cli
electric-sql/electric pull request #194
Opened 2023-06-21 14:55 UTC by paulharter

2023-06-26 08:32 UTC, kevin-dp requested changes
Looks good, awesome work!
Most comments are minor things to change or leftover commented code to remove.

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Home/index.tsx
> +import LeftMenu from '../../components/LeftMenu';
Could you run prettier such that the formatting is consistent with the formatting we internally use :-)

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Home/IssueList.tsx
> +  // TODO
Does this still apply?

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Home/IssueList.tsx
> +// import { AppDispatch, RootState } from 'store';
There is a bit of commented code in this file, please remove it if it's not needed.

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Home/IssueList.tsx
> +    const issues = results !== undefined ? [...results] : []
`[...results]` is the same as just `results` here.
Also, to make it more idiomatic you can do:
`const issues = results ?? []`

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Home/IssueList.tsx
> +    const { results } = useLiveQuery(db.issue.liveMany({}))
Perhaps leave a comment explaining what this query does: `// fetches all issues`
Also note that you can omit to argument if it's just the empty object, so `db.issue.liveMany()`

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Home/IssueList.tsx
> +    const { results } = useLiveQuery(db.issue.liveMany({}))
Just double checked, the argument is optional for `findMany` but not for `liveMany`. Will fix that later :-)

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/electric.tsx
> +  return electrify(conn, dbSchema, config)
Electrify is an async function, should be awaited here.

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/electric.tsx
> +  console.log("initElectric");
These log statements seem to be for debugging purposes. Should be removed before merging

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Home/IssueRow.tsx
> +        {/*<div className="flex-shrink-0 hidden w-10 ml-2 mr-3 font-normal sm:block">*/}
These divs seem to be commented out, do they have a purpose?

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/types/issue.ts
> +// export type User = {
Remove if not used

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/utils/notification.tsx
> +  //TODO: make notification showing from bottom
If this still applies you could make a Linear issue in order not to forget and remove it from here. There is a similar todo on line 30.

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/pages/Board/IssueBoard.tsx
> +// import { AppDispatch, RootState } from 'store';
Remove unused imports

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/TopFilter.tsx
> +  // TODO
Create a linear issues if this todo still applies and remove it from here

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/TopFilter.tsx
> +//import { RootState } from 'store';
Remove unused import

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/StatusIcon.tsx
> +  // console.log("***********", status);
Remove obsolete comments

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/SearchBox.stories.tsx
> +//import { Meta } from '@storybook/react';
Remove comment import above and export below

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/IssueModal.tsx
> +// import { AppDispatch } from 'store';
Remove commented imports

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/IssueModal.tsx
> +    // TODO
Create linear issue if still needed, remove it from here.

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/IssueModal.tsx
> +  // const dispatch = useDispatch<AppDispatch>();
Remove this obsolete line of code.

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/IssueFilterModal.tsx
> +// import { setTimeout } from 'timers';
Remove

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/src/components/contextmenu/LabelMenu.tsx
> +      (l) => l.name.toLowerCase().indexOf(normalizedKeyword) !== -1
could replace `indexOf` by `includes`: `l.name.toLowerCase().includes(normalizedKeyword)`

2023-06-26 08:32 UTC, kevin-dp commented on examples/linearlite/client/package.json
> +    "better-sqlite3": "^8.4.0",
Does this app really need `better-sqlite3` ? It's using wa-sqlite.

2023-06-26 08:32 UTC, kevin-dp commented on pnpm-workspace.yaml
> +  - 'examples/linearlite/*'
We could also go for the more general `examples/**`. Not sure what's best.

2023-06-26 15:07 UTC, paulharter commented on examples/linearlite/README.md
> +source .envrc
Or should we build a new up to date electric for all the new examples?

2023-06-26 15:08 UTC, paulharter commented on examples/linearlite/README.md
> +This is an example of an team collaboration app such as [linear](https://linear.app) built using electric-sql.
thanks for catching my typos

2023-06-26 15:09 UTC, paulharter commented on examples/linearlite/README.md
> +There are a set of Postgres migrations in `db/prisma/migrations`.
hmm yes - its sort of a set of one! I'll change this

2023-06-26 15:13 UTC, paulharter commented on examples/linearlite/client/package.json
> +    "better-sqlite3": "^8.4.0",
a left over I forgot to remove

2023-06-27 07:03 UTC, kevin-dp commented on examples/linearlite/README.md
> +source .envrc
Users will still need to change the version of Electric in `.envrc` to that version because currently we want the `.envrc` that comes with main to work with the old documented examples. Hence, that would only remove the build step. I would explain in the readme how to build Electric and how to change `.envrc` to use that one. As such, users trying it out are always using the latest Electric.

2023-06-27 07:12 UTC, kevin-dp commented on examples/linearlite/README.md
> +cd db
When following the command in the readme, `cd db` won't work because the last command i executed on line 56 was `cd ../..` which brought me to the root folder of the app. So i would change the command on line 56 to: `cd ../../examples/linearlite`

2023-06-27 07:15 UTC, kevin-dp commented on examples/linearlite/README.md
> +cd client
By following the command i'm still in `db`, so i would change this to `cd ../client`

2023-06-27 07:19 UTC, kevin-dp commented
I ran the app (against the local build of Electric i had) using the instructions in the readme and it worked without problems. Note that when i clicked "create issue" there were some warnings being raised in the console:

> Warning: Each child in a list should have a unique "key" prop.

2023-06-27 07:19 UTC, kevin-dp approved these changes

2023-06-27 09:47 UTC, icehaunter commented
Let's hold off merging this until we merge PG-centrality to make sure it all works still?

2023-06-29 13:23 UTC, icehaunter commented
Pg centrality landed, please rebase :)

2023-07-03 07:38 UTC, icehaunter requested changes
PG centrality is now in `main`, I think we should rebase this and check that everything still works

2023-07-05 13:12 UTC, paulharter commented
replaced by newer PR

2023-07-05 13:12 UTC, closed without merging