chore (ts-client): validate required Electric headers on response
electric-sql/electric pull request #1957
Opened 2024-11-07 11:11 UTC by kevin-dp

Fixes https://github.com/electric-sql/electric/issues/1950

Questions:
- Are the headers only required on 2XX responses or also on other responses?
   They are currently only being checked on 2XX responses.
- Are we checking *all* required headers?
   Currently we check `electric-offset`, `electric-handle`, and `electric-schema`

2024-11-07 11:18 UTC, msfstef approved these changes
Looks good, I like the reuse of the fetch wrapper pattern!

I think possibly only 409 responses would also require an `electric-handle` to ensure it is possible to switch to the "right" shape, but I think doing just 200s is good enough to solve the issue of potentially misconfigured proxies

2024-11-07 11:29 UTC, thruflo commented
Can we also validate an `electric-cursor` header when we receive a `204` in response to a live request?

Not having the cursor param can result in re-requesting to the same URL.

2024-11-07 11:33 UTC, thruflo commented
Plus can we please write a section in the https://electric-sql.com/docs/guides/troubleshooting guide about this and include a link to it in the error message?

Basically we would want to explain that if headers are missing then your proxy needs to make sure it includes them, maybe with a code sample showing how (Kyle has some proxy code that clones the headers).

I can write this if you'd like.

2024-11-07 13:40 UTC, KyleAMathews requested changes
What did y'all think also about the idea of also tracking which URLs we request and check that we don't request the same URL twice (within a given session)? 

This would catch any other issue we haven't thought of.

The only tricky thing here I can think of is we'd need to wipe the Set on shape rotation.

2024-11-07 13:40 UTC, KyleAMathews commented on packages/typescript-client/src/error.ts
> +    msg += `\nThis is often due to a proxy not allowing all headers to be returned.`
```suggestion
    msg += `\nThis is often due to a proxy not setting CORS correctly so that all Electric headers can be read by the client.`
```

2024-11-07 13:40 UTC, KyleAMathews commented on packages/typescript-client/src/fetch.ts
> +  `electric-schema`,
`electric-cursor` & `electric-up-to-date` are also required.

2024-11-07 13:41 UTC, KyleAMathews commented
Checking just 200s for headers seems fine as it covers all the headers.

2024-11-07 14:20 UTC, kevin-dp commented on packages/typescript-client/src/fetch.ts
> +  `electric-schema`,
Our API spec says that the cursor is optional on the response, is that wrong?

2024-11-07 14:43 UTC, thruflo commented on packages/typescript-client/src/fetch.ts
> +  `electric-schema`,
As [above](https://github.com/electric-sql/electric/pull/1957#issuecomment-2461998099) I believe we only return a cursor when returning a 204 to a live request.

2024-11-07 14:44 UTC, msfstef commented on packages/typescript-client/src/fetch.ts
> +  `electric-schema`,
We actually include `electric-cursor` for all live requests, 200 or 204

2024-11-07 19:20 UTC, KyleAMathews commented on packages/typescript-client/src/fetch.ts
> +  `electric-schema`,
Yeah ok it's a bit more tricky to check for these but it's still really bad if they're not available so it it's hard to check that'd be good. But with docs on what headers CORS allows through, probably just checking the minimal always sent set is enough

2024-11-07 19:20 UTC, KyleAMathews commented on packages/typescript-client/src/fetch.ts
> +  `electric-schema`,
The point is the dev would see an error while developing and fix things.

2024-11-12 09:31 UTC, kevin-dp commented on packages/typescript-client/src/fetch.ts
> +  `electric-schema`,
So, the docs are correct and `electric-cursor` is optional as it is only provided in live mode. I could modify the check such that it checks if the original URL contains the `live` query param and only then check for the presence of `electric-cursor`.

@KyleAMathews Regarding `electric-up-to-date`, it is only present on the last chunk we will get from the sync service, so we don't want to check this on every message?

2024-11-14 11:40 UTC, kevin-dp commented
@KyleAMathews Can you have another review at this PR to see if you approve the changes?
There are some required headers that are checked on all 2xx responses. There are also some headers that are required only in live mode and some only in non-live mode. I also check those on 2xx responses.

I will open a separate docs PR before merging this one.

2024-11-14 15:21 UTC, KyleAMathews approved these changes
:shipit: thanks!

2024-11-19 10:27 UTC, kevin-dp commented
For reference, this is the accompanying docs PR: https://github.com/electric-sql/electric/pull/1976

2024-11-19 10:28 UTC, merged