feat(satellite) add support for shape subscriptions on satellite client
electric-sql/electric pull request #196
Opened 2023-06-22 10:16 UTC by balegas

2023-06-29 11:25 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +  async _garbageCollectShapeHandler(shapeDef: ShapeDefinition): Promise<void> {
Need to pass an array and defer foreign key check, otherwise will be hell to drop a table

2023-06-29 11:40 UTC, kevin-dp requested changes
Overall a great PR, most code is very readable :-)
I left some comments none of which are major. 
All minor refactorings, improvements, commenting issues.

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/subscriptions.ts
> +        if (!this.subToShapes[subscriptionId]) {
this if test can be simplified: `this.subToShapes[subscriptionId] = this.subToShapes[subscriptionId] ?? []`

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/subscriptions.ts
> +export class SubscriptionsDataCache extends EventEmitter {
Let's move this to its own file in a new `shapes` folder :)

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/subscriptions.ts
> +// server sends tags, but no timestamp. Is this correct?
seem to be notes while implementing. Don't forget to remove before merging

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/subscriptions.ts
> +    if (this.remainingShapes.size == 0) {
This if test is duplicated on several places (e.g. in `subscriptionRequest`).
Could refactor it to a function that takes the error message as argument.

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/subscriptions.ts
> +    this.inDelivery = undefined
Don't we also need to reset `currentShapeRequestId` ?
If yes, we can call `this.reset()`

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/subscriptions.ts
> +    this.inDelivery = undefined
Oh i see now, this will already have been done by `shapeDataEnd`. Still, may be easier to call `reset` here, don't think we care about 1 extra assignment.

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/subscriptions.ts
> +      this.reset()
no need to call `reset` because that's the first thing `subscriptionError` does.
Same comment applies on line 184

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/types.ts
> +export type SubscribeResponse = {
I would move all shape-related types to a separate `types.ts` file in `shapes` folder

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/src/util/types.ts
> +  shapeReqToUuid: { [req: string]: string }
`Record<string, string>`

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/test/satellite/process.test.ts
> +test('apply shape data and persist subscription', async (t) => {
I'm wondering if we should make these tests serial because they are actually modifying a shared SQLite DB. And if these tests run in parallel this may perhaps cause issues.

2023-06-29 11:40 UTC, kevin-dp commented on clients/typescript/test/satellite/server_ws_stub.ts
> +            if (msgType == getTypeFromString(SatSubsResp.$type)) {
I know that you copied how it is done above, but this is way too much code duplication for my likings. Essentially every if test is doing the same, only the type cast is different and the type. This could be refactored:
- an array containing all message types
- loop over the array and for each message type do the if test

2023-06-29 12:55 UTC, icehaunter commented on clients/typescript/src/satellite/index.ts
> +  ): Promise<void | SatelliteError>
That's not it. @balegas, this is unfortunately just wrong, and it's wrong everywhere in the client: you're assuming that the `raise` you're actually doing in `unsubscribe` (e.g. in the implementation in `process.ts`) will be somehow reflected in the type. Extremely unfortunately, it won't - so including the `SatelliteError` in return signature anywhere is wrong. The `raise`-ed error can never end up in `.then()` handler or show up as a result of `await ...` - it'll get propagated to `.catch` (untyped) or reraised to be caught in `try ... catch (e: unknown)` (also untyped). We're not returning errors, we're (correctly) `raise`-ing them, but TypeScript has no ways to define that behaviour (no `throws` from Java) (explanation as to why this is the case can be found [here](https://github.com/microsoft/TypeScript/issues/13219#issuecomment-1515037604)). Plese remove them from signatures here, and @kevin-dp, we can remove them anywhere we encounter

2023-06-29 13:38 UTC, kevin-dp approved these changes
@icehaunter Looks good. Left two minor comments.

2023-06-29 13:38 UTC, kevin-dp commented on clients/typescript/src/satellite/client.ts
> +  private sendMessage<T extends SatPbMsg>(request: T) {
Isn't this equivalent in this case? Adding a generic with a subtyping constraint is useful if you don't want to lose type information for instance if the return type would be the same T as the one passed in. But in this case i don't see an added benefit of doing this.

2023-06-29 13:38 UTC, kevin-dp commented on clients/typescript/src/util/proto.ts
> +  return msgtypemapping[string_type]?.[0] ?? undefined
`?? undefined` seems very weird, unless its purpose is to turn `null` into `undefined`?
If so, add a comment documenting this. Otherwise, just return `msgtypemapping[string_type]?.[0]`

2023-06-29 14:09 UTC, icehaunter requested changes
I agree with @kevin-dp's comments, and just a small ones of mine

2023-06-29 14:09 UTC, icehaunter commented on clients/typescript/src/util/subscriptions.ts
> +  subscribeToUnsubscribeEvent(callback: GarbageCollectShapeHandler) {
Please specify return types on all non-private functions. And it would be nice to also have them specified on private. Having explicit return types makes it safer for us to update implementation detail - we have a clear contract with the world outside of the function and can adhere to it. If the return type is inferred, then any internal changes may alter the return type, unintentionally type-breaking the place of call instead of place of change

2023-06-29 14:12 UTC, balegas commented on clients/typescript/src/migrators/schema.ts
> +        `INSERT INTO ${metaTable} (key, value) VALUES ('compensations', 0), ('lastAckdRowId','0'), ('lastSentRowId', '0'), ('lsn', ''), ('clientId', ''), ('subscriptions', '');`,
Let me share the rationale behind the decision I made on this subject:
- It is very easy to manipulate the in-memory data-structure, but would lot more work to manipulate each individual subscription directly on the database.
- Therefore, database is just there to provide persistence
- We subscribe concurrently without hitting the storage. Subscription state is stored only when we apply the subscription, which happens serially. 
- The size of the object is relatively small so that we don't care about the cost comp/io (and it is client-side)

Also note that subscriptions will be an occasional operation, so I would not try to optimise so much for concurrency over simplicity. I think doing it from the database only makes sense if we have more complex flows.

2023-06-29 14:12 UTC, balegas commented on clients/typescript/src/satellite/client.ts
>  } from '../_generated/protocol/satellite'
Will look to it

2023-06-29 14:16 UTC, balegas commented on clients/typescript/src/satellite/index.ts
> +  ): Promise<void | SatelliteError>
I will fix that. I think was me that introduced the bad pattern early and everyone copied it (including me), even knowing that it doesn't make sense :D

2023-06-29 14:19 UTC, icehaunter commented on clients/typescript/test/satellite/process.test.ts
> +              t.fail()
First, you can just `return` the promise you're building for a clearer intention instead of building and then awaitng it. 
Second, you can `reject(e)` here from the promise so that Jest reports a proper reason why this failed instead of a generic "failed" state

2023-06-29 14:22 UTC, icehaunter commented on clients/typescript/src/util/proto.ts
> +  // FIXME
I addressed this in a later commit

2023-06-29 14:29 UTC, balegas commented on clients/typescript/src/satellite/mock.ts
> +  setRelations(relations: RelationsCache) {
Note that is for the mock, so not much problem with what is public.
I need this to set the relations ahead of streaming operations for a subscription, otherwise tests would also need to handle migrations etc... in fact, maybe I need to do that too.

@icehaunter this was something I wanted to raise during the call. I don't know how migrations and consequently relations are delivered if needed for subscriptions. I assume that the necessary messages will be delivered before.

2023-06-29 14:29 UTC, balegas commented on clients/typescript/src/satellite/mock.ts
> +  setRelations(relations: RelationsCache) {
- [ ] test missing relation path

2023-06-29 14:30 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +        if (error.code && throwErrors.find((te) => te == error.code)) {
always learning

2023-06-29 15:11 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +    this.subscriptions.subscribeToUnsubscribeEvent(
Fair point

2023-06-29 15:12 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +  async _applySubscriptionData(changes: DataChange[]) {
Will leave relevant info on comment

2023-06-29 15:18 UTC, balegas commented
Thanks a lot for all the comments. I will handle them with pleasure.

2023-06-29 15:53 UTC, balegas commented on clients/typescript/src/satellite/client.ts
>  } from '../_generated/protocol/satellite'
Need to touch all occcurence because it's ```import * as ``

2023-06-29 22:50 UTC, balegas commented on clients/typescript/src/satellite/mock.ts
> +  relations: RelationsCache
There was some strange reordering here. Fixed it now.

2023-06-29 22:50 UTC, balegas commented on clients/typescript/src/util/subscriptions.ts
> +  shapeReqToUuid: { [req: string]: string }
There are a few of these

2023-06-29 22:50 UTC, balegas commented on clients/typescript/src/util/subscriptions.ts
> +  subscribeToUnsubscribeEvent(callback: GarbageCollectShapeHandler) {
In general, I might have not paid attention to this, but the interface defines the return types. Agree that for convetion we might just specify the return types in the implementation anyways, for public and private.

2023-06-29 22:50 UTC, balegas commented on clients/typescript/src/util/subscriptions.ts
> +    this.inDelivery = undefined
Just calling reset instead :)

2023-06-29 22:50 UTC, balegas commented on clients/typescript/src/util/subscriptions.ts
> +    if (this.remainingShapes.size == 0) {
I prefer the monotony of the if statements if I cannot generize the pattern.

2023-06-29 22:50 UTC, balegas commented on clients/typescript/src/util/types.ts
> +  shapeReqToUuid: { [req: string]: string }
We (wrongly) overlaod the type Record in this file

2023-06-30 10:44 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +      this._applySubscriptionData(subsData.data.changes)
This function is going to be called through the event emitter, which doesn't await on completion. So, it doesn't matter if we await or not. However, given that this function could eventually be used elsewhere (but unexpectedly), it should still be async.  

Regarding the use of await in the return statement: the pattern I typically use is to return the result instead of awaiting and returng.
- I think it doesn't make a big difference because if the caller doesn't await, awaiting in the function has no effect either. I'd like to hear your toughts to understand better what should we adopt as a pattern.

2023-07-01 00:10 UTC, balegas reviewed
Addressed all suggestions, closed those that I think require no second review or action

2023-07-03 15:21 UTC, kevin-dp commented on clients/typescript/src/util/types.ts
> +  shapeReqToUuid: { [req: string]: string }
I see.. We could let the IDE refactor our own `Record` type to a slightly different name to solve this. I can also live with leaving it like this for now

2023-07-03 15:23 UTC, kevin-dp commented on clients/typescript/test/satellite/process.test.ts
> +test('apply shape data and persist subscription', async (t) => {
Yep overlooked that! Ignore this comment :)

2023-07-03 15:26 UTC, kevin-dp commented on clients/typescript/src/migrators/schema.ts
> +        `INSERT INTO ${metaTable} (key, value) VALUES ('compensations', 0), ('lastAckdRowId','0'), ('lastSentRowId', '0'), ('lsn', ''), ('clientId', ''), ('subscriptions', '');`,
I thought it would be simpler to have 1 row per subscription (e.g. adding a subscription is adding a row vs reading, modifying the structure, writing it back) but i trust you when you say that actually the inverse is simpler.

2023-07-03 15:31 UTC, balegas commented on clients/typescript/src/migrators/schema.ts
> +        `INSERT INTO ${metaTable} (key, value) VALUES ('compensations', 0), ('lastAckdRowId','0'), ('lastSentRowId', '0'), ('lsn', ''), ('clientId', ''), ('subscriptions', '');`,
It felt easier to me to reconstruct the in-memory state of the subscription manager by serialising/deserializng the entire thing, instead of reading/writting multiple columns and reconstructing it back from the query result.

To clarify we manage the in-flight subscriptions in-memory. If there is a crash, we don't recover in-flight subscriptions. We only persist the subscriptions object when a subscription is delivered.

2023-07-03 15:32 UTC, kevin-dp commented on clients/typescript/src/migrators/schema.ts
> +        `INSERT INTO ${metaTable} (key, value) VALUES ('compensations', 0), ('lastAckdRowId','0'), ('lastSentRowId', '0'), ('lsn', ''), ('clientId', ''), ('subscriptions', '');`,
Yeah this will probably be even more true in the future when those structures are more complex. Thanks for clarifying!

2023-07-04 08:36 UTC, icehaunter approved these changes

2023-07-04 11:03 UTC, merged