BETA release post.
electric-sql/electric pull request #2108
Opened 2024-12-06 12:50 UTC by thruflo

2024-12-06 14:09 UTC, KyleAMathews requested changes
Love it! Very simple and strong intro.

I made some small copy suggestions but nothing major.

2024-12-09 17:48 UTC, KyleAMathews reviewed
Some more tweaks

2024-12-09 17:48 UTC, KyleAMathews commented on website/blog/posts/2024-12-09-electric-beta-release.md
> +  With version 1.0.0-beta, the Electric sync engine is now in BETA!
```suggestion
  With version 1.0.0-beta.0, the Electric sync engine is now in BETA!
```

2024-12-09 17:48 UTC, KyleAMathews commented on website/blog/posts/2024-12-09-electric-beta-release.md
> +With version [`1.0.0-beta`](https://github.com/electric-sql/electric/blob/main/packages/sync-service/CHANGELOG.md) the Electric sync engine is now in BETA!
```suggestion
With version [`1.0.0-beta.0`](https://github.com/electric-sql/electric/blob/main/packages/sync-service/CHANGELOG.md) the Electric sync engine is now in BETA!
```

2024-12-09 17:48 UTC, KyleAMathews commented on website/blog/posts/2024-12-09-electric-beta-release.md
> +    Screenshot of Linearlite. Click on it to
```suggestion
    Screenshot of Linearlite.
```

2024-12-09 17:48 UTC, KyleAMathews commented on website/blog/posts/2024-12-09-electric-beta-release.md
> +### Signup for cloud
```suggestion
### Signup for early access to Electric Cloud
```

2024-12-09 17:48 UTC, KyleAMathews commented on website/blog/posts/2024-12-09-electric-beta-release.md
> +We're also working hard building our [Cloud product](/product/cloud), which provides managed Electric hosting so you don't need to [host Electric yourself](/docs/guides/deployment).
```suggestion
We're also building a [Electric Cloud](/product/cloud), which provides managed Electric hosting.
```

2024-12-09 17:48 UTC, KyleAMathews commented on website/blog/posts/2024-12-09-electric-beta-release.md
> +If you're interested in using Electric Cloud, you can sign up for early access now:
```suggestion
We'll be opening access soon in a private beta so if interested, you can sign up for early access now:
```

2024-12-10 13:48 UTC, KyleAMathews approved these changes
:shipit:

2024-12-10 13:54 UTC, thruflo commented
⚠️ 🔌

2024-12-10 16:34 UTC, thruflo commented on website/docs/reference/benchmarks.md
> +These statistics were generated using our [client load benchmarking](https://github.com/electric-sql/client-load-benchmarking) suite that allows for measuring client latencies for any combination of
Maybe `client latencies and sync service resource use`?

2024-12-10 20:21 UTC, merged