Write patterns deployment
electric-sql/electric pull request #2129
Opened 2024-12-09 16:48 UTC by balegas

Deployment and dockers files for hosting Write patterns example.

I did some changes to load env vars and add db ids, etc.

There seems to be some problem with pattern 4, but I'm not sure if is just me.

2024-12-09 16:48 UTC, balegas commented
This should generally be working, but I wasn't able to test it. Opening PR for visibility and for someone to take over if necessary.

2024-12-09 17:23 UTC, KyleAMathews requested changes

2024-12-09 17:23 UTC, KyleAMathews commented on examples/write-patterns/sst.config.ts
> +      const cluster = new sst.aws.Cluster(
let's reuse the our dev cluster from cloud

2024-12-09 17:26 UTC, balegas commented on examples/write-patterns/sst.config.ts
> +      const cluster = new sst.aws.Cluster(
Alright. Well have to do that though all examples

2024-12-09 17:27 UTC, KyleAMathews commented on examples/write-patterns/sst.config.ts
> +      const cluster = new sst.aws.Cluster(
that'd be good — they're slow to setup & fairly expensive

2024-12-09 19:11 UTC, thruflo commented on examples/write-patterns/patterns/1-online-writes/index.tsx
> +      database_id: import.meta.env.VITE_ELECTRIC_DATABASE_ID,
The challenge here is that this complicates the example code just for our deployment purposes.

One request is please can you follow the pattern of declaring a `const `DATABASE_URL ...` next to `ELECTRIC_URL` above and providing a default value there. It keeps the actual shape definition cleaner.

2024-12-10 00:41 UTC, balegas commented on examples/write-patterns/patterns/1-online-writes/index.tsx
> +      database_id: import.meta.env.VITE_ELECTRIC_DATABASE_ID,
I moved the params to the top but is not great. I suggest you change it to your taste.

In general is a bit of a pain that we need to set Cloud params explicitly. One possible way to hide is to pass Cloud in the base url, but I'm not sure if the code picks it up properly

2024-12-10 08:56 UTC, thruflo requested changes

2024-12-10 08:56 UTC, thruflo commented on examples/write-patterns/patterns/1-online-writes/index.tsx
> +const ELECTRIC_URL =
Maybe we could wrap this up into:

```ts
const { electricUrl, envParams } from '../../shared/app/config'
```

2024-12-10 08:56 UTC, thruflo commented on examples/write-patterns/patterns/1-online-writes/index.tsx
> +const ELECTRIC_URL =
I.e.: across all the patterns, given that it's a bunch of noise at the top of the code samples that are all displayed on the page in the Writes guide, etc.

2024-12-10 19:45 UTC, KyleAMathews approved these changes
:shipit:

2024-12-10 19:46 UTC, merged