feat(electric)!: Revamp Electric's auth implementation
electric-sql/electric pull request #216
Opened 2023-06-28 14:39 UTC by alco

Joken provides a richer set of features of which declarative claim validation and support for easily configurable asymmetric signing algorithms are the main highlights.

It's also more actively maintained and orders of magnitude more popular, judging by the download stats on hex.pm.

There's no need for any authentication-related configuration to happen at compile time. We'll be moving it to runtime config which will allow us to

  1. Validate user-provided config at application start.

  2. Convert the user-provided config into a clean map that is then easier to work with in the modules that implement auth.

The `metadata` field can be used to add any keys to Logger calls without also white-listing them in the Logger configuration (which is easy to forget).

Fixes VAX-663, VAX-665, VAX-666

BREAKING CHANGE: Old-style insecure authentication will no longer work with these server changes. Old-style JWT tokens produced by Electric Console are also not compatible with these changes.

2023-06-28 17:07 UTC, icehaunter commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
Please add all available environment variables to README

2023-06-28 20:58 UTC, alco commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
I didn't think it was necessary to mention optional configuration parameters in README. They're all going to be documented in our new docs ([preview](https://deploy-preview-4--wip-electric-sql-docs.netlify.app/docs/usage/auth/jwt#configuration-settings)).

2023-06-29 09:42 UTC, icehaunter commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
Sure, but we're an open-source project. I find it very very useful when all possible configuration params are mentioned in README, and details are in proper docs

2023-06-29 09:45 UTC, icehaunter commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
Also your docs link mentions some-but-not-all configuration params, and I really like a full reference when I'm setting up a service to be ran. I also would love for this readme to show up on DockerHub, where it's also going to be very useful to have all configuration options immediately listed

2023-06-29 10:00 UTC, icehaunter requested changes

2023-06-29 10:56 UTC, alco commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
Some open-source projects choose to use GitHub exclusively for documentation and for those projects it makes sense to have the full API or configuration reference in the README file.

But we have the bulk of our docs published on a dedicated website and, from what I've seen, API reference for the various components of our system will be part of that. In this context, duplicating reference docs in the README and on the docs website is just asking for trouble. At some point one will remember to update them in one place but forget to do it in the other one.

My opinion is that our READMEs should be slimmed down in the lead up to the public v2.0 release as we're making the docs website more comprehensive, not the other way around.

2023-06-29 10:58 UTC, alco commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
Regarding your last comment, I don't which configuration options are missing from the docs preview. These are all the options that are relevant to auth and they're all mentioned on the docs website:
 * SATELLITE_AUTH_MODE
 * SATELLITE_AUTH_JWT_ALG
 * SATELLITE_AUTH_JWT_KEY
 * SATELLITE_AUTH_JWT_NAMESPACE
 * SATELLITE_AUTH_JWT_ISS
 * SATELLITE_AUTH_JWT_AUD

2023-06-29 11:15 UTC, alco commented on components/electric/test/electric/satellite/auth/jwt_test.exs
> +    end
I wouldn't be so sure about Joken's test suite, it only tests a few things related to the implementation of its `Joken.Signer` struct. You can say that it's `jose`'s responsibility to test this because that's the underlying library that Joken wraps but then there won't be any tests verifying the full end-to-end flow from our Elixir code to `jose` unless we write those tests ourselves.

Think of these as end-to-end tests that verify our claims in the documentation. For example, we support the `ES512` (signing algorithm because it's one of the algorithms defined in JWT spec) and provide hints on generating the key pair compatible with it. Without testing a token signed using this algorithm and an appropriate key, we can only hope it'll work as expected. Better verify in tests than rely on hope, IMO.

Especially when it comes to public key and elliptic curve cryptography, keys may be encoded in different formats, so it's best to have a tested happy path if only to be able to look it up when we get user feedback complaining about a certain JWT not getting validated by Electric.

2023-06-29 11:16 UTC, alco commented on components/electric/config/runtime.exs
> +        key: Base.decode64!("AgT/MeUiP3SKzw5gC6BZKXk4t1ulnUvZy2d/O73R0sQ="),
No reason, this code was taken from the old implementation verbatim. I have updated it to use a less opaque-looking key.

2023-06-29 11:25 UTC, icehaunter commented on components/electric/test/electric/satellite/auth/jwt_test.exs
> +    end
OK, sounds good

2023-06-29 11:36 UTC, icehaunter commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
> Regarding your last comment, I don't which configuration options are missing from the docs preview. These are all the options that are relevant to auth and they're all mentioned on the docs website:
> 
>     * SATELLITE_AUTH_MODE
> 
>     * SATELLITE_AUTH_JWT_ALG
> 
>     * SATELLITE_AUTH_JWT_KEY
> 
>     * SATELLITE_AUTH_JWT_NAMESPACE
> 
>     * SATELLITE_AUTH_JWT_ISS
> 
>     * SATELLITE_AUTH_JWT_AUD

Yeah, the docs mention all of them, but I'm saying that that's not enough to actually run the container. I believe readme should be sufficient if light on the details. Please please let's add them to the list -- that list was written by me when I was setting up our infra + console (now defunct), and found it very useful to immediately know what variables are available to configure the container. The Docs are very good at explaining the details, but I insist on having enough information for configuring the container in README

2023-06-29 12:08 UTC, alco commented on components/electric/config/runtime.exs
> +            aud: System.get_env("SATELLITE_AUTH_JWT_AUD")
Added.

2023-06-29 12:21 UTC, icehaunter approved these changes

2023-06-29 12:25 UTC, merged