feat: let users pass sync/async functions for resolving values for headers/params
electric-sql/electric pull request #2184
Opened 2024-12-18 16:52 UTC by KyleAMathews

2024-12-18 17:54 UTC, KyleAMathews commented
> Brilliant -- the usage and docs are both 👌

Gotta thank my colleague Windsurf for these 😎

2024-12-19 10:21 UTC, msfstef requested changes
Looks good! I'm a bit weary of adding async steps in the tight loop, and would like more protection (at both the type and runtime level) agains people setting reserved params and headers

2024-12-19 14:01 UTC, KyleAMathews commented on packages/typescript-client/src/client.ts
> +export type ExternalParamsRecord = PostgresParams & {
hmm ok yeah I'll write some type tests (or hopefully windsurf will)

2024-12-19 14:01 UTC, KyleAMathews commented on packages/typescript-client/src/client.ts
> +export type ExternalHeadersRecord = {
👍

2024-12-19 14:02 UTC, KyleAMathews commented on packages/typescript-client/src/client.ts
> +        const requestHeaders = await resolveHeaders(this.options.headers)
If it's actually sync then it'd just wait until the next tick so generally almost immeasurable delay.

2024-12-19 14:03 UTC, KyleAMathews commented on website/docs/api/clients/typescript.md
> +      await refreshToken()
ah right — I'll fix that

2024-12-19 14:05 UTC, KyleAMathews commented on website/docs/api/clients/typescript.md
> +- Dynamic filtering based on current state
It'd reset the stream if they changed the filtering — which perhaps isn't ideal as it'd be better to get more of the stream if possible — but it would work just fine as the new stream would come in and it'd just trigger an immediate re-render

2024-12-19 14:35 UTC, msfstef commented on website/docs/api/clients/typescript.md
> +- Dynamic filtering based on current state
I think the way the code is currently structured it attempts to prevent this from happening with the "core" properties that would reset the stream - and I tend to think that should be the case since they should be what they were initially declared IMO (especially when thinking about our declarative streams topic)

for user-defined stuff it makes total sense though

2024-12-19 15:42 UTC, icehaunter commented on packages/typescript-client/src/client.ts
> +        const requestHeaders = await resolveHeaders(this.options.headers)
> If it's actually sync then it'd just wait until the next t

Is that so? I thought that this releases control to the event loop and it might not immediately return to this place if loop is contended for

2024-12-19 16:11 UTC, msfstef commented on packages/typescript-client/src/client.ts
> +        const requestHeaders = await resolveHeaders(this.options.headers)
It does release it and reinsert it but I think it does that in the microtask queue rather than the full "macrotask" event queue, so the time spent would be small and it wouldn't relinquish control to other "macrotasks" (unless within ithis await there was a timeout or fetch or something)

2024-12-19 16:31 UTC, KyleAMathews commented on packages/typescript-client/src/client.ts
> +        const requestHeaders = await resolveHeaders(this.options.headers)
yeah it'd only be slow if the browser UI thread is bogged down with other CPU-intensive tasks — in which case we'd be delayed even getting to this point or for the fetch to start, etc.

2024-12-19 17:26 UTC, KyleAMathews commented on website/docs/api/clients/typescript.md
> +- Dynamic filtering based on current state
Yeah — people could definitely kill performance if they change stuff constantly — but this feels it falls under the sharp knives principle — https://signalvnoise.com/svn3/provide-sharp-knives/

2024-12-19 18:26 UTC, KyleAMathews commented on packages/typescript-client/src/client.ts
> +export type ExternalHeadersRecord = {
We don't actually send any headers on the request — so there's nothing to check. So I think this is fine.

2024-12-19 18:26 UTC, merged