feat(examples):linearlite without vaxine or local config
electric-sql/electric pull request #221
Opened 2023-07-05 13:11 UTC by paulharter

2023-07-06 10:29 UTC, kevin-dp requested changes
Amazing to see a LinearLite app running on top of Electric =D 

I went through all files and left comments. I'm not sure which parts you wrote/modified and which parts stem from the linearlite app you forked so i may have left comments on parts that were not written by you.

I have a few general comments:
- The formatting across the project is inconsistent and also inconsistent with the formatting we adhere to in the typescript client. Since there are many files, best to set up prettier to automatically format all code.
- There are quite some typescript errors, could you please fix them?
I left a comment in `tsconfig.json` where you should add a line in order to be able to run the typescript compiler using `tsc`.
- There are commented pieces of code and logging statements meant for debugging purposes a bit everywhere. Could you remove those please? :-)

2023-07-06 10:29 UTC, kevin-dp commented on examples/linearlite/src/pages/Board/IssueItem.tsx
> +                {issue.owner ? (
instead of returning a different avatar depending on whether an owner is defined (which btw will never be the case becasue that column does not exist in the DB) it would be better to let the Avatar component handle the case where name and/or avatarUrl are missing. That would simplify this code:
```typescript jsx
<Avatar
  name={issue.owner?.name}
  avatarUrl={issue.owner?.avatar}
/>
```

2023-07-06 10:29 UTC, kevin-dp commented on examples/linearlite/src/pages/Board/IssueCol.tsx
> +// import { Issue } from 'types/issue';
You have to import Issue since you are using it below, but i think you want to `import {issue as Issue} from '../../generated/client'`

2023-07-06 10:29 UTC, kevin-dp commented on examples/linearlite/src/components/IssueModal.tsx
> +function getPriorityString(priority: string) {
The argument can probably be typed more precisely as `Priority` (cf. `types/issue.ts`) instead of `string`. Also these constants are already strings, e.g. `Priority.HIGH` is the string `'high'. So we could replace this entire switch by:
```typescript
function getPriorityString(priority: Priority) {
  return priority.charAt(0).toUpperCase() + priority.slice(1)
}
```

Note that the only functional difference with this code and yours is that `Priority.NO_PRIORITY` is defined as `'no_priority'` and you're here turning it into `'Priority'`. If that's really needed you could special case it in my code above but i would argue that we should seek to unify them, e.g. just use 'no_priority'.

Also, i'm not sure if these priorities really need to be uppercased here or if we can just use them as how they are defined in `Priority`.

2023-07-06 10:29 UTC, kevin-dp commented on examples/linearlite/src/components/IssueModal.tsx
> +        name: "Hello",
why are we hardcoding the name of the issue?

2023-07-06 10:29 UTC, kevin-dp commented on examples/linearlite/src/components/IssueModal.tsx
> +    if (onDismiss) onDismiss();
can be simplified to `onDismiss?.()`

2023-07-06 10:29 UTC, kevin-dp commented on examples/linearlite/src/components/contextmenu/PriorityMenu.tsx
> +    [NoPriorityIcon, 'No priority', Priority.NO_PRIORITY],
the strings that are used here are different from the others.
for example, `Priority.NO_PRIORITY` is defined as `'no_priority'` but i have seen usages of the string `'Priority'` for  `Priority.NO_PRIORITY`  in `getPriorityString` in `issueModal.tsc` and now we there is a 3rd version which is `'No priority'`. Not sure what these are used for but if these are used for anything else than showing to the user this will yield subtle bugs

2023-09-04 13:34 UTC, balegas commented
Closing this PR, referring it from #VAX-942

2023-09-04 13:34 UTC, closed without merging