Initial sync of transactions with deduplication
electric-sql/electric pull request #225
Opened 2023-07-08 19:23 UTC by alco

Closes VAX-734.

TODO...

2023-07-10 08:21 UTC, alco commented on components/electric/lib/electric/replication/initial_sync.ex
> +        lsn: 0,
Not sure if it'd be appropriate to fetch the latest LSN and use that instead of 0.

The only problem with using 0 is that a client who connects for the first time, receives migration transactions but no data and then reconnects, will go through the initial sync of migrations again (though it won't receive duplicate transactions the second time around once https://github.com/electric-sql/electric/pull/226 is merged.

A potential problem with putting the latest LSN into these migration transactions could be inadvertent filtering of a subsequent migration coming from the cached WAL after the initial sync has finished.

2023-07-10 09:44 UTC, alco commented on components/electric/lib/electric/postgres/extension.ex
> +      #{@version_table}.txid ASC
We could have chosen to sort by version instead but there's a potential problem with versions: app developer may set any version for their migration (via `SELECT electric.migration_version('...")`) and we cannot ensure that those versions are monotonically increasing from older migrations to newer ones. In other words, a new migration may end up with a version that sorts _before_ one or more previously applied migrations.

Although that should be avoided in practice because it may caused other issues, even outside Electric, but just to be on the safe side, we sort by txid instead. Because migration transactions are applied serially, we can use their `txid`s as a safe, monotonically increasing criterion for sorting.

2023-07-10 14:03 UTC, kevin-dp commented on components/electric/lib/electric/postgres/extension.ex
> +      #{@version_table}.txid ASC
Interesting, the CLI does depend on the migration versions being in chronological order because it fetches a zip file containing the migrations from Electric. So in this zip file it does not know the order of migrations so it has to sort the migrations based on their version. This problem will be fixed later when Electric exposes the migrations in JSON format instead of a zip file.

2023-07-10 16:46 UTC, alco commented on components/electric/lib/electric/postgres/extension.ex
> +      #{@version_table}.txid ASC
Great point!

I mean, we could assume that versions are ordered correctly (i.e. migrations are always applied in version order) and avoid this complication with reliance on txid. I'm going to flag it up as a discussion point with the team.

2023-07-11 13:02 UTC, icehaunter requested changes
One important question from me, otherwise I think it's good

2023-07-11 13:02 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol.ex
> +  end
I think this is wrong, since we explicitly decided to allow "mixed" transactions (ones with both DDL and DML statements) This shouldn't skip transaction wholesale, it should filter out migrations from changes if they've already been seen

2023-07-12 08:20 UTC, alco commented on components/electric/lib/electric/satellite/protocol.ex
> +  end
This function is meant to skip migrations coming from cached WAL during a very narrow time window: when a migration transaction has been committed while a client is performing initial sync, such that the client receives it as part of initial sync, and then the client subscribes to changes from cached WAL at an LSN that precedes this last transaction's LSN. If this happens, this same transaction will be coming in once again from the cached WAL producer.

At any other time, including a new client connection that doesn't go through the initial sync, this function should be a no-op. I could do a better job of communicating that in the code. I think what I need to add is this: once the current txid coming from the cached WAL producer matches `state.out_rep.last_seen_migration_xid` stored just after the initial sync, the `skip_migration_tx?()` function should explicitly be made a no-op.

Now, regarding whether it's appropriate to drop the full transactions if it is to be skipped. Right after the initial sync, the client may not yet have any active subcriptions. So it doesn't matter if we drop the whole transaction, including its DML.

If the client manages to send a SatSubReq before the duplicate transaction comes in from the cached WAL producer, the client will get the data for the shapes it's subscribing to via the regular path of fetching initial shape data. So the duplicate transaction has to be dropped anyhow because the client will have already received the data part of it.

2023-07-12 13:46 UTC, icehaunter approved these changes

2023-07-12 13:54 UTC, merged