feat(satellite,electric): Rely on client-supplied schema version to push only missing transactions to the client
electric-sql/electric pull request #226
Opened 2023-07-08 19:26 UTC by alco

2023-07-10 06:48 UTC, kevin-dp approved these changes
Good work, looks good to me! Just make sure the e2e tests pass before we merge

2023-07-10 08:28 UTC, alco commented on clients/typescript/test/satellite/client.test.ts
> +      columns: [{name: 'id', sqliteType: 'text', pgType: undefined } as Proto.SatOpMigrate_Column],
I took this code from `test/satellite/process.migration.test.ts` but the TypeScript compiler keeps finding typing issues if I omit explicit casting.

2023-07-10 08:29 UTC, alco commented on clients/typescript/test/satellite/client.test.ts
> +    migrationVersion: '3',
I took this code from `test/satellite/process.migration.test.ts` but it doesn't appear the test database has any migrations in it like the comment above this line claims.

2023-07-10 08:30 UTC, alco commented on clients/typescript/test/satellite/client.test.ts
> +          t.deepEqual(req.schemaVersion, undefined)
I wanted to verify this condition first, then apply a migration to the local DB and verify that `schemaVersion` is no longer `undefined`. I didn't get to that last part yet due to issues described in my other comments above.

2023-07-10 09:46 UTC, alco commented on clients/typescript/src/migrators/bundle.ts
> +        ORDER BY id DESC
I'm ordering by `id` here to ensure the same order in which the migrations were applied. In principle, we could order by `version` instead, but there's a possibility (even though it's vanishingly small) that migrations are applied to the PG database in a different order than the one defined by their versions. See https://github.com/electric-sql/electric/pull/225/files#r1257996658 for additional context.

2023-07-10 15:02 UTC, kevin-dp commented on clients/typescript/test/satellite/client.test.ts
> +      columns: [{name: 'id', sqliteType: 'text', pgType: undefined } as Proto.SatOpMigrate_Column],
The problem is that `satellite._applyTransaction()` expects an object of type `Transaction`:
```
export type Transaction = {
  commit_timestamp: Long
  lsn: LSN
  changes: Change[]
  // This field is only set by transactions coming from Electric
  origin?: string
  migrationVersion?: string // the Postgres version number if this is a migration
}
```

The `changes` is of type `Change[]` which is:
```
export type Change = DataChange | SchemaChange

export type SchemaChange = {
  table: MigrationTable // table affected by the schema change
  migrationType: SatOpMigrate_Type
  sql: string
}

export type MigrationTable = Omit<SatOpMigrate_Table, '$type'>
```

So, we don't need to provide a `$type` field on `SatOpMigrate_Table` but inside `SatOpMigrate_Table` the `columns` and `fks` properties are of type `SatOpMigrate_Column[]` and `SatOpMigrate_ForeignKey[]` respectively. Both of these types expect a `$type` field, which you are not providing in your `columns` property.

However, our code does not actually use these `$type` fields so we can remove them from the type.
Changing the `MigrationTable` type as follows solves the issue:
```
export type MigrationTable = Omit<SatOpMigrate_Table, '$type' | 'columns' | 'fks'> & {
  columns: Array<Omit<SatOpMigrate_Column, '$type'>>
  fks: Array<Omit<SatOpMigrate_ForeignKey, '$type'>>
}
```

2023-07-10 15:13 UTC, kevin-dp commented on clients/typescript/test/satellite/client.test.ts
> +    migrationVersion: '3',
In the `process.migration.test.ts` we call `await satellite.start(authState)` before every test.
Satellite then calls `migrator.up()` which loads the migrations defined in `test/support/migrations/migrations.js` and hence the DB contains those 2 migrations.

However, in your test, those migrations are never loaded, so you can use `migrationVersion: '1'`.

2023-07-10 15:19 UTC, kevin-dp commented on clients/typescript/test/satellite/client.test.ts
> +          t.deepEqual(req.schemaVersion, undefined)
i would replace the if test by an assertion, `t.assert(msgType == getTypeFromString(Proto.SatInStartReplicationReq.$type))`.
Also, `deepEqual` is useful to compare objects for structural equality instead of referential equality.
In this case, you're comparing primitive values so you can just do `t.assert(req.schemaVersion === undefined)`.
No need to call `t.pass()` here.

2023-07-12 17:57 UTC, icehaunter commented
It seems like relevant e2e tests are still failing

2023-07-12 20:51 UTC, alco commented
@icehaunter Fixed.

2023-07-13 09:23 UTC, icehaunter requested changes
Looks nice, but I have one important question and some nitpicks

2023-07-13 09:23 UTC, icehaunter commented on components/electric/lib/electric/satellite/ws_server.ex
> +    migration_transactions = InitialSync.migrations_since(schema_version, state.pg_connector_opts)
Not sure where to leave this comment, but:

I'm not sure, I'd rather deny connection if the supplied migration version isn't known. It means the client is either ahead and we can't do replication or misbehaving (or DB has been reset) and we can't do replication. That means I would rather do a "is a known migration?" check on connection against the cache, not in this "continuation" handler

2023-07-13 09:23 UTC, icehaunter commented on components/electric/test/electric/satellite/ws_server_test.exs
> +    test "no migrations are delivered as part of initial sync if PG has no electrified tables",
I don't see a test to check if the proper migrations are sent if `schema_version` is present in ReplicationReq

2023-07-13 09:23 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
>    ): Promise<void | SatelliteError> {
Just while we're here

```suggestion
  ): Promise<void> {
```

2023-07-13 09:23 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      .then(() => this.migrator.querySchemaVersion())
optional, feel free to skip: I'd appreciate a rewrite of this chain to `await`s

2023-07-13 09:28 UTC, alco commented on clients/typescript/src/satellite/process.ts
> +      .then(() => this.migrator.querySchemaVersion())
It's curious that I had this call as an `await` first but Kevin suggested that I include it in this chain of `then`s. But now Kevin is rewriting all of it as a sequence of `await` calls in https://github.com/electric-sql/electric/pull/247/commits/4ea8afecfadfbdcb163e8c223517b94e1e9a1341#diff-4ae478716dc5aae8eca5e417ee51fbb261dc105b923b67eff253f2a25ae42d95L490-R508.

2023-07-13 10:42 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      .then(() => this.migrator.querySchemaVersion())
Lol. it's either all `await` or all `then`, not a good practice to mix unless it's mostly awaits and a one-off `then`. Don't worry about this then for now, whoever merges second will get to resolve the conflict :D

2023-07-13 13:42 UTC, alco commented on components/electric/test/electric/satellite/ws_server_test.exs
> +    test "no migrations are delivered as part of initial sync if PG has no electrified tables",
This is a good point. Added one test. Writing it turned out to be a huge pain in the ass because of the whole mocking of things that are involved in maintaining the schema cache and migration versions.

2023-07-17 12:08 UTC, merged