client: fix buggy connectivity hook.
electric-sql/electric pull request #298
Opened 2023-07-26 18:46 UTC by thruflo

The problem was that existing satellite processes were not reporting their existing connectivity status to the connectivity hook. This was confusing the hook into always starting in a disconnected state, despite the connection being connected.

I've left one note in the code about a future refactor. I'm not convinced by the current code structure and connectivity state machine. But suggesting we merge this as we need the fix urgently.

2023-07-26 19:24 UTC, thruflo commented
p.s.: someone please tell me the right command to run prettier properly!

2023-07-26 19:52 UTC, alco commented
@thruflo Run `pnpm format` inside the `clients/typescript` directory.

2023-07-27 10:04 UTC, icehaunter requested changes

2023-07-27 10:04 UTC, icehaunter commented on clients/typescript/src/client/model/client.ts
> +    })
This feels very weird and indirect to me. 

So before this change, the `const electric = new ElectricNamespace()` variable in `src/satellite/index.ts` was used in a mildly weird way: it was used for the constructor, and then only `.adapter` and `.notifier` properties got used from that instance. This `ElectricClient` instance extends `ElectricNamespace` - so it will be initialized again with the same notifier, but now you're building a closure to capture a previous namespace and use `isConnected` value from there instead of using `isConnected` value derived from the `extends ElectricNamespace`. I honestly see no reason at all for this override: if it's just so you can run `electric.setIsConnected(satellite.connectivityState)` in `src/satellite/index.ts` then you can remove this property and call `namespace.setIsConnected` a couple lines down in the same file.

I don't know why we need that kind of cognitive load - figuring out how/why this is working took a minute. 

I think the correct change would be to:
1. Replace the `electric: ElectricNamespace` parameter in `create` with explcit `adapter` and `notifier`. Same for this constructor.
2. Don't create a "transient" `ElectricNamespace` instance in `src/satellite/index.ts` at all - it doesn't get used and the same constructor code runs perfectly well here in the `super` call.
3. Move `electric.setIsConnected(satellite.connectivityState)` to instead reference the created `ElectricClient` instance directly.

That way it's cleaner, we're setting up one less listener, have only once source of truth instance, and don't need an ugly `definePropery` call in constructor

2023-08-01 14:44 UTC, thruflo commented on clients/typescript/src/client/model/client.ts
> +    })
Totally. Be very good to simplify this.

As a left field thought: perhaps the electric client should just have a reference to the satellite process?

2023-08-01 15:26 UTC, kevin-dp approved these changes

2023-08-01 15:26 UTC, kevin-dp commented on clients/typescript/src/frameworks/react/hooks/useConnectivityState.ts
> +const STATES: {
Why not using a TypeScript enumeration for this?

2023-08-01 15:29 UTC, icehaunter approved these changes

2023-08-01 15:29 UTC, merged