VAX-807: cannot catch up to the servers current state
electric-sql/electric pull request #319
Opened 2023-08-07 21:18 UTC by balegas

After server is gone, it loses information about clients. Right now it is throwing a BEHIND_WINDOW error when a client tries to reconnect. It's arguable if this is the appropriate error to throw, but it highlighted a problem with failures to reconnect on error.

1. the client would not trigger subscriptions cleanup because of improper configuration
2. it would send unsubscribe requests to the server without first starting replication, which would throw an error
3. there was de-referencing error to a variable that was out of scope()
4. we did not close the client before attempting to reconnect, which is undefined behaviour

2023-08-07 22:29 UTC, balegas commented on clients/typescript/src/satellite/index.ts
> +  start(authConfig: AuthConfig): Promise<ConnectionWrapper>
flattened options. Not necessary for now, I guess.
Happy to revert to avoid changing api and types but need to thread through behindWindow flag in multiple places

2023-08-07 22:29 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> -    await this.client.unsubscribe(ids)
this causes an error because replication state hasn't been changed. However, we don't need to call unsubscribe because we're clearing local state and next time we connect, server will throw away client data.

It's a small optimisation to ensure we clear subscriptions early. Don't mind doing that.

2023-08-07 22:29 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +        await this._handleSubscriptionError(error)
this seems to be the right procedure on the client, but we still missing re-subscriptions from the app.

2023-08-07 22:29 UTC, balegas commented on clients/typescript/src/util/types.ts
> +  CONNECTION_FAILED,
Error thrown if client can't reach Electric. Opened VAX-830 because client should long poll to try to reconnect to server. I think I wrote that code, but doesn't seem to be working

2023-08-08 08:58 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +        await this.client.close()
connectivity hook does this, but it might race, so better do it twice, I think. Although doesn't seem to create a lot of trouble not to do it

2023-08-11 09:09 UTC, thruflo commented
Will these changes will also fix https://linear.app/electric-sql/issue/VAX-831/replication-not-active-error-when-cant-reach-backend ?

2023-08-14 09:54 UTC, icehaunter requested changes
Great work! I have some nitpicks/suggestions and one possible bug highlighted

2023-08-14 09:54 UTC, icehaunter commented on clients/typescript/src/satellite/client.ts
> -      this.initializing!.reject(e)
Why not do this then?

```suggestion
      this.initializing?.reject(e)
```

2023-08-14 10:58 UTC, balegas reviewed
Thanks, will review all suggestions shortly

2023-08-14 10:58 UTC, balegas commented on clients/typescript/src/satellite/client.ts
> -      this.initializing!.reject(e)
I'm afraid there is a larger issue here that is not being addressed. 
- I feel like the behind window exception should not reach here. Maybe it doesn't any longer, I can check
- but, initializing could only be undefined at this point if we closed before. In that case, I think we should reject on close (and provide error context to close).

2023-08-14 10:58 UTC, balegas commented on clients/typescript/src/satellite/client.ts
> +      this.emit('error', error)
I agree, its swallowing too much info. Will apply the suggestion

2023-08-14 10:58 UTC, balegas commented on clients/typescript/src/satellite/client.ts
> +    Log.info(`Sending message ${JSON.stringify(request)}`)
Right, unintended.

Let me raise here that I would like very much to review the patters we use in the e2e for matching messages. Right now is impossible to print messages that have data, because prints all the bytes. I wanted to just print the type, but found out that e2e relies on more info on this strings.

I was thinking two approaches, but both are a bit processing heavy:
- parse the message and hide all the byte arrays (I tried it, but I think this needs some deep traversal to do right)
- have specific prints for each messages

2023-08-14 10:58 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +    tablenames.forEach((t) => this.notifier.actuallyChanged(t, []))
Thanks for finding this, I think this is also some remnants of my root cause analysis. I'll try to check hwo things work without that line -- which should be doing nothing atm.

2023-08-14 10:58 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +      .filter((s): s is ShapeDefinition[] => s != undefined)
I've been suggested to change this, and it's a think that I should just change my default.

for my edification, what is the difference if we're comparing with undefined?

2023-08-14 11:16 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +    tablenames.forEach((t) => this.notifier.actuallyChanged(t, []))
Yeah, that line is a no-op right now

2023-08-14 11:22 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      .filter((s): s is ShapeDefinition[] => s != undefined)
Functionally, `null == undefined` but `null !== undefined`, but practically since `==` (and `!=`) does implicit type conversions before doing the comparison, it's a really good idea to never use `==` at all. It can hide errors (although less so with typescript, but if you let `any` sneak in which can happen you're in for a runtime treat). It's a good thing to never use it so you don't forget it in a critical place later. ESLint even has a  rule to just disallow non-strict equality checks: https://eslint.org/docs/latest/rules/eqeqeq.

2023-08-14 14:41 UTC, icehaunter approved these changes

2023-08-21 13:08 UTC, icehaunter requested changes
Hey, I'm a bit unsure of very suddenly using a `Result ` monad in just this one place with no visible benefit. Can we discuss the reason for this approach?

2023-08-21 13:08 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
>      } catch (error: any) {
This feels like a very weird and uncommon pattern for Typescript. I don't understand how it's better than doing that `if` with `return` within a `catch` clause. Getting the error as a `Result` and then immediately throwing it JUST to catch it?

2023-08-21 13:08 UTC, icehaunter commented on clients/typescript/src/satellite/client.ts
> -      this.emit(
Why aren't we doing `this.emit` anymore and it's fine?

2023-08-21 13:55 UTC, balegas reviewed
Thanks, applied your suggestion and replied to your question

2023-08-21 13:55 UTC, balegas commented on clients/typescript/src/satellite/process.ts
>      } catch (error: any) {
nothing against that suggestion. Applied it.

2023-08-21 13:55 UTC, balegas commented on clients/typescript/src/satellite/client.ts
> -      this.emit(
RPC errors where being handled inconsistently. Some would emit 'error', others would reply with a response object with an error field.
In practice, in the first case we would handle the response in a catch clause, in the latter we would process the response with error.
I consolidated on the latter.

2023-08-21 13:55 UTC, balegas commented on clients/typescript/src/satellite/client.ts
> +      const errorListener = (error: SatelliteError) => {
In fact we can't ensure this is a SatelliteError. Reverting

2023-08-22 07:13 UTC, icehaunter requested changes
This is the final discussion comment from me, although I somewhat feel like we're complicating this more than it should be. What do you think? If you feel like this is nitpicking - feel free to merge, we can give it another pass at a later date, but it seems like the current complicated implementation may hide some bugs - I believe I may have spotted at least two

2023-08-22 09:19 UTC, icehaunter approved these changes

2023-08-22 15:10 UTC, merged

2023-08-22 15:10 UTC, balegas commented
@icehaunter thanks for bearing with me on all the back-and-forth with this one