feat(electric): Add server-side validation of row values incoming from Satellite clients
electric-sql/electric pull request #320
Opened 2023-08-08 10:02 UTC by alco

Closes VAX-813.

[ ] Validate values of nullable and non-nullable columns

2023-08-14 09:42 UTC, magnetised requested changes
few nitpicks but otherwise great

2023-08-14 09:42 UTC, magnetised commented on components/electric/lib/electric/postgres/postgres_manager.ex
> +           oids =
can we split this stage into a separate function and keep this `with` block as clean as possible, in fact why split this bit out of the `OidDatabase` module? could easily just pass in the `conn_config` and keep all this messiness out of this "manager"

2023-08-14 09:42 UTC, magnetised commented on components/electric/lib/electric/postgres/postgres_manager.ex
> +    type_server = Postgrex.TypeSupervisor.locate(Postgrex.DefaultTypes, type_server_key)
how stable are these APIs? 😰 

well done for digging them out though!

2023-08-14 09:42 UTC, magnetised commented on components/electric/lib/electric/satellite/serialization.ex
> +  defp decode_record(nil, _columns, true), do: nil
this 3rd argument boolean would be clearer as an atom, say `:nil_valid`, `:nil_ok` or something

2023-08-14 09:42 UTC, magnetised commented on components/electric/lib/electric/satellite/serialization.ex
> +      {_type, _val, true = _null?} ->
i think the need to label the boolean with a `_null?` var suggests that maybe `bitmask_to_boolean` should be `bit_mask_to_null` and return `:null` rather than true/false

2023-08-14 10:21 UTC, alco commented on components/electric/lib/electric/postgres/postgres_manager.ex
> +    type_server = Postgrex.TypeSupervisor.locate(Postgrex.DefaultTypes, type_server_key)
Last time the `Postgrex.Types` module saw a behaviour-changing update was in 2021. And both `Postgrex.TypeSupervisor` and `Postgrex.TypeServer` were last updated in 2019.

2023-08-14 10:44 UTC, alco commented
@magnetised Great feedback! I've implemented your suggestions.

2023-08-14 10:45 UTC, magnetised approved these changes
magic

2023-08-14 10:46 UTC, icehaunter requested changes
Good work, cool to see a bit more rigidity in the system! I have one slightly philosophical question.

2023-08-14 10:46 UTC, icehaunter commented on components/electric/lib/electric/satellite/validation.ex
> +  def assert_type!(val, col_type) do
Could you add a docstring here?

2023-08-14 10:46 UTC, icehaunter commented on components/electric/lib/electric/satellite/validation.ex
> +      |> Postgrex.DefaultTypes.encode_value(postgrex_ext)
So correct me if I'm wrong, but it feels like we're relying on multiple internal Postgrex APIs essentially just to validate ranges on types. I'm not sure how much I agree with this, given that we're doing the actual hard lifting below, in `parse_column_value/2`, to do a first pass of validation for data coming form Satellite. If we were calling `.decode_value()` of some kind on Postgres, I would have been fine with it, but pulling in a bunch of code to do very little seems a bit unreasonable. Especially when we're going to need to evaluate row constraints on parsed values anyway - it seems like maybe keeping most code in our codebase would be reasonably OK?

My argument is fully based on the notion that we're already doing heavy lifing on our side in parsing, and we're going to do that even more: our "intermediate representation" of a value that SQLite can interact with is going to likely differ from PG representaiton (or we're going to do quite a bit of conversions on the client, which is also OK). In particular, think of array serialization: SQLite can only benefit from JSON arrays, while PG can have the same array as `int4[]` and we're going to need to marry that up somehow. Seems to me that most complicated logic will live "on our side" anyway, so I don't see a need to drop down to Postgrex just to check if int is indeed int4.

WDYT?

2023-08-15 07:37 UTC, alco commented on components/electric/lib/electric/satellite/validation.ex
> +      |> Postgrex.DefaultTypes.encode_value(postgrex_ext)
You're absolutely right!

I may have been carried away by thoughts of using more of Postgrex further down the road, e.g. as a more Elixir-native way of interfacing with Postgres compared to epgsql. I was also thinking we could start using Postgrex's encoding/decoding functionality to switch to the binary encoding of row data in the logical replication stream.

But all of that is irrelevant to the current task. And as I've learned by now, Postgrex does not do everything we need to be doing in terms of validation. For example, it doesn't do any validation for sized `char` and `varchar` types, it simply lets Postgres report an error if the user data exceeds the length limit.

I have removed Postgrex and rethought the idea of validation a bit, making more emphasis on decoding values coming from Satellite, rather than validating them. This will be mirror by the corresponding encoding of some types as can be seen already in the upcoming PR that adds support for `timestamp` types - https://github.com/electric-sql/electric/pull/330.

2023-08-15 07:39 UTC, alco commented on components/electric/test/electric/satellite/ws_validations_test.exs
> -        "CREATE TABLE public.foo (id TEXT PRIMARY KEY, f4 REAL, f8 DOUBLE PRECISION)"
I haven't found a way to reliably tell if a given float number can fit in a 4-byte float without loss of precision. For now, I'm leaving support only for double precision floats.

2023-08-15 07:44 UTC, magnetised reviewed
actually much simpler without postgrex huh. I'm not particularly worried about the performance tweak but I think a more helpful error in the out-of-range-integer case is worth it

in fact, should this validation step raise at all? don't we want to feed back to the client rather than crash the process?

2023-08-15 07:44 UTC, magnetised commented on components/electric/lib/electric/satellite/serialization.ex
> +  defp assert_integer_in_range!(int, :int2) when int in @int2_range, do: :ok
this function will raise a matcherror (I think) when an integer is out of range -- wouldn't it be helpful to raise some `"integer column #{column_name} value #{value} is outside the range of a #{type}"` type exception

2023-08-15 07:44 UTC, magnetised commented on components/electric/lib/electric/satellite/serialization.ex
> +    |> apply_nulls_bitmask(bitmask)
this is very much in the hot path of the system, could we do the same thing in a single pass?

2023-08-15 07:53 UTC, alco commented
@magnetised 

> in fact, should this validation step raise at all? don't we want to feed back to the client rather than crash the process?

The validation is initiated via the call to `Serialization.deserialize_trans()` from `Electric.Satellite.Protocol`. The call is wrapped in a `try` block there, so any exception is transformed into an `INVALID_REQUEST` response to the client. No processes crash as a result of this.

On the server, we do get the exception logged with all the details. In the example with `int2`, the log entry is pretty clear about which function clause failed to match (that one that has `:int2` as the second argument).

As for the client, we don't have a proper mechanism for reporting such critical errors to the user. From the perspective of the client app, it did its write locally and moved on. It doesn't track how this write is then synced to the server in background and results in an error response from the server. We want to avoid having this is a valid error state in practice because once a local write has succeeded, it should eventually get synced to the server.

What I think would be useful to add eventually is a way to report validation faliures to the app developer.

2023-08-15 07:54 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +    |> apply_nulls_bitmask(bitmask)
Do you mean squashing this function pipeline into a single loop that does everything: check for nulls, validate types and produce the {name, value} tuple?

2023-08-15 07:55 UTC, magnetised commented
> On the server, we do get the exception logged with all the details. In the example with `int2`, the log entry is pretty clear about which function clause failed to match (that one that has `:int2` as the second argument).

ok, seems vaguely irresponsible but ok... ;)

> As for the client, we don't have a proper mechanism for reporting such critical errors to the user. From the perspective of the client app, it did its write locally and moved on. It doesn't track how this write is then synced to the server in background and results in an error response from the server. We want to avoid having this is a valid error state in practice because once a local write has succeeded, it should eventually get synced to the server.

that's a much bigger fish. gotcha

2023-08-15 10:39 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +    |> apply_nulls_bitmask(bitmask)
Updated.

2023-08-15 11:57 UTC, merged