feat(electric, satellite): Add support for timestamp and timestamptz column types
electric-sql/electric pull request #330
Opened 2023-08-09 14:04 UTC by alco

Closes VAX-818.

2023-08-09 14:09 UTC, thruflo commented
So you think we need to serialise the values in the DAL?

2023-09-13 09:18 UTC, icehaunter requested changes

2023-09-13 09:18 UTC, icehaunter commented on components/electric/lib/electric/satellite/serialization.ex
> +      timestamp timestamptz
This function is weird placed here, because it's used in the `20230605141256_electrify_function.ex` migration, but that migration is not reran on Electric upgrade, meaning in-place upgrades are not going to expand functionality to allow these new columns. I think we either need a special function that runs on every startup against PG and updates the `electrify` function to use the new types, or we need to add a new migration to do that for each type PR

2023-09-13 09:18 UTC, icehaunter commented on components/electric/test/electric/satellite/serialization_test.exs
> -    mask = <<0b1101000010000000::16>>
Could you please preserve the long bimask test? Bitmask format (direction, namely) discrepancy between server and client was a source of weird bugs very early in development and I'd have this double-checked

2023-09-13 09:18 UTC, icehaunter commented on components/electric/lib/electric/satellite/serialization.ex
> +  def decode_column_value(val, :timestamp) do
nitpick: I would appreciate it if you renamed `decode_column_value` and `decode_record` functions to `decode_column_value!` and `decode_record!` because it took me a minute to recall that missed matches here are intended behaviour

2023-09-13 09:20 UTC, icehaunter commented
Sorry, VSCode Github plugin submitted the review without the top comment

The PR looks good to me! I don't have any issues with timestamp implementation and details, but some auxiallary questions. The "no migration" problem seems quite important

2023-09-13 09:54 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +      timestamp timestamptz
It's a very good point. But since it's not directly related to an implementation of any specific type, I'm going to take the liberty of addressing it separately, just prior to merging the PRs that add support for new types.

I've addressed your other comments.

2023-09-13 10:51 UTC, icehaunter commented on components/electric/lib/electric/satellite/serialization.ex
> +      timestamp timestamptz
Ok, sounds good

2023-09-13 10:51 UTC, icehaunter approved these changes

2023-09-14 11:40 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +      timestamp timestamptz
Garry has proposed to define all PG functions when Electric starts to avoid issues with putting them in migrations --  https://linear.app/electric-sql/issue/VAX-1016/change-migration-mechanism-for-pg-functions.

Before that is implemented, I can make the type-checking function defined at runtime to address the immediate issue of adding new types in a backwards-compatible manner. But that's better done after all the current type PRs are merged to avoid another cascading rebase fest.

2023-09-14 11:57 UTC, merged