chore(example): improved web-wa-sqlite example
electric-sql/electric pull request #333
Opened 2023-08-10 17:06 UTC by balegas

Took the template from the starter. Updated instructions

2023-08-10 17:37 UTC, thruflo requested changes

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/README.md
> +If you're looking into running the services yourself, check the instructions in [running the examples](https://electric-sql.com/docs/examples/notes/running#running-your-own-postgres) page, which has
"connect the [Electric sync service](https://electric-sql.com/docs/api/service)"

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/README.md
> +If you're looking into running the services yourself, check the instructions in [running the examples](https://electric-sql.com/docs/examples/notes/running#running-your-own-postgres) page, which has
I'd also suggest moving down to a notes section and matching the wording of the https://github.com/electric-sql/electric/blob/09c413252d9e846f73166932e05cde803575db67/examples/starter/template/README.md throughout.

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/README.md
> +This produces a type-checked model of your schema that can be used to build the app.
I think this line is unecessary.

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/README.md
> +That's it! You're running a local-first app that synchs changed with other connected devices through Electric sync service.
syncs

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/README.md
> +That's it! You're running a local-first app that synchs changed with other connected devices through Electric sync service.
changes

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/README.md
> +That's it! You're running a local-first app that synchs changed with other connected devices through Electric sync service.
the Electric sync service

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/backend/compose/docker-compose.yaml
> +      # Currently published version (electric-sql@0.5.0-next.4)
I believe we've published `next.5`?

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/db/migrate.js
> +  console.log('⚡️ Database is migrated.')
I suggest `'Database migrated.'`.

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/package.json
> -  "author": "Valter Balegas",
I think in this example we do want an Author (can be Valter Balegas or perhaps ElectricSQL) and we do want to include the Apache 2 license field.

We took out from the starter because they're not appropriate there.

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/src/Example.tsx
> +  const items: Items[] = results !== undefined ? results : []
`const items: Items[] = results ?? []` would also be correct and terser.

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/public/wa-sqlite-async.wasm
The copied wasm files should be removed and gitignored.

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/src/generated/client/index.ts
And the generated client files should also be removed and gitignored.

2023-08-10 17:37 UTC, thruflo commented on examples/web-wa-sqlite/src/generated/client/migrations.ts
as per above

2023-08-10 17:42 UTC, thruflo commented
Btw, Im not sure `copy-wasm` on every build is the right pattern. Perhaps we need to document it as a step and remove from yarn build.

2023-08-10 21:52 UTC, balegas commented on examples/web-wa-sqlite/README.md
> +If you're looking into running the services yourself, check the instructions in [running the examples](https://electric-sql.com/docs/examples/notes/running#running-your-own-postgres) page, which has
Fine. Note that we need to document [DATABASE_URL](https://github.com/electric-sql/electric/pull/332/files#r1290701185) in the template.

Either duplicate the note in this file, or link to it (I prefer the first).
- [ ] Leaving this task open until starter template is updated

2023-08-10 21:52 UTC, balegas commented on examples/web-wa-sqlite/backend/compose/docker-compose.yaml
> +      # Currently published version (electric-sql@0.5.0-next.4)
- [ ] Leaving this task open until starter template is updated @kevin-dp

2023-08-10 21:52 UTC, balegas commented on examples/web-wa-sqlite/db/migrate.js
> +  console.log('⚡️ Database is migrated.')
- [ ] Leaving this task open until starter template is updated @kevin-dp

2023-08-10 21:52 UTC, balegas commented on examples/web-wa-sqlite/src/generated/client/index.ts
You're right. Remnants from previous example

2023-08-10 21:52 UTC, balegas commented on examples/web-wa-sqlite/public/wa-sqlite-async.wasm
applied the suggestion, but I think this is more relevant for the template @kevin-dp.

2023-08-10 21:52 UTC, balegas commented on examples/web-wa-sqlite/src/generated/client/index.ts
applied the suggestion, but I think this is more relevant for the template @kevin-dp 

Interestingly we don't have a lock file for the example. Shall we add yarn.lock?

2023-08-10 21:57 UTC, balegas commented on examples/web-wa-sqlite/backend/compose/docker-compose.yaml
> +      # Currently published version (electric-sql@0.5.0-next.4)
better to just remove those comments

2023-08-22 08:04 UTC, thruflo approved these changes

2023-08-22 08:04 UTC, thruflo commented on examples/web-wa-sqlite/README.md
> +yarn db:connect
I really think this should be `yarn db:psql`

2023-08-22 08:08 UTC, balegas commented on examples/web-wa-sqlite/README.md
> +yarn db:connect
yep, Kevin changed that. applying here.

2023-08-22 10:21 UTC, merged