Continuing VAX-830
electric-sql/electric pull request #357
Opened 2023-08-23 22:56 UTC by balegas

See commit messages for context about changes.

- [ ] rebase on latest main
- [ ] fix tests
- [ ] verify socket implementations again

Reconnection is working flawlessly with a single demo (http://localhost:3000/docs/intro/local-first)

2023-08-24 10:36 UTC, icehaunter reviewed
I really like the approach you've taken. Code feels quite a bit cleaner. Big props! I have some questions, but nothing too critical I think

2023-08-24 10:36 UTC, icehaunter commented on clients/typescript/src/sockets/node.ts
> +    this.socket.on('error', (_unusedError) =>
Let's add a `Log.error` here, just so we have some visibility over the socker closing?

2023-08-24 10:36 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +    }
```suggestion
    await this.initializing?.promise
```

Awaiting undefined is a no-op, so we can do it like that.

2023-08-24 10:36 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +  async _connect(): Promise<void> {
Then make it private :D


```suggestion
  private async _connect(): Promise<void> {
```

2023-08-24 10:36 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      }
nitpick: and this is why `authenticate` should also throw :P

2023-08-24 10:36 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +      await this.initializing.promise
I may be wrong, but my gut feeling is that this may need some care in that in the sequence of events
1. `await start()`
2. `await subscribe()`

If `initializing` is rejected, the requested subscription gets stuck because it wasn't cleaned up with `this.subscriptions.subscriptionCancelled`

Another point of interest: is it possible to call this method before `start` was called or had a chance to reach `_connectWithBackoff`? Probably not if `electrify` was awaited, right? Just thinking of actual use in React apps.

2023-08-24 10:36 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +const connectionRetryPolicy: Partial<IBackOffOptions> = {
nitpick: We may want to pull this into a class property just so it can be overridden in tests easily

2023-08-24 10:36 UTC, icehaunter requested changes
I really like the approach you've taken. Code feels quite a bit cleaner. Big props! I have some questions, but nothing too critical I think

2023-08-24 13:21 UTC, balegas commented on clients/typescript/src/sockets/node.ts
> +    this.socket.on('error', (_unusedError) =>
error will always trigger logging on the process, but a process might no longer be listening. So that is a good idea.

added logging on the client listener.

2023-08-24 13:23 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +  async _connect(): Promise<void> {
sure :). I had to remove a bunch of internal calls to connect too.

2023-08-24 13:29 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +      await this.initializing.promise
the initializing is horrible. Specially the double-throw. We need to fix this.

I think this remains a source of bugs. added to triage.

2023-08-28 14:04 UTC, icehaunter commented on clients/typescript/src/sockets/web.ts
> +  private errorListener = () => {
This likely should be a method and not a property if this is never reassigned

2023-08-28 14:07 UTC, icehaunter commented on clients/typescript/src/sockets/web.ts
> +    }
This can be written slightly more error-resistant without the `!`
```suggestion
    let callback: (() => void) | undefined
    while (callback = this.connectCallbacks.pop()) {
      callback()
    }
```

2023-08-28 14:09 UTC, icehaunter commented on clients/typescript/src/util/common.ts
> +  {
Is this extra block level intentional?..

2023-08-28 14:10 UTC, icehaunter commented on clients/typescript/src/util/common.ts
> +      finished,
I don't think this works? Will the object store a reference to closed variable here? I may be wrong though

2023-08-28 14:46 UTC, balegas commented on clients/typescript/src/satellite/client.ts
>        this.socket!.closeAndRemoveListeners()
let's add that lint rule when a good moment (and that other one to avoid testing conditions on fuction definitions :D)

2023-08-28 14:46 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +  }
yeah, should have not mixed approaches

2023-08-28 15:04 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +  _handleAck: AckCallback = async (lsn: LSN, type: AckType) => {
out of place

2023-08-28 15:33 UTC, balegas commented on clients/typescript/src/util/common.ts
> +      finished,
oh, this was silly.... All the bug fixing without proper tests and just confirming our own intuition is recipe for disaster.

2023-08-30 10:17 UTC, icehaunter approved these changes
Looks good, great work!

2023-08-30 14:37 UTC, merged