chore(electric): Do not lose client writes when Electric restarts
electric-sql/electric pull request #386
Opened 2023-08-29 15:17 UTC by alco

Closes VAX-911.

Notes:

* @icehaunter I remember your suggestion to use a connection pool in WsServer. I want to address that in a follow-up PR to add one pool for use both by the LSN fetching function and initial sync. Both are initiated by a WsServer process.
* @magnetised I don't fully understand the need for SchemaCache to implement the SchemaLoader behaviour. It makes the definition somewhat circular when SchemaCache itself calls functions from SchemaLoader. If the goal is to have an abstraction on top of epgsql, then we can abstract just that behind an adapter strategy and make SchemaCache a standalone module that does not implement any behaviour.

2023-09-04 13:10 UTC, balegas commented
I like that this issue is number 911

2023-09-04 14:04 UTC, alco commented on components/electric/lib/electric/postgres/extension/migrations/20230829000000_acknowledged_client_lsns_table.ex
> +      client_id TEXT PRIMARY KEY,
It's probably a good idea to constrain this column to some fixed length. But I don't what value to pick.

2023-09-05 09:37 UTC, magnetised requested changes
Since we're having to mess with an otherwise purely application-level and electric-level split that we'd managed to maintain up til now, I think it's worth doing the work to make it consistent at a slightly deeper level in terms of how we build the list of replicated tables, in particular which are managed by the schema (and schema loader backed by pg plus migration machinery) and which are or can be purely functional/generated based on that and our extension infra.

2023-09-05 09:37 UTC, magnetised commented on components/electric/lib/electric/postgres/extension.ex
> +      migration_module.create_table_ddl()
what about if a migration  needs to create > 1 replicated table, shouldn't `create_table_ddl/0` return a list

2023-09-05 09:37 UTC, magnetised commented on components/electric/lib/electric/postgres/extension/migrations/20230829000000_acknowledged_client_lsns_table.ex
> +  def create_table_ddl do
I think this needs a different name, e.g. `replicated_tables_ddl` because you only need to use if if you're adding the internal table to the replication publication.

2023-09-05 09:37 UTC, magnetised commented on components/electric/lib/electric/replication/postgres/migration_consumer.ex
> +          if relation == Extension.acked_client_lsn_relation() do
could we replace this if with another guard clause e.g. `is_client_lsn_relation/1` so that we keep all the relations that we act on at the top level

2023-09-05 09:37 UTC, magnetised commented on components/electric/lib/electric/replication/satellite_collector_producer.ex
> +      # NOTE(alco): !!! Potential data race warning !!!
perhaps lower the scare-factor of this comment, which starts off "warning!!" of an un-handled scenario leading to bugs then goes on to say that actually it's fine, n.p.

2023-09-05 09:37 UTC, magnetised commented on docs/api/service.md
> -| Variable                                                        | Description
it's annoying that when you change a line in these tables, the whole thing gets reformatted, making it hard to see what's changed. we should perhaps remove the alignment of the table markers so we can track what's going on (I managed to make a one-line change by turning off markdown mode in vim and just deleting the line, which stopped any re-formatting on save)

2023-09-05 09:37 UTC, magnetised commented on components/electric/lib/electric/postgres/extension/schema_loader.ex
> -  @callback electrified_tables(state()) :: {:ok, [table()]} | {:error, term()}
I don't like the removal of the electrified tables callback. I get that we need a separate callback that lists all tables in the replication publication (only some of which are "electrified" in the sense of application data that's been added by the developer) but removing the call to list those application-level tables seems like a mistake. 

perhaps we should keep the electrified_tables call, but remove the shadow table list from it and move those shadow tables to the new "all replicated tables" function, which would be purer.

also, this `internal_schema` call is purely an extension managed thing. the purpose of the schema_loader is to abstract the storage and retrieval of schema info, but the internal schema is defined purely in code so every implementation will just call the underlying `Extension` function.

so perhaps there's a need for a `replicated_tables` function which takes a loader impl as an arg and returns electrified tables (from the loader) + shadow tables (which is again a functional thing not stored anywhere) + extension internal stuff.

2023-09-05 10:53 UTC, alco commented on docs/api/service.md
> -| Variable                                                        | Description
You can switch to the Rich diff view for this value to see it rendered and nicely diffed.

2023-09-05 10:53 UTC, alco commented on docs/api/service.md
> -| Variable                                                        | Description
![Screenshot from 2023-09-05 13-53-32](https://github.com/electric-sql/electric/assets/207748/47c64ceb-5e49-439e-973d-adfa5097ef0d)

2023-09-05 10:56 UTC, alco commented on components/electric/lib/electric/postgres/bytea.ex
> +    for <<bbbb::4 <- bin>>, into: "\\x", do: <<to_hex_digit(bbbb)>>
This function takes an Elixir value and produces a new value that is then sent to Postgres over the logical replication stream. So the encoded value needs to use Postgres syntax for bytea values, either Hex-encoded or Escape-encoded - https://www.postgresql.org/docs/current/datatype-binary.html#id-1.5.7.12.9.

That is, as long as we're using the text encoding for tuple data. I'm researching the possibility to switch to binary encoding but haven't made any progress to speak of on that front.

2023-09-13 12:59 UTC, alco commented on components/electric/lib/electric/postgres/extension/schema_loader.ex
> -  @callback electrified_tables(state()) :: {:ok, [table()]} | {:error, term()}
I get what you're saying with regards to splitting electrified user tables and our internal replicated tables + shadow tables of the former. But this here is a bit of a separate issue.

I remove `electrified_tables` from SchemaLoader because it had never been used, even before my addition of internal schema. If you do a code search with `main` checked out, you'll see that `electrified_tables()` is only ever called as `SchemaCache.Global.electrified_tables()` in the `Postgres.TcpServer` module. `SchemaCache.Global` simply delegates to `SchemaCache.electrified_tables()` which has its own bespoke `handle_call(:electrified_tables)` callback that doesn't mention `SchemaLoader`. So I treat this function as something specific to `SchemaCache` and not part of the `SchemaLoader` abstraction, similar to the `SchemaCache.relation/*` family of functions.

Let me know if you would like to preserve the `electrified_tables` function separately from what I implemented as `logical_publication_tables` here and:
* restore the `SchemaLoader` definition for it
* or just keep it local to `SchemaCache`

I'm thinking of defining a separate function to just return the replicated tables that are part of the internal schema and invoke that in `Postgres.TcpServer` in addition to `electrified_tables()`.

As for adjusting the abstraction implemented by `SchemaCache`, `SchemaLoader`, and `ShadowTableTransformation`, I'm not ready to take that on and that would be out of scope of this PR.

2023-09-14 11:31 UTC, alco commented
@magnetised address your feedback and implemented renaming proposals. I had to rebase on top of main to resolve conflicts but I didn't touch old commits. You can catch up with the changes made after your review by looking at https://github.com/electric-sql/electric/pull/386/commits/23d5b9df8f06a92a03c9795d11254d70a035a12e and later commits.

Thanks!

2023-09-19 09:31 UTC, magnetised approved these changes
thanks for addressing those concerns, some of which were slightly metaphysical.

2023-09-19 10:22 UTC, merged