chore(client): enable foreign_keys pragma on startup
electric-sql/electric pull request #397
Opened 2023-09-04 07:44 UTC by kevin-dp

Closes VAX-880.
No need to also enable the compensations because they are already enabled by the base migration:
- defined here with compensations set to 1: https://github.com/electric-sql/electric/blob/main/clients/typescript/src/migrators/schema.ts#L20
- and applied here: https://github.com/electric-sql/electric/blob/main/clients/typescript/src/migrators/bundle.ts#L38

2023-09-04 07:48 UTC, thruflo commented
N.b.: let's also remove the dupe calls from the examples. N.n.b: this may require another PR, i.e.: merge this, release library, then merge PR relying on it.

2023-09-04 07:59 UTC, kevin-dp commented
> N.b.: let's also remove the dupe calls from the examples. N.n.b: this may require another PR, i.e.: merge this, release library, then merge PR relying on it.

Yep. This makes me think, do we really want the examples to run against the latest published version?
Having the examples run against the ts client in the mono repo would simplify the worklow and simplify evolution of the examples together with the codebase. Because now, examples cannot be evolved until next release which is also cumbersome for our own testing purposes.

2023-09-04 08:03 UTC, thruflo commented
Yup, we had the same discussion whilst you were away. Another option was versioning the published docs and examples. No solution is ideal. We need to pick one and work with it.

2023-09-04 08:06 UTC, kevin-dp commented
> Yup, we had the same discussion whilst you were away. Another option was versioning the published docs and examples. No solution is ideal. We need to pick one and work with it.

Yes. If we want examples against latest published version, i would advocate for using a separate repo as it does not make much sense to put it in the mono repo. But i'm sure you've discussed this. We can catch up on this.

2023-09-04 08:09 UTC, balegas commented
If we start managing the next release PR through Linear or with a open PR here we can track pending changes. I suspect @icehaunter might have some input on this too.

2023-09-04 08:14 UTC, balegas requested changes

2023-09-04 08:14 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +    await this.adapter.run({ sql: 'PRAGMA foreign_keys = ON;' })
Note that foreign keys need to be enabled on a connection-basis. Even though this ensures foreign keys will be on, atm when they need to be. I think this should be done closer to when the connection is open.

Would also be nice that this configuration change would be done through a initial configuration step and not just ad-hoc command.

2023-09-04 10:57 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +    await this.adapter.run({ sql: 'PRAGMA foreign_keys = ON;' })
I think the right pattern is that there might be several things we want to configure on sqlite and setting foreign keys is one of those steps

2023-09-04 12:02 UTC, kevin-dp commented on clients/typescript/src/satellite/process.ts
> +    await this.adapter.run({ sql: 'PRAGMA foreign_keys = ON;' })
I see, if there are several things to configure should we be the ones doing it though?
If we will provide a flag for several configuration options we may as well just let programmers configure the DB directly. So maybe for now best to configure it with foreign_keys pragma because we need it, and if later we need additional options we can come back to this discussion.

2023-09-04 12:18 UTC, balegas commented on clients/typescript/src/satellite/process.ts
> +    await this.adapter.run({ sql: 'PRAGMA foreign_keys = ON;' })
I’m not thinking so far in the future. Just making sure we have a step in init that is to set default configs and fk is one of them and is not just an ad hoc statement somewhere

2023-09-04 12:18 UTC, kevin-dp commented
@balegas i moved it to the base electrify call as that is the earliest point where we can get to the user-defined database connection. Let me know if that is fine.

2023-09-04 12:35 UTC, thruflo commented
Just to chip in: I think that's a great place for it. That's where we take a standard conn and electrify it, which thus includes making sure it's got the right settings etc.

That said, perhaps you could extract to a `prepare(conn)` function that's called at the start of electrify *and* make that function overridable, in case drivers need custom setup?

2023-09-05 08:41 UTC, thruflo approved these changes
Looks good 👍

2023-09-05 08:50 UTC, balegas approved these changes

2023-09-05 08:50 UTC, balegas commented on clients/typescript/src/electric/index.ts
> +  prepare?: (connection: DatabaseAdapter) => Promise<void>
It would be better to document that if the dev overrides `prepare`, the default properties are expected to be set.

2023-09-05 08:57 UTC, kevin-dp commented on clients/typescript/src/electric/index.ts
> +  prepare?: (connection: DatabaseAdapter) => Promise<void>
Would you prefer if we always call the default prepare that sets the foreign key pragma, followed by calling the provided prepare function (if any)?

2023-09-05 09:05 UTC, balegas commented on clients/typescript/src/electric/index.ts
> +  prepare?: (connection: DatabaseAdapter) => Promise<void>
I thought of that but couldn't decide what's better, because the dev might now some stuff is already set or not. Let's not overdo it. documenting it is just fine. A long time before anyone overrides that function

2023-09-06 06:47 UTC, merged