Update util.js
electric-sql/electric pull request #482
Opened 2023-09-22 07:57 UTC by KhurramJalil

Fixes #480 

Updated utils.js to rename env variable from DATABASE_URL TO ELECTRIC_DATABASE_URL

2023-09-23 11:07 UTC, balegas requested changes
Tthank you for your kind contribution.

Note that all PRs need to include a changeset that you can generate with `pnpm generate` (see other PRs). I'm adding that to the instructions

2023-09-23 11:07 UTC, balegas commented on examples/starter/template/db/util.js
> +const DATABASE_URL = process.env.ELECTRIC_DATABASE_URL || DEFAULT_URL
There are more places in the code that load process.env.DATABASE_URL (see startElectric.js).
Note that the change need to be applied to the pre-generated examples.

2023-09-23 12:27 UTC, KhurramJalil commented
Thanks @balegas for reviewing and providing feedback.

I have committed more changes in the same PR with 11 files updated overall. Please review again and see if there is anything more to add.

2023-11-22 09:51 UTC, balegas commented
I'm closing thins without merging because of the new changes to the starter that are coming in. Thanks for picking this up and there will be more #good-first-issues in the future.

2023-11-22 09:51 UTC, closed without merging