feat(DAL)!: data type support for time-related types
electric-sql/electric pull request #537
Opened 2023-10-09 07:43 UTC by kevin-dp

This PR introduces data type support for PG's `time`, `timetz`, `timestamp`, `timestamptz`, and `date` type on the client*. It fixes VAX-841 and its subissues VAX-991, VAX-992, VAX-993, VAX-994, VAX-995, VAX-996, VAX-997.

In a nutshell, this PR introduces the following changes:
- Modifies the CLI to introspect the PG database via Electric's proxy
- Modifies the generator to parse the Prisma schema (we got by introspecting the PG DB) and extend the DMMF with the type attributes of fields
- Modifies the generator to expose PG column types on the generated Electric client
- Modifies DAL to transform JS date objects to SQLite strings encoding the date/time/timestamp based on the PG type information in the generated Electric client
- Modifies DAL to transform SQLite strings into JS date objects when reading from the SQLite DB based on the PG type information in the generated Electric client

This PR introduces breaking changes to the format of the generated Electric client.
The fields of a table now consist of a map from column name to PG column type whereas previously it was an array of column names.

*Although the client can handle the `timetz` type, it is not supported by Electric.

2023-10-09 08:47 UTC, alco commented on clients/typescript/test/client/generated/client/libquery_engine-darwin-arm64.dylib.node
Just noticed this. Probably accidental addition to Git? Otherwise, it would only work on macOS obviously.

2023-10-09 08:47 UTC, kevin-dp commented on clients/typescript/test/client/generated/client/libquery_engine-darwin-arm64.dylib.node
oops indeed! good catch

2023-10-17 11:24 UTC, alco approved these changes
LGTM! :+1: 

I have skipped the changes `generator/src` as those are beyond my level of understanding.

I would suggest @icehaunter to have a look at the TS code as well.

2023-10-17 11:24 UTC, alco commented on clients/typescript/src/client/conversions/sqlite.ts
> +  const parse = (v: any) => {
This can be defined as a module-level function. Any specific reason why it's a closure?

2023-10-17 11:24 UTC, alco commented on clients/typescript/src/client/conversions/sqlite.ts
> +function ignoreTimeZone(v: Date): Date {
We could instead conditionally call either `toISOString()` or `toString()` where appropriate. That would alleviate the need to do arithmetic on milliseconds and would fully offload timezone handling to the JavaScript runtime.

2023-10-17 11:28 UTC, alco commented on clients/typescript/src/client/conversions/sqlite.ts
> +  PG_FLOAT = 'FLOAT8',
I see you've fixed it in the next PR - https://github.com/electric-sql/electric/pull/542/commits/5fb56065273d5c64a279087887f39f5283c45e22#diff-0e52d53e61005f9ad23e9a24992613360a8f77cfaab3911d9809a2c759a79af8. So feel free to ignore my comment here.

2023-10-17 11:29 UTC, alco commented on clients/typescript/src/client/conversions/sqlite.ts
> +function ignoreTimeZone(v: Date): Date {
Since you've moved this code to another file in the next PR, it makes sense to make changes there (if you're planning to act on my comments here).

2023-10-23 15:51 UTC, kevin-dp commented on clients/typescript/src/client/model/builder.ts
> +  // TODO: in create, updateInternal, deleteInternal, and findWhere
This is a leftover todo. It has been implemented. Will remove.

2023-10-23 15:58 UTC, kevin-dp commented on clients/typescript/src/client/conversions/sqlite.ts
> +function ignoreTimeZone(v: Date): Date {
@alco  We can't use `toISOString()` or `toString()` for this purpose. We want to transform the provided Date object into the same date and time in UTC (e.g. input 3PM GMT+2 -> we want output 3PM UTC). However, `toISOString()` would return a string where it is `1PM UTC` and `toString` would leave it in GMT+2 time zone.

2023-10-24 07:34 UTC, alco commented on clients/typescript/src/client/conversions/sqlite.ts
> +function ignoreTimeZone(v: Date): Date {
Got it. My bad, I didn't fully grasp the intent here.

2023-10-25 09:56 UTC, davidmartos96 requested changes
Could we add a test to the `datatype.test.ts` file for the case of TIMESTAMP when a Date object with offset is provided?

```ts
test.serial('support timestamp type - input date with offset', async (t) => {
  const date = new Date('2023-08-07 18:28:35.421+05')

  const res = await tbl.create({
    data: {
      id: 1,
      timestamp: date,
    },
  })

  // ??????????
})
```

Should the function `ignoreTimeZone` return `18:28:35.421` here or `13:28:35.421`?

2023-10-25 10:21 UTC, kevin-dp commented
> Could we add a test to the `datatype.test.ts` file for the case of TIMESTAMP when a Date object with offset is provided?
> 
> ```ts
> test.serial('support timestamp type - input date with offset', async (t) => {
>   const date = new Date('2023-08-07 18:28:35.421+05')
> 
>   const res = await tbl.create({
>     data: {
>       id: 1,
>       timestamp: date,
>     },
>   })
> 
>   // ??????????
> })
> ```
> 
> Should the function `ignoreTimeZone` return `18:28:35.421` here or `13:28:35.421`?

When using `timestamp` (i.e. without time zone) we are storing the local date and time and anyone reading the timestamp should get the same date and time local to them. So if i'm in GMT+2 and it is 3PM and i store the timestamp then anyone reading it should also get 3PM in their timezone.

So when writing `const date = new Date('2023-08-07 18:28:35.421+05')` to the database as in your example, the timestamp everyone should read depends on the time zone of the user that wrote it to the database. I'm in GMT+2 so for me `'2023-08-07 18:28:35.421+05'` is `2023-08-07 15:28:35.421` local time and that is what gets stored in the DB. Hence, anyone reading my write will get `2023-08-07 15:28:35.421` in their timezone. That's exactly what `serialiseDate` (L65 in `src/client/conversions/sqlite.ts`) does: `ignoreTimeZone(new Date('2023-08-07 18:28:35.421+05')).toISOString()` results in `"2023-08-07T15:28:35.421Z"`.

2023-10-25 14:23 UTC, davidmartos96 commented
@kevin-dp 

> So if i'm in GMT+2 and it is 3PM and i store the timestamp then anyone reading it should also get 3PM in their timezone.

Ok, this statement and the following review comment is what created the confusion https://github.com/electric-sql/electric/pull/590#discussion_r1371301971.

We were under the assumption that the value stored in SQLite is the date in UTC, without the T and the Z. So for your example, 1PM UTC would be stored, and anyone would read 1PM UTC converted to the corresponding local times.

We thought TIMESTAMP in Postgres could be use to store a moment in time, same for any client, and interpreted always as UTC.
Source: https://stackoverflow.com/a/5876276
In particular, this statement from the Stackoverflow:
> Without a time zone as part of the value, the obvious default time zone is UTC, so it is rendered for that time zone.

2023-10-25 14:37 UTC, alco commented
> Without a time zone as part of the value, the obvious default time zone is UTC, so it is rendered for that time zone.

@davidmartos96 I don't think that characterisation of the `TIMSTAMP` type is correct. A better way to think about it and `TIMESTAMPTZ` is as follows:
* `TIMESTAMP` stores a timestamp as basically text. You can think of it as a photo of a wall clock (that also shows the date). No matter where in the world one looks at the photo, it'll show the same time regardless.
* `TIMESTAMPTZ` stores an objective moment in time: it's the same moment in time no matter where in the world one reads it. If this moment happened 2 hours ago for me in GMT+3, for someone in GMT+2 it happened 1 hour ago.

Here's an example `psql` session that demonstrates this distinction:
```
=# create table foo (id text primary key, t timestamp, tz timestamptz);
CREATE TABLE

=# set timezone to 'Europe/Brussels';
SET
=# show timezone
electric-# ;
    TimeZone     
─────────────────
 Europe/Brussels
(1 row)

=# insert into foo values ('1', now(), now());
INSERT 0 1
=# insert into foo values ('2', '2023-10-25 17:28:00', '2023-10-25 17:28:00');
INSERT 0 1
=# select * from foo;
 id │             t              │              tz               
────┼────────────────────────────┼───────────────────────────────
 1  │ 2023-10-25 16:27:48.505401 │ 2023-10-25 16:27:48.505401+02
 2  │ 2023-10-25 17:28:00        │ 2023-10-25 17:28:00+02
(2 rows)

=# set timezone to 'UTC';
SET
=# show timezone;
 TimeZone 
──────────
 UTC
(1 row)

=# select * from foo;
 id │             t              │              tz               
────┼────────────────────────────┼───────────────────────────────
 1  │ 2023-10-25 16:27:48.505401 │ 2023-10-25 14:27:48.505401+00
 2  │ 2023-10-25 17:28:00        │ 2023-10-25 15:28:00+00
(2 rows)
```

See how the values in `t` stay the same regardless of the client's time zone? We've implemented what we think is equivalent behaviour in DAL: the `TIMESTAMP` value is simply fed into `new Date(...)` as is, with no time zone conversion.

If what you're interested is a moment in time, rather than a snapshot of wallclock time, you should use `TIMESTAMPTZ`.

2023-10-25 14:50 UTC, davidmartos96 commented
@alco Thanks a lot! That really helps.
It was a misinterpretation with how Postgres works with those values. We don't have much experience with time operations in Postgres, we've always used dates stored as INT8 as milliseconds since Unix epoch.

I guess Timestamp is not the most clear name :sweat_smile:

2023-10-25 20:44 UTC, alco commented
> we've always used dates stored as INT8 as milliseconds since Unix epoch.

I think it's fair to say that this is almost exactly how Postgres stores TIMESTAMPTZ values internally: as an offset in microseconds since UNIX epoch which is defined in UTC.

2023-10-30 12:00 UTC, merged