Token Auth v1
electric-sql/electric pull request #54
Opened 2022-10-20 10:38 UTC by magnetised

just enough auth to require a real token in the authentication request, giving the ws server access to the user id

2022-10-20 11:07 UTC, define-null commented
https://github.com/electric-sql/electric/pull/55 is merged, please rebase to rerun e2e tests

2022-10-20 11:17 UTC, define-null commented
We do not seem to use mockserver anymore, lets remove it then.

2022-10-20 14:21 UTC, magnetised commented
@define-null see https://github.com/electric-sql/console/pull/7 for the console side of things, including new env var for the database_id stuff

2022-11-02 15:54 UTC, icehaunter commented on lib/electric/satellite/satellite_protocol.ex
> +            {%SatAuthResp{id: "server_identity"},
@magnetised, `database_id` is much better off being named `global_cluster_id` everywhere, now that we've merged the ID distinctions into console.

2022-11-09 11:01 UTC, magnetised commented on lib/electric/satellite/satellite_protocol.ex
> +        case Electric.Satellite.Auth.validate_token(database_id, token) do
good point. it's not like it's hard to get the cluster id at any point.

2022-11-09 11:33 UTC, magnetised commented on lib/electric/satellite/satellite_auth.ex
> +        Logger.error("authorization failed for #{database_id} with reason: #{inspect(reason)}")
have lowered the level for expired tokens, there was a way...

I've also updated the logger metadata to include client id and user id

2022-11-09 14:26 UTC, define-null requested changes
Looks good to me! There are some tests still failing both on ExUnit and E2E side.

2022-11-09 17:38 UTC, define-null commented
Failure on ws is caused by LSN recent change and it could be ignored.

2022-11-09 17:39 UTC, define-null approved these changes

2022-11-10 14:31 UTC, merged