Update auth configuration to match provisioning
electric-sql/electric pull request #66
Opened 2022-11-16 10:20 UTC by magnetised

https://linear.app/vaxine/issue/VAX-395/electric-auth-configuration-is-not-in-sync-with-console

2022-11-16 18:19 UTC, define-null commented on README.md
> +$ mix electric.gen.token my_user my_other_user
It would be nice to add a test for this functionality. Probably the simplest way - to add lux test, or make sure that we use gen.token generation when using `satellite_ws.lux` test

2022-11-16 18:26 UTC, define-null commented on integration_tests/single_dc/electric.exs
> +  regional_id: "local.dev.test-electric-db"
A bit confused now.. shouldn't it be the other way around? Let's say we have 2 electric instances in `US`, and 2 in `EU`. Then I would expect 2 electic instances in US to share same `regional_id`, but have different `instance_id`. At least that's how I think we discussed that :) @icehaunter

2022-11-17 10:45 UTC, magnetised commented on integration_tests/single_dc/electric.exs
> +  regional_id: "local.dev.test-electric-db"
I think I carried a misunderstanding through that conversation which led me astray, so I got the roles of the ids reversed.

2022-11-17 11:41 UTC, magnetised commented on integration_tests/multi_dc/electric.template
> +  regional_id: "region-{REGION}.test.electric-db"
@define-null is this right? my understanding of this test is that we're creating 3 distinct "regions" with a single instance in each one

2022-11-17 13:01 UTC, icehaunter commented on integration_tests/single_dc/electric.exs
> +  regional_id: "local.dev.test-electric-db"
@define-null is correct. `instance_id` is unique for every Electric instance within the cluster, `regional_id` will be shared by all electrics that connect to the Vaxine cluster (or, currently, single instance) in the region

Just a general heads-up tho, please treat the IDs as opaque (but having the desired properties), they are unlikely to have any structure you could rely upon.

2022-11-17 14:58 UTC, define-null commented
Test seems to be failing, because message about start_replication request was printed before `iex>3`. 
So expectations order does not match with the actual output.
We need to use `?+Regexp` syntax for that: https://github.com/hawk/lux/blob/master/doc/lux.md#interacting-with-a-shell

2022-11-17 14:59 UTC, define-null commented on integration_tests/multi_dc/electric.template
> +  regional_id: "region-{REGION}.test.electric-db"
Yes, that looks correct.

2022-11-17 15:30 UTC, define-null requested changes
Test seems to be failing, because message about start_replication request was printed before iex>3.
So expectations order does not match with the actual output.
We need to use `?+Regexp` syntax for that: https://github.com/hawk/lux/blob/master/doc/lux.md#interacting-with-a-shell

2022-11-17 20:22 UTC, define-null commented
Are you sure it fails at the start of the Vaxine? Cause I think it was actually in the ws client shell, on receiving of StartReplicationReq

2022-11-18 09:50 UTC, magnetised commented
> Are you sure it fails at the start of the Vaxine? Cause I think it was actually in the ws client shell, on receiving of StartReplicationReq

@define-null this was part of trying to get the integration tests to pass locally... my last attempt at eod yesterday actually produced my first successful run of the single_dc e2e tests, going to just prod at the multi_dc today in the background. 

no idea why the environments produce such different results.

2022-11-24 10:15 UTC, define-null approved these changes
Looks great to me!

2022-11-24 11:46 UTC, merged