chore(docs): Document the limitation of only the `public` schema being supported
electric-sql/electric pull request #675
Opened 2023-11-16 11:43 UTC by alco

2023-11-16 13:43 UTC, balegas requested changes
Thanks for accommodating my suggestion so quickly. 
Before we merge, I'm calling in @kevin-dp to also document the current limitations with table name collisions and any other issues that we've identified so far with regards to generator, and whatever (see VAX-1101 and VAX-1158).

2023-11-16 13:43 UTC, balegas commented on docs/usage/data-modelling/migrations.md
> +Only tables in the default schema named [`public`](https://www.postgresql.org/docs/14/ddl-schemas.html#DDL-SCHEMAS-PUBLIC) can be electrified at the moment.
```suggestion
Only tables in the default schema named [`public`](https://www.postgresql.org/docs/14/ddl-schemas.html#DDL-SCHEMAS-PUBLIC) can be electrified at the moment. We're working to lift this restriction.
```

2023-11-16 15:27 UTC, thruflo commented on docs/usage/data-modelling/migrations.md
> +In addition, we capitalise the first letter of table names.
Where do we capitalise the table name -- in the Postgres schema? In PG and SQLite? Just during the generation process? If not in the actual DDL schemas then perhaps better to rephrase as clashes being case insensitive, so myTable and MyTable clash.

2023-11-16 16:40 UTC, thruflo commented on docs/usage/data-modelling/migrations.md
> +In addition, we capitalise the first letter of table names.
Yup, so it's just internal to the client generation process. I suggest just saying the table name comparison is case insensitive.

2023-11-16 16:50 UTC, kevin-dp commented on docs/usage/data-modelling/migrations.md
> +In addition, we capitalise the first letter of table names.
That's not entirely true, as we can differentiate `foobar` from `fooBar` but not from `Foobar`.

2023-11-16 18:18 UTC, balegas commented on docs/usage/data-modelling/migrations.md
> +### Table names
```suggestion
### Table names

The client generator sanitises table names (because of an issue in an external library [link]). The rule of thumb is that the generator handles table names as case insensitive and removes any prefix of the table name that is not a letter. For example `_myTable`, `123myTable`, and `myTable` are all handled as the same table name. Electrifying tables that have a name clash causes errors during the generation.
```
- Please move this section to after the default schema section
- Do we have a link for the issue in the library?
- Is it true that it leads to an error? If not, it should.

2023-11-17 08:00 UTC, thruflo commented on docs/usage/data-modelling/migrations.md
> +In addition, we capitalise the first letter of table names.
My point is don't make it sound like we're changing your tablenames in the your actual database schema.

2023-11-20 10:28 UTC, kevin-dp commented on docs/usage/data-modelling/migrations.md
> +### Table names
Ok, i moved it and added the link to the issue. Yes, it leads to an error.

2023-11-20 10:32 UTC, kevin-dp reviewed
I applied Valter's suggestions, waiting for his approval to merge.

2023-11-22 08:29 UTC, balegas approved these changes

2023-11-22 08:32 UTC, merged