capacitor-sqlite runInTransaction now takes the lock.
electric-sql/electric pull request #677
Opened 2023-11-17 15:27 UTC by gregzo

This PR fixes a concurrency issue with the capacitor-sqlite database adapter. The mutex was previously only acquired in the `transaction` method, causing concurrency conflicts when calling `runInTransaction`.

Comments have been added to other public methods of the adapter in order to clarify the intended behaviour of each method. In effect, `run`, `execute` and `query` have ambiguous meanings depending on the layer (electric driver -> capacitor-sqlite -> native SQLite). It is therefore important to make sure that the methods as implemented correspond to what is expected of `electric`'s API.

2023-11-20 08:38 UTC, kevin-dp requested changes
Hi @gregzo, thanks for your PR!
I left some comments as i believe we also need to lock the `run` and `query` methods.

2023-11-20 08:38 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * @returns
No need for @param and @returns if there is no explanation for them.

2023-11-20 08:38 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * Executes a single SQLite statement, without taking the lock and without wrapping it in a transaction.
I would not say "without wrapping it in a transaction" because SQLite will always wrap standalone reads/writes in a transaction (cf. https://www.sqlite.org/lang_transaction.html):
> No reads or writes occur except within a transaction. Any command that accesses the database (basically, any SQL command, except a few [PRAGMA](https://www.sqlite.org/pragma.html#syntax) statements) will automatically start a transaction if one is not already in effect. Automatically started transactions are committed when the last SQL statement finishes.

2023-11-20 08:38 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * Executes a single SQLite statement, without taking the lock and without wrapping it in a transaction.
The `run` and `query` methods do not take the lock, i believe that is problematic as it may lead to `run`/`query` statements being interleaved in a concurrent transaction. For example, Satellite starts a transaction using `transaction` or `runInTransaction` and the lock is acquired. These methods are async, while waiting for some async call, JS may handle a call to `run`/`query`. Since these methods do not use the lock, they can now become interleaved within the transaction, which should not have been the case (they should be executed in a transaction of their own).

2023-11-20 08:38 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +    releaseMutex()
If `executeSet` fails, an error is thrown and `releaseMutex()` is not called.
This should be wrapped in a try..finally block:
```ts
const releaseMutex = await this.#txMutex.acquire()
try {
  const result = await this.db.executeSet(set, wrapInTransaction)
  const rowsAffected = result.changes?.changes ?? 0
  return { rowsAffected }
} finally {
  releaseMutex()
}
```

2023-11-20 08:38 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
>      // TODO: unsure how capacitor-sqlite populates the changes value (additive?), and what is expected of electric here.
Electric expects the value to be additive, i.e. to be the total number of changes.

2023-11-20 09:01 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * Executes a single SQLite statement, without taking the lock and without wrapping it in a transaction.
Perhaps it would be easier if we-rewrite the adapter to extend the generic adapter and override `runInTransaction` to execute the queries in batch using `executeSet`. Even better, i can perhaps modify the generic adapter to allow concrete adapters to provide an optional `executeSet` method; then the generic adapter can have a default implementation for `runInTransaction` that uses `executeSet` if provided and otherwise resorts to executing the queries manually one after the other in a transaction. That would considerably simplify the implementation of the capacitor-sqlite adapter.

2023-11-20 10:33 UTC, gregzo commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * Executes a single SQLite statement, without taking the lock and without wrapping it in a transaction.
Indeed, this is why I did not add locks to `query` and `run` methods. A recursive mutex could work though. But your suggestion to add an optional `executeSet` method sounds much better - transaction complexity will be handled higher up whilst retaining an opportunity for using better optimised driver APIs, 👍.

Should I wait for this enhancement of the generic adapter and rewrite the whole thing then?

2023-11-20 10:35 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * Executes a single SQLite statement, without taking the lock and without wrapping it in a transaction.
Yes, i will implement it now. And comment here when it is done such that you can rewrite on top of that branch.

2023-11-20 11:42 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * Executes a single SQLite statement, without taking the lock and without wrapping it in a transaction.
@gregzo Here you go: https://github.com/electric-sql/electric/pull/685 (still needs to be reviewed so is subject to change).

2023-12-06 10:39 UTC, gregzo commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +   * Executes a single SQLite statement, without taking the lock and without wrapping it in a transaction.
@kevin-dp That's beautiful, and very straightforward to implement thanks!

I've resolved all conversations since they're not relevant anymore - my last commit implements your BatchDatabaseAdapter.

I've rebased on `main` before, so it should be ready to merge.

2 things:

1. Capacitor-SQLite returns `numRowsAffected` within the `run` transaction result, but doesn't offer an API to retrieve that value separately. I've simply cached it at the adapter level. Is that safe? Risk of race condition?
2. I've implemented the `exec` method by calling the lib's `run` method, which is meant for single SQL statements and supports binding values. Can you please confirm that `exec` will never be called with multiple statements? In which case, I'd need to map it differently.

2023-12-12 08:57 UTC, kevin-dp requested changes
Thanks for your contribution, the PR looks good!
Just some minor things to fix.

2023-12-12 08:57 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/database.ts
> -export interface Database
Looks like the todo on L10 has become obsolete?

2023-12-12 08:57 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/test.ts
> +import { DatabaseAdapter as CapacitorSQLiteAdapater } from './adapter'
Typo in `CapacitorSQLiteAdapater` -> `CapacitorSQLiteAdapter`

2023-12-12 08:57 UTC, kevin-dp commented on clients/typescript/src/drivers/capacitor-sqlite/test.ts
> +    adapter as DatabaseAdapter,
Why do you need to cast the Capacitor sqlite DB adapter to the better-sqlite3 DB adapter?

2023-12-12 08:58 UTC, kevin-dp commented on .changeset/quick-rats-end.md
> +Capacitor sqlite DB driver re-imlemented to extend the new generic BatchDatabaseAdapter.
typo in "re-imlemented" -> "re-implemented"

2023-12-12 11:52 UTC, gregzo commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +    this.#rowsAffected = result.changes?.changes ?? 0
Looking at the Swift implementation, it appears that changes are tracked globally with `sqlite3_total_changes(sqlite3*);`

How it works:
1. The concrete swift imp of Database computes a changes diff by caching `UtilsSQLCipher.dbChanges()` before executing queries. I didn't check all methods in detail, but the two that we use certainly do (`runSQL` and `execSet`). **Database.swift:**
https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Database.swift
2. `UtilsSQLCipher.dbChanges` simply maps to `sqlite3_total_changes(sqlite3*);` **UtilsSQLCipher.swift:** https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Utils/UtilsSQLCipher.swift)

**`sqlite3_total_changes(sqlite3*)` doc:**
https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Database.swift

My understanding is that the current adapter implementation should be fine for `execBatch` (routed to `execSet`), but will indeed return 0 changes in a select query executed through the adapter's `exec`, which maps to `runSQL`, which will compute a diff of total changes of zero even if a previous update transaction did change rows.

If this is a problem, we can selectively route the adapter's `exec` imp to cap-sqlite's `query` instead of `run`, and not update the cached changes value for select queries. That should work fine. Should I give it a go? If so, which util can I use to determine if a query is a single select statement?

2023-12-12 11:54 UTC, gregzo commented on clients/typescript/src/drivers/capacitor-sqlite/test.ts
> +    adapter as DatabaseAdapter,
Not sure how that happened, good catch thanks!

2023-12-13 08:48 UTC, kevin-dp approved these changes

2023-12-13 10:27 UTC, gregzo commented on clients/typescript/src/drivers/capacitor-sqlite/adapter.ts
> +    this.#rowsAffected = result.changes?.changes ?? 0
As per our Discord discussion, the PR should be ready to merge. We've determined that `getTowsAffected()` returning 0 if called after a SELCT query is acceptable for now.

2023-12-13 11:16 UTC, merged