feat (toolbar):Debug toolbar
electric-sql/electric pull request #686
Opened 2023-11-20 15:59 UTC by paulharter

Checked out toolbar stuff into this new clean branch as many many messy changes of mind.

2023-11-29 14:04 UTC, kevin-dp requested changes
The toolbar looks good overall, I left some comments.
Seems that we're close to be able to merge this 👍

2023-11-29 14:04 UTC, kevin-dp commented on .changeset/spicy-beans-build.md
> +"@electric-sql/debug-toolbar": major
I believe this will bump the version of the toolbar to `1.0.0`. I think we want to keep it at `0.1.x` in which case this should be a patch bump.

2023-11-30 09:44 UTC, kevin-dp commented
Also, it seems you had an example usage of the toolbar in web-wa-sqlite example but you removed it?
Would be good to have an example where the toolbar is being used such that users can see the usage.

2023-12-04 12:25 UTC, paulharter commented on pnpm-workspace.yaml
> +  - 'toolbar'
I'm easy about this which ever seems best

2023-12-04 12:29 UTC, paulharter commented on toolbar/.prettierignore
> +dev-app/dist/
I keep the dev-app locally for development so this is useful

2023-12-04 12:31 UTC, paulharter commented on toolbar/README.md
> +import '@electric-sql/debug-toolbar/dist/index.cjs.css'
I couldn't get it to work otherwise - what would be the better way?

2023-12-04 12:36 UTC, paulharter commented on toolbar/README.md
> +Add web-wa-sqlite to the pnpm workspace by adding this line to `pnpm-workspace.yaml`
I've removed this section on development

2023-12-04 12:37 UTC, paulharter commented on toolbar/tsconfig.json
> +  "include": ["src/*", "custom.d.ts"]
I'm not sure - I'll try

2023-12-04 16:03 UTC, paulharter commented on toolbar/src/api/toolbar-typescript.ts
> +    return sat?.adapter.query(statement) ?? Promise.resolve([])
I've replaced this with an error message

2023-12-04 16:11 UTC, paulharter commented on toolbar/src/index.tsx
> +  const [dbNames, setDbNames] = useState([''])
React seems to want to know the type of the useState variable

2023-12-04 16:37 UTC, paulharter commented on toolbar/src/tabs.tsx
> +      case 'status':
I had something like this before but it upset React - It give hook errors something to do with when the JSX objects get rendered

2023-12-04 16:42 UTC, paulharter commented on toolbar/src/tabs/SQLTab.tsx
> +  function clearResults() {
makes sense

2023-12-04 16:45 UTC, paulharter commented on toolbar/src/tabs/SQLTab.tsx
> +                onClick={() => {
same

2023-12-04 16:46 UTC, paulharter commented on toolbar/src/tabs/SQLTab.tsx
> +                  setActive('query')
yup

2023-12-04 16:49 UTC, paulharter commented on toolbar/src/tabs/SQLTab.tsx
> +                  tabSize: 2,
I've set it to 4 everywhere

2023-12-04 16:52 UTC, paulharter commented on toolbar/src/tabs.tsx
> +      case 'status':
I've removed the status one

2023-12-04 16:57 UTC, paulharter commented on toolbar/src/tabs/SQLTab.tsx
> +    switch (active) {
done

2023-12-04 16:58 UTC, paulharter commented on toolbar/src/tabs/StatusTab.tsx
> +    if (dbName !== undefined) {
done

2023-12-04 17:25 UTC, paulharter commented on .changeset/spicy-beans-build.md
> +"@electric-sql/debug-toolbar": major
The checkpoint tool wanted to set it to 1.0.0 as its a first version - couldn't see a way to do a patch

2023-12-04 18:00 UTC, paulharter commented on clients/typescript/package.json
> +    "./satellite/mock": "./dist/satellite/mock.js",
I played with this - I added `export { MockRegistry } from './mock'` to `satellite/index.ts` to make it work

2023-12-06 11:41 UTC, paulharter commented
@kevin-dp I've pretty done everything as you suggest. A few notes:

I had to add export { MockRegistry } from './mock' to satellite/index.ts to get the import to work without the addition export is the package

I couldn't refactor the tab components as you suggested, I had tried to do this before, its something to do with when react expands out the JSX, it generates react hook errors.

I have moved the whole thing for now - but we can do this later

I haven't added back the toolbar in an example as I want to do this an other step once there is a published toolbar package to refer to properly. But I have checked that this will works ok in the web example. I have also added a non compiled `util.ts` script to tidy away the code to add the toolbar.

2023-12-12 09:04 UTC, kevin-dp commented on clients/typescript/package.json
> +    "./satellite/mock": "./dist/satellite/mock.js",
yep that's the way to do it 👍

2023-12-12 10:09 UTC, kevin-dp requested changes

2023-12-12 10:09 UTC, kevin-dp commented on toolbar/src/index.tsx
> +export default function addToolbar(toolbarApi: ToolbarInterface) {
I would not use a default export here because it makes the code that imports it less clear:
```ts
toolbar.default(toolbar.clientApi(...))
```
In the code above, it's not clear what `toolbar.default` does.
I would argue that this is more clear:
```ts
toolbar.addToolbar(toolbar.clientApi(...))
```

And if using regular imports instead of dynamic imports it becomes even better:
```ts
import { addToolbar, clientApi } from '...'
addToolbar(clientApi(...))
```

2023-12-12 10:09 UTC, kevin-dp commented on toolbar/util.ts
> +export function addToolbar() {
Let's not use dynamic import and instead have `addToolbar` take 1 argument which is satellite or electric.

2023-12-12 11:40 UTC, paulharter commented on toolbar/util.ts
> +export function addToolbar() {
I couldn't get this to work - the typing of the client makes it want to pulll in generated types

so I left it with `addToolbar(globalRegistry)`

2023-12-12 11:40 UTC, paulharter commented on toolbar/src/index.tsx
> +export default function addToolbar(toolbarApi: ToolbarInterface) {
removed all the dynamic imports

2023-12-12 11:41 UTC, paulharter commented on toolbar/package.json
> +    "build": "rm -rf ./dist && node builder.js && tsc --emitDeclarationOnly --outDir dist && cp ./util.ts ./dist/util.ts",
I've removed this in favour of static imports

2023-12-12 11:42 UTC, paulharter commented on toolbar/README.md
> +import ('@electric-sql/debug-toolbar/util').then(util => {util.addToolbar()});
I have removed all the dynamic imports

2023-12-12 11:44 UTC, kevin-dp commented on toolbar/util.ts
> +export function addToolbar() {
Try `ElectricClient<unknown>` otherwise you could do `ElectricClient<any>` that should make TS happy.

2023-12-12 11:50 UTC, paulharter commented on toolbar/src/api/toolbar-interface.ts
> +  resetDB(dbName: string): void
done

2023-12-12 14:27 UTC, kevin-dp commented on toolbar/src/api/toolbar-typescript.ts
> +export class ToolbarTypescript implements ToolbarInterface {
This is a typescript package so no need to put `Typescript` in the class name nor in the filename.
Can we rename this file to `toolbar.ts` and this class to `Toolbar` please. Also, we can rename the `toolbar-interface.ts` file `interface.ts`

2023-12-13 12:12 UTC, paulharter commented on toolbar/src/api/toolbar-typescript.ts
> +export class ToolbarTypescript implements ToolbarInterface {
I was anticipating that this will could be used with the rust client too - but happy to remove the language specification if you prefer.

2023-12-13 12:14 UTC, kevin-dp commented on toolbar/src/api/toolbar-typescript.ts
> +export class ToolbarTypescript implements ToolbarInterface {
Yes please :-)

2023-12-13 12:15 UTC, kevin-dp commented on toolbar/README.md
> +Then in your code after calling `electrify` pass the electric client into addToolbar:
addToolbar should be `addToolbar`

2023-12-13 12:16 UTC, kevin-dp commented on toolbar/README.md
> +const electricClient = await electrify(conn, schema, config)
we usually just call it `electric`

2023-12-13 12:51 UTC, paulharter commented on toolbar/src/api/toolbar-typescript.ts
> +export class ToolbarTypescript implements ToolbarInterface {
@kevin-dp have changed as you suggest now

2023-12-13 12:54 UTC, paulharter commented
I think this might be ready now - I've made to readme changes you suggested

2024-01-03 10:54 UTC, kevin-dp commented on .github/workflows/toolbar_tests.yml
> +      - run: pnpm run build
I don't see the change? i still see `pnpm run build`

2024-01-03 10:54 UTC, kevin-dp commented on clients/typescript/src/satellite/index.ts
> +export { MockRegistry } from './mock'
Could you move it down to the block of exports.
It's in the block of imports which confused me, i first thought it was an import.

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/.gitignore
> +dev-app
`dev-app` and `package.dev.json` are not needed. You have them locally because of the way how you tested this but normally one doesn't have this directory and file so no need to put it in `.gitignore`.

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/.prettierignore
> +dev-app/src/generated/
same here, `dev-app` is not needed.

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/Makefile
> +	pnpm install --frozen-lockfile
indentation is off, we usually indent it like this for targets containing several commands:
```
deps:
  pnpm install --frozen-lockfile
  make -C ...
```

And like this for targets with a single command:
```
tests: CI=true pnpm run test
```

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/src/api/interface.ts
> +export interface Interface {
Can we give this a more descriptive name?
I would be fine with `ToolbarInterface`, `IToolbar`, or other descriptive names.

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/src/index.tsx
> +    let names = api.getSatelliteNames()
We don't reassign `names` so better to use `const`.

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/src/index.tsx
> +  const toolbar_div = document.createElement('div')
we use camelCase in TS -> `toolbarDiv`

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/src/index.tsx
> +  const toolbar_root = ReactDOM.createRoot(
`toolbarRoot`

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/src/tabs.tsx
> +  name: 'status' | 'db' | 'sql',
this type is being used in several places.
Let's make a type alias for it.

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/src/tabs.tsx
> +  function handleClick(
`handleClick` does not use the event and just calls `setActive`. Do we really need `handleClick`? It seems like we can get rid of this function and just pass `secActive` into `TabItem` if we change the type of `handleClick` in `TabItem` to:
```ts
handleClick: (
    name: 'status' | 'db' | 'sql'
  ) => void
```

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/src/tabs/SQLTab.tsx
> +    let cmd = code
Why is this variable needed, `cmd` is not reassigned. Could use `code` instead of `cmd`.

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/test/api.test.ts
> +  const dbDescription = {} as DbSchema<any>
Could type the variable such that we don't have to cast the value `const dbDescription: DbSchema<any> = {}`

2024-01-03 10:54 UTC, kevin-dp commented on components/toolbar/test/api.test.ts
> +test('identity', async () => {
this tests `getSatelliteNames`, we should also test the other public methods:
```ts
getSatelliteStatus(name: string): ConnectivityState | 'Not found'
resetDB(dbName: string): Promise<void>
queryDB(dbName: string, statement: Statement): Promise<Row[]>
```

2024-01-04 16:20 UTC, balegas commented
I see there is still activity here. Let's not leave it hanging.

2024-01-17 16:07 UTC, paulharter commented on components/toolbar/test/api.test.ts
> +  const dbDescription = {} as DbSchema<any>
I get an error if I do this - {} isn't actually sufficient to be a DbSchema<any> so I'm forcing it

2024-01-18 15:42 UTC, kevin-dp commented on components/toolbar/test/api.test.ts
> +  const dbDescription = {} as DbSchema<any>
I see, we can leave it like this then

2024-01-31 16:40 UTC, paulharter commented on components/toolbar/src/tabs.tsx
> +  function handleClick(
neat - I wasn't sure this would work

2024-01-31 17:16 UTC, paulharter commented
@kevin-dp I have done all the changes you suggested except the additional tests, and I have tested it manually against 0.0.9 with the web example.

Can we merge this now as I'm not really coding now and don't have time to think about how to set up the extra tests and Valter wanted this in for next week?

2024-02-01 08:24 UTC, kevin-dp reviewed
Thanks for addressing my comments!
I have two nitpicks that would be nice to fix:
- `components/toolbar/Makefile` indentation is still off
- `clients/typescript/src/satellite/index.ts` export is still on the block of imports

You tested the toolbar manually on 0.9 and it seems to work which is great. However, we don't have unit tests for some public methods and that would be a blocker for me as that means we will have to go and manually test the toolbar on every release. These are the untested public methods:
```ts
getSatelliteStatus(name: string): ConnectivityState | 'Not found'
resetDB(dbName: string): Promise<void>
queryDB(dbName: string, statement: Statement): Promise<Row[]>
```

I will let @balegas decide whether we merge without the tests or not.

2024-02-01 08:24 UTC, kevin-dp commented on components/toolbar/src/tabs.tsx
> +  handleClick: (name: 'status' | 'db' | 'sql') => void,
you can use `TabName` here as the type for `name`

2024-02-01 08:48 UTC, balegas commented
Hi @paulharter,
It feels like the unit tests suggestion are important. I understand that this will probably not help a lot with browser implementation, but for the sake of completeness let's make those tests.

This PR is dragging for too long. It's very near.

Best,

2024-02-14 15:07 UTC, paulharter commented on components/toolbar/src/tabs.tsx
> +  handleClick: (name: 'status' | 'db' | 'sql') => void,
done

2024-02-14 15:24 UTC, paulharter commented
@kevin-dp @balegas I've added the extra api tests now

2024-04-24 14:41 UTC, msfstef commented
I've modified the debug toolbar slightly, added a couple more APIs for the connection status (toggle on/off) and an experimental shapes tab for viewing active shapes.

The last one uses a private field from the satellite implementation so before developing further I'll open a PR to expose some shape subscription information from the Satellite client for the debug toolbar to use safely.

I've also done an ugly inlining of CSS into the debug toolbar to make the DX better (now only need to dynamically import and call `addToolbar(electric)`) - will improve that over time but I had already spent too much time on CSS bunding, postprocessing, and TS errors...

@kevin-dp can you have another look so we can potentially merge this?

2024-04-25 14:02 UTC, kevin-dp approved these changes
Looks good to me!
Left some minor comments.

2024-04-25 14:02 UTC, kevin-dp commented on components/toolbar/package.json
> +    "zod": "^3.23.3"
Does the toolbar need Zod?
If yes, this version is problematic as it may give type errors in the generated client, let's use `3.21.1` instead.

2024-04-25 14:29 UTC, msfstef commented on components/toolbar/Makefile
> +deps:
Not sure what you mean? it's tab indented (similar to the generator Makefile)

2024-04-30 07:50 UTC, merged