Pin Zod to 3.21.1 to avoid code generator bug in client
electric-sql/electric pull request #700
Opened 2023-11-27 20:44 UTC by fooware

## Summary
As discussed on Discord with @kevin-dp, it appears that the dependencies for Zod can pull in a version that causes the generated client to contain invalid casts.

![image](https://github.com/electric-sql/electric/assets/984279/e37012af-5192-4a2a-ab4f-29783dd37d6e)

The issue in Zod + Prisma can be found here:
https://github.com/colinhacks/zod/issues/2184
https://github.com/chrishoermann/zod-prisma-types/issues/98

## Background

For us, the problem manifests itself by adding any kind of basic table relationship and generating a client. Indeed, it appears to also happen in this example code created by a third party:
https://github.com/KyleAMathews/vite-react-router-electric-sql-starter/tree/main

In both that example, and our internal code, it is enough to comment out any relationships and the generated code is fine, or rather doesn't contain the code blocks that are causing the issues.

![image](https://github.com/electric-sql/electric/assets/984279/9a7c2429-19cd-407b-b9cc-27f3094a32e7)

Patching the packages lock file in both cases to resolve Zod to 3.21.1 (as suggested in the linked issue threads) fixed the issue for both our code and the third-party example.

![image](https://github.com/electric-sql/electric/assets/984279/e3a17b0a-6f2d-4b31-ba19-f2c8149cf3f2)
![image](https://github.com/electric-sql/electric/assets/984279/7779f8e5-d07d-47d8-9244-8911ca955c1b)

## Temporary Workaround

Since we are using PNPM we could achieve the same result by adding a forced version override to our root package.json file:
```
  "pnpm": {
    "overrides": {
      "zod": "3.21.1"
    }
  }
```

## Suggested Fix

This PR pins the version of Zod to 3.21.1 which is the latest version that did not cause the issue. Hopefully, this will mean that new users will get a local package lock file that resolves Zod to 3.21.1 and a working client generator. That last part is a bit hard for me to verify locally though.

## Caveat

I have only updated the TypeScript Client and the Client Generator, but there are at least two places in this mono repo that explicitly reference higher versions of Zod:
- e2e/satellite_client - `^3.21.4`
- examples/linearlite - `^3.22.2`
- 
I was not comfortable downgrading those dependencies since I do not know _why_ they require a higher version.

2023-11-28 09:10 UTC, kevin-dp reviewed
Hi @fooware, thanks for your contribution!
The e2e tests and linearlite should indeed also be pinned to version 3.21.1 of Zod.
The fact that they are using a higher version of Zod is an accident.

Could you also generate a changeset for this PR please?
To do that, run `pnpm changeset` at the root of the monorepo.

2023-11-28 12:01 UTC, fooware commented
> Hi @fooware, thanks for your contribution! The e2e tests and linearlite should indeed also be pinned to version 3.21.1 of Zod. The fact that they are using a higher version of Zod is an accident.

Done.
 
> Could you also generate a changeset for this PR please? To do that, run `pnpm changeset` at the root of the monorepo.

Done, but please make sure I did it correctly.

Please note that I didn't rebuild any packages here. I assume that a build server handles that during release?

2023-11-29 11:27 UTC, kevin-dp requested changes

2023-11-29 11:27 UTC, kevin-dp commented on .changeset/happy-lobsters-type.md
> +"@core/electric": patch
The changeset is not correct. It patches all packages but your PR only touches the typescript client (i.e. `electric-sql`) and the generator (i.e. `@electric-sql/prisma-generator`). It does not touch Electric (`@core/electric`) neither does it touch the starter (`"create-electric-app": patch`).

So the changeset should look like this:
```
---
electric-sql": patch
@electric-sql/prisma-generator": patch
---

Pin Zod to version 3.21.1
```

You probably accidentally selected all packages instead of only the changed packages.

2023-11-29 16:49 UTC, fooware commented on .changeset/happy-lobsters-type.md
> +"@core/electric": patch
I assumed it only listed the ones it detected changes in so I accepted the defaults.

I’ll push an updated one tomorrow.

2023-12-04 22:04 UTC, fooware commented on .changeset/happy-lobsters-type.md
> +"@core/electric": patch
@kevin-dp, any feedback? I assume I shouldn’t resolve this thread?

2023-12-05 15:08 UTC, kevin-dp commented on .changeset/happy-lobsters-type.md
> +"@core/electric": patch
> @kevin-dp, any feedback? I assume I shouldn’t resolve this thread?

We will need a bit more time to see if we can provide a fix for this under the hood such that we don't need to pin the version of Zod to a specific version for all Electric projects. This will require some changes in the generator. I'm hoping to look into it tomorrow and ideally push a fix for it tomorrow. We will keep you posted here.

2023-12-12 13:21 UTC, alco commented
@kevin-dp @samwillis does https://github.com/electric-sql/electric/pull/727 address this issue?

2023-12-12 21:39 UTC, samwillis commented
Hey @fooware,

Thanks for the help with this, we fixed the issue in #727 with your tip off for the upstream bug report. We will be publishing a version with this fixed this week.

2023-12-12 21:39 UTC, closed without merging