fix(client) Various fixes to run generator and starter scripts on windows
electric-sql/electric pull request #737
Opened 2023-12-07 17:50 UTC by samwillis

Included fixes:
- Prefix zod type generator provider with node for exe on windows so that its run with node
- Conditionally escape quotes in docker command on windows, this has to be conditional as it breaks Posix
- Execute the pg-migrations command with npx not yarn

The fixes to the starter are also applied to the web-wa-sqlite example.

---

### To test:

```sh
git clone git@github.com:electric-sql/electric.git && cd electric
git checkout samwillis/windows-fix
pnpm install
cd clients/typescript
pnpm build && pnpm pack
cd ../../examples/web-wa-sqlite/
npm uninstall electric-sql
npm uninstall @prisma/client @electric-sql/prisma-generator prisma  # These are no longer required but we haven't updated the example yet 
npm install ../../clients/typescript/electric-sql-0.8.1.tgz
npm backend:up
npm db:migrate
npm client:generate
npm start
```

If for some reason the client won't build on windows, this is a ready made build from this branch: 
[electric-sql-0.8.1.tgz](https://github.com/electric-sql/electric/files/13635086/electric-sql-0.8.1.tgz) - just try it with the web-wa-sqlite *in this branch*

2023-12-07 22:43 UTC, balegas requested changes
The last issue I found is in `"start": "yarn electric:check && SERVE=true npm run build"`
Windows shell does not support using env vars that way.  This `$env:SERVE="true";`works, but maybe there is a better way.

Thanks for working on this

2023-12-07 22:43 UTC, balegas commented on clients/typescript/src/cli/migrations/migrate.ts
> +      provider      = "node ${escapePathForString(provider)}"
This worked

2023-12-08 09:15 UTC, alco commented on examples/starter/template/db/migrate.js
> +const proc = spawn("npx", args, { stdio: ['inherit', 'pipe', 'inherit']  })
Correct me if I'm wrong, but when you pass the `shell` option, the first argument to `spawn()` should be a string that includes all arguments. Basically, a one-liner you would type into your shell by hand.

2023-12-08 15:13 UTC, samwillis commented on examples/starter/template/db/migrate.js
> +const proc = spawn("npx", args, { stdio: ['inherit', 'pipe', 'inherit']  })
Looks like Node handles this itself, if there are arguments and shell=true then it constructs the command by joining the array of args with a space:

https://github.com/nodejs/node/blob/8cdb7cae98468efee222727ad9a4096e415f3ef6/lib/child_process.js#L620-L645

2023-12-12 08:04 UTC, kevin-dp approved these changes
LGTM!

2023-12-12 08:13 UTC, merged