feat(electric): Create permissions protobuf definitions and write validation logic
electric-sql/electric pull request #768
Opened 2023-12-18 15:34 UTC by magnetised

2024-01-15 16:18 UTC, alco approved these changes

2024-01-15 16:18 UTC, alco commented on components/electric/lib/electric/satellite/permissions/transient.ex
> +    table = :ets.new(name, [:bag, :public, read_concurrency: true])
Why not use `named_table` and avoid the need to call `table_ref`?

2024-01-15 16:18 UTC, alco commented on components/electric/lib/electric/satellite/permissions/transient.ex
> +    |> Stream.map(fn m -> {role_grant, hd(m)} end)
```suggestion
    |> Stream.map(fn [transient] -> {role_grant, transient} end)
```

2024-01-16 09:49 UTC, magnetised commented on components/electric/lib/electric/satellite/permissions/transient.ex
> +    table = :ets.new(name, [:bag, :public, read_concurrency: true])
Premature optimisation! Have regretted it since doing it, will revert

2024-01-22 11:48 UTC, icehaunter requested changes
These are some questions, most imporant stuff has been talked about in calls

2024-01-23 14:48 UTC, magnetised commented on components/electric/lib/electric/satellite/permissions/scope.ex
> +  @callback scope_id(state(), root :: relation(), Changes.change()) :: id() | nil
you know, theoretically yes. Can't imagine a use case for that but there probably is one somewhere. I think this would be covered by the `USING scope_path` clause of the assign statement, so if you only wanted one of those paths to be included in the perms scope, you would specify it in the USING clause of your assign. We haven't implemented the `USING` bit yet, but it's in there.

2024-01-23 15:09 UTC, magnetised commented on components/electric/lib/electric/satellite/permissions.ex
> +  1. An update that moves a row between authentication scopes is treated like an update in the
yeah. good point. is it a delete? i suppose if the move-in is an insert then it follows that the move-out is a delete, but I'm not sure that the two things are mirrored like that, at least it's not completely obvious to me. i would perhaps expand the checks so that this fk update/scope move requires update and delete perms on the original scope and insert on the new, because you have to have the perms to update the row, this update implies a removal from the original scope and an insert into the new. but that feels excessive. 

perhaps we should raise this and get a consensus -- my gut is saying that it's not (clearly, definitely) a delete. like you're not removing a row from the db you're moving one and the insert check is there to assert that you have equivalent permissions on the new scope.

perhaps we should change it from {update, insert} to {update, update} 

the options are:

1. {update, insert} - as is
2. {delete, insert} - what you're suggesting
3. {[update, delete], insert} - my first suggestion above
4. {update, update} - my last suggestion. 

I mean there are some combinations I haven't included there if you want to be exhaustive, but let's not eh.

i'll raise it tomorrow in the scopes call

2024-01-23 15:10 UTC, magnetised commented on components/electric/lib/electric/satellite/permissions.ex
> +      |> Map.new(&classify_roles/1)
this is not the hot path, it's optimising for the hot path. it only gets run when permissions change, so not "rarely" but nothing like "for every tx coming from pg"

2024-01-24 14:58 UTC, magnetised commented on components/electric/lib/electric/satellite/permissions.ex
> +  1. An update that moves a row between authentication scopes is treated like an update in the
for the record, the final decision was option 4: {update, update}

2024-04-09 11:54 UTC, icehaunter approved these changes
OK, seems good! Great work

2024-04-22 10:09 UTC, alco approved these changes
Brilliant!

I could only come up with a handful of nitpicks, sorry to disappoint.

2024-04-23 08:54 UTC, magnetised commented on protocol/satellite.proto
> +        string column = 2;
Good point. I'll address after merging down into a single pr

2024-04-23 08:58 UTC, magnetised commented on protocol/satellite.proto
> +    Roles roles = 4;
Because I patch in the serialised `Roles` struct which is maintained per-user so it keeps the symmetry between the rules and roles. But yes, it is a bit redundant.

2024-05-22 16:02 UTC, msfstef commented on docs/api/ddlx.md
> +  TO (projects, member');
```suggestion
  TO (projects, 'member');
```

2024-05-22 16:04 UTC, msfstef commented on docs/api/ddlx.md
>  This is similar to the grant above. It lets a project member read comments on issues in a project, but the comments table doesn't itself have a foreign key pointing to the project so the `USING` para
nit: `USING` no longer part of the spec (?)

2024-05-29 13:32 UTC, magnetised commented on docs/api/ddlx.md
>  This is similar to the grant above. It lets a project member read comments on issues in a project, but the comments table doesn't itself have a foreign key pointing to the project so the `USING` para
yeah, good point. there is a thing in these docs where we talk about how things *will* work, once they're done. But I'm seeing that all the eventualities come with a cost which is that people will just use the docs as is and then be confused when it doesn't work. so, I've taken this `using` ref out, as you suggest and added a (probably too long) para about scope resolution and fks.

2024-05-30 09:25 UTC, msfstef commented
created small PR to add `ELECTRIC_FEATURES` to the client CLI for ease of use https://github.com/electric-sql/electric/pull/1304

draft PR for linearlite multi-project + multi-user stacked on top of this for ad-hoc testing https://github.com/electric-sql/electric/pull/1303

2024-08-06 13:41 UTC, closed without merging

2024-08-06 13:41 UTC, KyleAMathews commented
👋 we've been working the last month on a rebuild of the Electric server over at a temporary repo https://github.com/electric-sql/electric-next/

You can read more about why we made the decision at https://next.electric-sql.com/about

We're really excited about all the new possibilities the new server brings and we hope you'll check it out soon and give us your feedback.

We're now moving the temporary repo back here. As part of that migration we're closing all the old issues and PRs. We really appreciate you taking the time to investigate and create this improvement!