Fix `/ws` 400 error in the `web-wa-sqlite` starter
electric-sql/electric pull request #787
Opened 2023-12-28 03:35 UTC by ickynavigator

## Issue
- The example repo failed to sync up with other clients/devices
- There was a `/ws` 400 error thrown in the browser (and in the docker logs) <img width="1920" alt="image" src="https://github.com/electric-sql/electric/assets/46367335/551f47fa-67ba-456d-ae35-e24b0f780809">

ps: I wasn't sure if the migrations were meant to be added to git so I just ignored it (please let me know if I should undo that)
pps: I made a typescript version of this example and would be fine with sending in a PR if it's needed

2023-12-28 08:10 UTC, kevin-dp requested changes
Thank you for contributing to Electric!
The 400 error code is because the version of Electric and the version of the TypeScript client didn't match. I'm assuming you were running e.g. version 0.8.2 of the client against Electric 0.7 or vice-versa. Your PR bumps both to version 0.8 which is good.

Regarding vite, @samwillis has an open PR https://github.com/electric-sql/electric/pull/786 that introduces vite for this example.

2023-12-28 08:10 UTC, kevin-dp commented on examples/web-wa-sqlite/.gitignore
> +.electric_migrations*
No need to add this to `.gitignore`, this is a temporary file that gets deleted normally. It would only remain if the client generation failed but there is a pending PR which is about to get merged that will always delete the folder (unless passing an flag that explicitly tells not to delete it on error).

2023-12-28 08:10 UTC, kevin-dp commented on examples/web-wa-sqlite/backend/compose/.envrc
> +export APP_NAME=electric
The app name should be `web_wa_sqlite`.

2024-01-11 13:23 UTC, closed without merging

2024-01-11 13:27 UTC, balegas commented
As Kevin explained the issue was caused by a mismatch between client and server versions. Examples use specific versions and we only update them for new releases and all at once.

Thanks for engaging.

2024-01-11 15:40 UTC, ickynavigator commented on examples/web-wa-sqlite/.gitignore
> +.electric_migrations*
ahh thanks. that should ix it then

2024-01-11 15:41 UTC, ickynavigator commented
thanks @balegas !!!