chore(docs) Docs for new CLI and Starter
electric-sql/electric pull request #820
Opened 2024-01-10 14:12 UTC by samwillis

2024-01-10 14:18 UTC, thruflo commented on docs/api/cli.md
> +| <span className="no-wrap">`--proxy`</span><br/><span className="no-wrap">`-p`</span><br/>`ELECTRIC_PROXY` | `<url>` | Provides the url to connect to Electric's database proxy.<br /> Defaults to <sp
Note that it's essential to document the need for the username to be `prisma`. As per the clashing docs I just merged.

2024-01-10 14:22 UTC, thruflo commented on docs/api/cli.md
> +Connect with psql to the ElectricSQL PostgreSQL proxy.
It's the `Migrations proxy`. And I would say: Start an interactive PSQL session with Postgres, connecting via the Electric [Migrations proxy](...).

2024-01-10 14:22 UTC, thruflo commented on docs/api/cli.md
> +The `psql` command accepts a number of arguments for specifying the Postgres Proxy to connect to, the main one being:
Migrations proxy.

2024-01-10 14:22 UTC, thruflo commented on docs/api/cli.md
> +Configure the ports used by the ElectricSQL sync service.
Electric sync service.

2024-01-10 14:24 UTC, thruflo commented on docs/api/cli.md
> +This command allows you to run a subcommand substituting arguments configured with Electric environment variables. It also makes all Electric configuration environment variables available to the subc
I don't understand from this what this does. And what kind of command would you run? Can the description be clearer and can you provide a real example?

2024-01-10 14:25 UTC, thruflo commented on docs/api/cli.md
> +This command allows you to run a subcommand substituting arguments configured with Electric environment variables. It also makes all Electric configuration environment variables available to the subc
Sorry, I see you have further below. I leave the commend here though because I didn't read ahead that far before being confused. You may want to bring the example higher up.

2024-01-10 14:28 UTC, thruflo commented on docs/api/cli.md
> +| <span className="no-wrap">`--with-migrations`</span> | `<command>` | Specify a command to generate migrations. With this option the work flow is:<br /> 1. Start new ElectricSQL and PostgreSQL conta
I see the link to the with-config section here, which has the usage example of with-migrations. However, I think maybe it deserves more prominence here where the generate command is.

Ideally I'd like to see a section explaining the local-only-first flow.

2024-01-10 14:29 UTC, thruflo commented on docs/api/cli.md
> +1. Start new ElectricSQL and PostgreSQL containers
As per comment in the generate command above, it's great to show this usage but I think we could highlight the benefit and principle more. I.e.: this allows you to develop with Electric without running the backend and without sync. That's a big deal but the lede isn't clear here.

2024-01-10 14:31 UTC, thruflo commented on docs/examples/notes/running.md
> +`npm un backend:start` uses Docker Compose to start a connected Postgres and Electric. To run the Electric sync service on top of an *existing* Postgres instead, make sure that:
`npm run ...`

2024-01-10 16:15 UTC, samwillis commented
I've moved the new caution block that was added today out of the table as it's currently broken on the main site. It seems to work with a local test, but not on a preview or live build:

<img width="922" alt="image" src="https://github.com/electric-sql/electric/assets/31130/400b4cca-8571-488d-b9c8-de2cc8d6da8a">

2024-01-10 17:38 UTC, thruflo requested changes
See the comment about local-only-first mode.

One additional suggestion is that perhaps we can add a note or info box to the QuickStart (or wherever we best explain the development workflow), highlighting the existence of local-only-first mode.

Perhaps that's a blog post as well. So e.g.: a `:::info` note in the QuickStart, linking to a blog post explaining the concept, linking to the `### Local-only-first mode` section that I sketched out in my PR comment here.

What do you think? I know I'm labouring it but I think it's on us to explain the concept to really land the value of the work.

2024-01-10 17:38 UTC, thruflo commented on docs/api/cli.md
> +Normally the `generate` command expects to be run against an Electric and Postgres where you already have a full schema installed. However you may want to work in a *"local only first"* way, generati
This is great but I think it can be tightened up one more notch by focusing the message on "running the backend or not". I.e.:

```md
### Local-only-first mode

Normally, when you develop or deploy apps with Electric, you want to run the backend services (Postgres and Electric) in order to sync data. As a result, it's natural that the `generate` command expects you to be running the backend services during your build step.

However, it's also quite common in development or with an early version of an app, not to need data sync enabled yet. Either because you're just working on the interface or because your app starts off local-only and you plan to enable sync later. This makes the overhead of running (and potentially deploying) the backend services quite high, given that you're running them just to support the generate command in your build step.

As a result, we provide a special `--with-migrations` mode for the generate command that allows you to generate the type safe client just from your migrations, without having to run the backend services yourself. Specifically what the `--with-migrations` option does is it tells the generate command to spin up a temporary Postgres and Electric itself, apply your migrations from scratch, generate the type safe client and then tear Electric and Postgres down. All of which happens automatically in the background for you.

We call this approach "local-only-first", in the sense that it allows you to develop local-only and then progressively enable sync later on, as and when you want to.

<then the command examples etc. from below>

As you can see from the steps above, the backend is started, your migrations are applied, the type-safe client is generated and then everything is torn down and cleaned up for you. Allowing you to develop local-only-first and then run the backend services only when you actually want to enable sync.
```

2024-01-10 19:22 UTC, samwillis commented on docs/api/cli.md
> +Normally the `generate` command expects to be run against an Electric and Postgres where you already have a full schema installed. However you may want to work in a *"local only first"* way, generati
Good call, I've push an update with that

2024-01-15 08:46 UTC, alco commented on docs/api/cli.md
> +#### Local-only-first mode
There's a fair amount of duplication between this section and the one right below it:
![image](https://github.com/electric-sql/electric/assets/207748/49afee3e-0719-46fe-9878-b74ed014ee30)

Maybe leave high-level description here, in the `Local-only-first mode` intro and leave the technical details about the underlying commands for the next section?

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
>  npx electric-sql generate [--service <url>] [--proxy <url>] [--out <path>] [--watch [<pollingInterval>]]
This synopsis does not match the list of options below.

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +| <span className="no-wrap">`--with-migrations`</span> | `<command>` | Specify a command to run migrations against a blank postgres in order to create a client. [See details below](#generate---with-m
```suggestion
| <span className="no-wrap">`--with-migrations`</span> | `<command>` | Specify a command to run migrations against an ephemeral database in order to create a client. [See details below](#generate---with-migrations) |
```

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +All [environment variables for configuring the Electric sync service](./service.md#configuration-options)  are passed through to the service if they are found prefixed with `ELECTRIC_`.
That anchor is no longer there.

```suggestion
All [environment variables for configuring the Electric sync service](./service.md)  are passed through to the service if they are found prefixed with `ELECTRIC_`.
```

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +All [environment variables for configuring the Electric sync service](./service.md#configuration-options)  are passed through to the service if they are found prefixed with `ELECTRIC_`.
> if they are found prefixed with `ELECTRIC_`

I'm not sure what this means. Only variables prefixed with `ELECTRIC` are passed through? Does the developer need to add the `ELECTRIC_` prefix to the variables documented on the `service.md` page?

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +| <span className="no-wrap">`--database-url`</span><br/><span className="no-wrap">`-db`</span><br/>`ELECTRIC_DATABASE_URL` | `<url>` | PostgreSQL connection URL for the database. |
It's not clear what database this is referring to. Is this option mutually exclusive with `--with-postgres`? If not, how do the two interact?

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +The `start` command accepts a single argument:
```suggestion
The `stop` command accepts a single argument:
```

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +| <span className="no-wrap">`--remove`</span> | Remove the containers and volumes from Docker.
```suggestion
| <span className="no-wrap">`--remove`</span> | Remove the Docker containers and volumes previously created by `start`.
```

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +Start an interactive PSQL session with Postgres, connecting via the Electric [Migrations proxy](../usage/data-modelling/migrations.md#migrations-proxy).
Does this require `psql` to be installed? If yes, let's mention that.

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +The `psql` command accepts a number of arguments for specifying the Migrations proxy to connect to, the main one being:
I find this structure very confusing: this sentence mentions "a number of arguments", the table below contains a single one. One has to go through the full list of environment variables and see in the description of each var which command it applies to. That's inconvenient. Moreover, it's not clear how one should map the env var name to a command-line flag.

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +One of the main use cases for this command is running migrations against your Electric Postgres Proxy using the configuration specified locally.
Throughout this page, it's called `Migration proxy`, `Migrations proxy` and now `Electric Postgres Proxy`. I think we need to standardize on a single name so as not to confuse people.

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +    "db:migrate": "npx electric-sql with-config \"npx pg-migrations apply --database {{ELECTRIC_PROXY}} --directory ./db/migrations\"",
How about this to improve readability?

```suggestion
    "db:migrate": "npx electric-sql with-config 'npx pg-migrations apply --database {{ELECTRIC_PROXY}} --directory ./db/migrations'",
```

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +In addition to those specified below, all standard Electric sync service environment variables are available for setting prefixed with `ELECTRIC_`. These are then passed though to the sync service st
```suggestion
In addition to those specified below, all standard Electric sync service environment variables are available for setting prefixed with `ELECTRIC_`. These are then passed though to the sync service started with the [`start`](#start) command. See a [full list of environment variables here](./service.md).
```

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +    example="http://electric.mydomain.com"
```suggestion
    example="https://electric.mydomain.com"
```

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +## Environment Variables
I can't seem to guess the ordering criterion used for variables in this section. Let's order them alphabetically? Or at least by logically related groups. Currently, `ELECTRIC_SERVICE` is followed by two unrelated vars before `ELECTRIC_SERVICE_HOST`.  Then, after 7 other env vars comes `ELECTRIC_HTTP_PORT`.

2024-01-15 14:49 UTC, alco commented on docs/api/cli.md
> +#### `ELECTRIC_PROXY`
Perhaps `ELECTRIC_PG_PROXY` is a more suitable name, to be consistent with its constituent `PG_PROXY_PORT` and `PG_PROXY_PASSWORD` variables?

2024-01-16 14:01 UTC, alco approved these changes

2024-01-18 11:07 UTC, merged