chore (client): detach electrification from connection
electric-sql/electric pull request #828
Opened 2024-01-15 13:47 UTC by kevin-dp

This PR detaches electrification of a database from connecting to the Electric sync service.
Authentication credentials still need to be passed when calling `electrify` because the client ID is used for generating tags when snapshotting the oplog.

Note that the ts-client will complain if you try to sync a shape before being connected to the Electric sync service.

The flow is as follows:

```ts
const electric = await electrify(conn, schema, config)
await electric.connect()
// only now can one sync shapes
```

This PR unblocks https://github.com/electric-sql/electric/issues/491 as it enables using Electric in local-only mode as one can essentially never call `electric.connect`. In local-only mode, one never syncs any shape.

2024-01-17 15:14 UTC, kevin-dp commented
As discussed with @balegas, i modified `electrify` to make the `AuthConfig` optional.
If an `AuthConfig` is provided it should only contain a client ID.
If no client ID is provided, the Satellite process generates one.

```ts
const electric = await electrify(conn, schema)
```

After electrifying the database, we can now connect to Electric. Now is the time to provide the JWT:
```ts
const token = /* fetch your JWT somehow */
await electric.connect(token)
```

2024-01-18 13:26 UTC, icehaunter requested changes
LGTM, with one nitpick and one type signature question to finish the cleanup

2024-01-18 13:26 UTC, icehaunter commented on clients/typescript/src/satellite/process.ts
> +    await this._setAuthState({ clientId: clientId }) //, token: authConfig.token })
nitpick: `await` on a non-promise expression + comment leftovers

2024-01-18 13:26 UTC, icehaunter commented on clients/typescript/src/client/model/client.ts
> +  async connect(token: string): Promise<ConnectionWrapper> {
I don't see a reason to keep this indirection around (other than code compat, but we're alpha, right?). This promise was returned from `Satellite#start` because the pre-connect method was async, and connection itself is separately async, and we wanted to return from the setup immediately instead of waiting for a full connection. This signature makes no sense here on an explicit `connect` method, so IMO `ConnectionWrapper` type can be deleted

2024-01-18 13:29 UTC, kevin-dp commented on clients/typescript/src/client/model/client.ts
> +  async connect(token: string): Promise<ConnectionWrapper> {
Yep i had left it like this to make the minimal required changes. But indeed this no longer makes sense so i will fix this, thanks!

2024-01-18 13:33 UTC, kevin-dp commented on clients/typescript/src/satellite/process.ts
> +    await this._setAuthState({ clientId: clientId }) //, token: authConfig.token })
Thanks, i think this slipped back in on a merge conflict that i wrongly resolved

2024-01-18 13:46 UTC, samwillis commented
@kevin-dp Is it worth adding a matching `.disconnect()`?
(you may already have discussed this with @balegas)

2024-01-18 13:47 UTC, kevin-dp commented
@icehaunter thanks for your review! I adressed your issues and am therefore re-requesting your review
@samwillis yep we discussed this with @balegas, a `disconnect` method is planned but as a separate PR.
The plan is to make the connectivity state read-only (currently you can disconnect by putting it on `disconnected`) and introduce the `disconnect` method.

2024-01-18 14:03 UTC, icehaunter approved these changes

2024-02-05 16:29 UTC, alco commented on .changeset/chilled-avocados-compare.md
> +"electric-sql": patch
This looks like a breaking change to me.

People with existing apps will start getting type errors about unknown `token` field in the auth config. And their app will stop syncing until they add an explicit `.connect()` call. Or am I missing something?

2024-02-06 07:48 UTC, kevin-dp commented on .changeset/chilled-avocados-compare.md
> +"electric-sql": patch
Yes that's true. But i believe the philosophy with versioning for now is to indicate compatibility with Electric, not to indicate breaking changes?

2024-02-06 12:04 UTC, alco commented on .changeset/chilled-avocados-compare.md
> +"electric-sql": patch
That's correct.

I'm worried about the documentation burden of this change. Not only the API reference, but the Quickstart and maybe a few other pages need to be updated.

Looking at our examples, most of them have `electric-sql` pinned to `"^0.7.0"` so they won't be affected even if users update the deps. Only `web-wa-sqlite` has `electric-sql` pinned to `"^0.9.0"`. Perhaps we should update that version requirement to just `"0.9.0"` to avoid unexpected updates.

@balegas @samwillis We need to have a way to notify users about such changes that require action on the user's part. Any ideas? I think printing a warning into the browser console would be the surest way for a developer to notice that their app no longer works as before.

2024-02-14 18:50 UTC, samwillis approved these changes
LGTM

I think @alco is right about a warning. Maybe we set a timeout for 500ms after an electric client is initiated, and if `connect` isn't called emit a warning.

2024-02-15 14:01 UTC, kevin-dp commented
@samwillis @alco Not sure about adding a timer to our code to signal that the user may have missed this breaking change. Up till when will we keep that timer in our codebase? Till the next minor release?

2024-02-15 14:20 UTC, kevin-dp commented
@samwillis as pointed out by @alco in a private conversation, the auth configuration that is passed to the `electrify` call no longer accepts a token. So for those cases where we break it they will see a type error. So there should be no need for an additional warning. Can i proceed and merge? @samwillis @alco

2024-02-15 14:25 UTC, alco commented
@kevin-dp Sounds good :+1:

2024-02-15 18:48 UTC, samwillis commented
Go for it 👍

2024-02-21 09:19 UTC, merged