feat!: shape subscriptions
electric-sql/electric pull request #899
Opened 2024-01-29 09:22 UTC by icehaunter

Main feature of this commit is the support for arbitrary FK traversal when
requesting shape subscription. This makes previous "multiple full table"
requests invalid, because when a table is requested without following
it's FKs, we cannot guarantee FK consistency of the client's data view.

When requesting a shape, the server will do it's best to fulfill "at
least" the requested shape: if there are any outgoing FKs from the
tables mentioned in the requested include tree, those will also be
traversed and sent to the client.

Another important change is introduction of "additional" transactions:
those are non-timestamped transactions that the server sends to the
clients when they need to see some data they haven't seen before, but
those rows weren't affected directly. They are tied to a "real"
transaction that caused this additional data to appear by a reference
number, so the client may wait for the full view of the data if it so
chooses. Only one-to-many relations are followed with a lag like that,
many-to-one relations will always be present in the transaction itself
to ensure FK consistency on the client.

This functionality is supported by a sent rows FK graph that's
maintained per client in the WebSocket process. It may be persisted, but
should probably have a similar lifetime to WAL cache window, since
that's the current boundary for client reconnection.

2024-01-30 13:34 UTC, magnetised approved these changes
`magic()` - awesome stuff.

2024-01-30 13:55 UTC, icehaunter commented on clients/typescript/src/satellite/merge.ts
> +  // TODO: Does deleting on GONE make sense at all?
That's addressed already by some chats w/ @balegas, and I'm indeed going to expand upon this in further issues

2024-01-30 14:03 UTC, icehaunter commented on clients/typescript/src/util/types.ts
> -  primaryKey?: boolean
Unfortunately

2024-01-30 14:03 UTC, icehaunter commented on components/electric/.tool-versions
> +erlang 25.3
Mis-addition. I work with electric folder as VSCode root and missed that it got added

2024-01-30 14:58 UTC, alco commented on components/electric/lib/electric/postgres/extension/functions.ex
> +      relpath = Path.relative_to(path, @template_dir_path)
No need for `@external_resource`. SQL template files are loaded at runtime, so a content change in any of them doesn't affect module compilation.

2024-01-30 14:58 UTC, alco commented on components/electric/lib/electric/satellite/protocol/state.ex
> +          move_in_data_fun: fun(),
```suggestion
          subscription_data_fun: fun() | nil,
          move_in_data_fun: fun() | nil,
```

2024-01-30 14:58 UTC, alco commented on components/electric/lib/electric/satellite/protocol.ex
> +  @spec query_move_in_data(Shapes.subquery_actions(), State.t()) ::
```suggestion
  @spec query_move_in_data(actions(), State.t()) ::
```

2024-01-30 14:58 UTC, alco commented on components/electric/lib/electric/satellite/protocol.ex
> +      # This is `InitialSync.query_subscription_data/2` by default, but can be overridden for tests.
`fun` here actually holds `InitialSync.query_after_move_in/4`.

2024-01-30 14:58 UTC, alco commented on components/electric/lib/electric/utils/gen_stage.ex
> +defmodule Electric.Utils.GenStage do
It's quite confusing to see `Utils.GenStage` and `GenStage` mentioned in close proximity. How about changing the module name to `Electric.Utils.GenStageHelpers`?

2024-01-30 14:58 UTC, alco commented on components/electric/lib/electric/satellite/serialization.ex
> +      ops: [commit_op],
It is somewhat hacky to put the `commit_op` here with the expectation that trans-ops will be added to the state inside `Enum.reduce()` calling `serialize_changes()` below, and then top it off with prepending `begin_op`. It threads the knowledge about the exact contenst of the `state.ops` field between here and the implementation of `serialize_change/2`.

Also, compared to, for example, the handling of ops in the `serialize_trans()` function above (compare line 67 to 86), the order of operations is theorder of `changes` reversed. Does the order within a transaction not matter?

2024-01-30 14:58 UTC, alco commented on components/electric/lib/electric/satellite/ws_server.ex
> +    {msgs, _actions, state} =
Why not assert that `[] = _actions`?

2024-01-30 15:02 UTC, icehaunter commented on components/electric/lib/electric/satellite/serialization.ex
> +      ops: [commit_op],
Not for a "fake" transaction like this. This is just data being sent - maybe it's better just not modelled within a txn message at all

2024-01-30 15:02 UTC, icehaunter commented on components/electric/lib/electric/satellite/ws_server.ex
> +    {msgs, _actions, state} =
%{}, but yeah, good point

2024-01-30 15:07 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol/state.ex
> +          move_in_data_fun: fun(),
no, they need to be set always. We can even `@enforce_keys` on them - state is built as a new object exactly once in `Electric.Satellite.WebsocketServer.init/1`

2024-01-30 17:23 UTC, icehaunter commented on components/electric/lib/electric/replication/shapes/change_processing.ex
> +      when (is_map(record_or_id) or is_tuple(record_or_id)) and layer.direction != :first_layer and
That's only partially true. Point here is that if `layer.direction == :first_layer`, the fourth argument MUST be null, otherwise it MUST NOT be null. This is only achievable with these two guards, and I can say it guarded my errors a couple of time while writing tests so I'll insist on keeping that

2024-01-30 20:17 UTC, icehaunter commented on clients/typescript/src/util/types.ts
> +  primaryKey?: number | false
practically, it forces a stronger check than `!== undefined`, to make sure only positive numbers are relevant. This is a bit hazy though and I can simplify down to `undefined

2024-01-31 11:06 UTC, alco approved these changes
Brilliant! :rocket: 

Thanks for including an extensive test coverage for the new functionality!

It would be helpful to have brief, high-level module docs added to the new modules to help the reader orient themselves within the shape procesing data flow. It's a lot of new code to take in, so I can't claim I was able to wrap my head around it.

2024-01-31 11:06 UTC, alco commented on components/electric/test/electric/satellite/subscriptions_test.exs
> +        refute_receive {^conn, %SatOpLog{}}, 100
This might be nitpicky but DB queries in tests and their subsequent processing by Electric's logical replication consumer, especially when running on CI, may take a while. A timeout of 1000 to confirm that a message **is not** received would look more convincing here.

2024-01-31 11:10 UTC, alco commented on components/electric/lib/electric/satellite/protocol/state.ex
> +          move_in_data_fun: fun(),
Sorry, I know this is a nitpick, it's just they are set to `nil` by default in the `defstruct` definition above. Perhaps Dialyzer has figureed out that they are never `nil` when they are referenced in other code. I wonder why it sometimes misses cases like this but then at some point starts complaining about them when some other, seemingly unrelated code, is modified.

2024-02-01 14:44 UTC, icehaunter commented on components/electric/lib/electric/replication/shapes/change_processing.ex
> +    process_next_layers(layer, reduction(state, graph: graph), event.record, event: :new)
Made it nice and pipy

2024-02-01 14:46 UTC, icehaunter commented on components/electric/lib/electric/replication/shapes/change_processing.ex
> +  def add_to_graph(graph, %Layer{} = layer, own_id, parent_id)
Yeah, you're correct, it was a leftover from previous iterataions

2024-02-01 14:51 UTC, icehaunter commented on components/electric/lib/electric/replication/shapes/change_processing.ex
> +      case record_or_id do
I disagree on this, let's leave it at that - it's only 2 places in the code and they don't share their args

2024-02-01 14:57 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol/state.ex
> +          move_in_data_fun: fun(),
because you cannot "not" set nil as default in these struct definitions, but Dialyzer assumes you'll set a real value when you first build it. So if your function return type is `t()` and you forget this assignment it'll complain

2024-02-01 14:58 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol/state.ex
> +          move_in_data_fun: fun(),
There is no "sane" compile-time default to be had here, it's just a value that should never be nil after the record is constructed

2024-02-01 15:01 UTC, icehaunter commented on components/electric/lib/electric/satellite/protocol.ex
> +      {:subscription_insertion_point, ^ref, xmin} ->
Sure, will rename, but the logic is exactly the same, hence the same name

2024-02-01 15:02 UTC, icehaunter commented on components/electric/test/electric/satellite/subscriptions_test.exs
> +        refute_receive {^conn, %SatOpLog{}}, 100
No, good point, I definitely agree on a refute

2024-02-01 15:08 UTC, icehaunter commented on components/electric/lib/electric/replication/shapes/querying.ex
> +      |> Enum.reject(&(is_nil(&1) or &1 == ""))
It's literally 3 element list, stream buildup is more expensive than iterating that 2 times

2024-03-19 09:41 UTC, magnetised commented on clients/typescript/src/satellite/client.ts
> +        this.inbound.maxUnackedTxs = resp.unackedWindowSize ?? 30
Can we move this magic number to a named constant

2024-03-19 13:53 UTC, icehaunter commented on components/electric/lib/electric/replication/shapes.ex
> +  @type action_context :: {actions :: subquery_actions(), source_tx_ids :: [non_neg_integer()]}
True but that's too many places to change, I'll do a refactor later, it doesn't feel impactful here

2024-03-19 14:08 UTC, icehaunter commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +      for id <- txn_ids, do: {{{client_id, id}, :_}, [], [:"$$"]}
Great catch!

2024-03-19 14:52 UTC, alco commented on components/electric/lib/electric/satellite/client_reconnection_info.ex
> +  def clear_all_data(client_id) do
> > needs to be made private
> 
> Why so, given it's explicitly used in `protocol.ex` right under the comment you've corrected? We need to clear all data for a client who connects outside the WAL window, and I don't see a way to make it private here.

I knew I saw it used outside! For some reason, when I checked out your branch on my machine and did a code search in VSCode, it only showed uses in this module. Probably an indexing glitch. Sorry for the noise.

Regarding your other points, I'm not trying to start a debate here but just wanted to clarify what I meant. None of it requires any action in this PR, but I think these arguments still hold:

We _should_ be mindful of concurrent processes acting on shared data structures when we add such data structures in the code. The code written now may live on for years when other features will be added to it and different people will be modifying it. If a lot of logic may break when called by concurrent processes, doesn't that sound like a problem? Elixir gives us tools to delineate parts of the code that need to be serialized (gen servers) vs parts of the code that can be run concurrently (thanks to immutable data).

If a public function is vulnerable to data races when called from concurrent processes, it cannot be called an implementation detail of the module. Disregarding my earlier comment about making `clear_all_data()` private, I would appreciate a comment on it explaining that concurrent access is not a concern for us because each client_id is guaranteed to have a single websocket process for it thanks to the use of ClientManager.


> > reconnection info is truly local for each client
> 
> It is truly local, but it needs to persist reconnects (even disregarding Electric restarts), so it can't be in the WS process state. [...] given the next step of putting all this info into a shared persistent cache (for restarts), I felt like implementing a set of ETS tables is a better option that leaves us with a more explicit API surface for a cache.

Fair point. With my take I was pointing out the fact that a different structuring of data in the code could remove the "concurrency problem" entirely. And keeping client-local state local to the client isn't creating potential performance bottlenecks where an ordered table has to be scanned repeatedly for the same `client_id` while other client IDs are less frequently touched. But that's a concern for a later time.

2024-03-19 18:22 UTC, davidmartos96 commented on clients/typescript/test/satellite/process.test.ts
> +test.only('additional data will be stored properly', async (t) => {
It looks like a `.only` remained in the code :)

2024-03-20 14:11 UTC, magnetised requested changes
found missing `:global` modifiers on `:binary.replace/3`

2024-03-20 14:11 UTC, magnetised commented on components/electric/lib/electric/replication/shapes/querying.ex
> +  defp quote_escape(str), do: [?', :binary.replace(str, "'", "''"), ?']
```suggestion
  defp quote_escape(str), do: [?', :binary.replace(str, "'", "''", [:global]), ?']
```

2024-03-20 14:11 UTC, magnetised commented on components/electric/lib/electric/replication/shapes/querying.ex
> +      escaped = :binary.replace(context[:user_id], "'", "''")
```suggestion
      escaped = :binary.replace(context[:user_id], "'", "''", [:global])
```

2024-03-20 14:16 UTC, icehaunter commented on clients/typescript/test/satellite/process.test.ts
> +test.only('additional data will be stored properly', async (t) => {
Thanks!

2024-03-20 14:16 UTC, magnetised approved these changes

2024-03-20 14:55 UTC, merged