chore: publish versioned tags to DockerHub [VAX-539, VAX-541]
electric-sql/electric pull request #95
Opened 2023-01-26 15:49 UTC by icehaunter

- Fill the version field of `mix.exs` from closest git tag
- Use that version to tag docker images
- Push images to Dockerhub if a tag is pushed

2023-01-30 10:09 UTC, define-null requested changes
Tests are failing, otherwise minor comments and suggestions.

2023-01-30 10:09 UTC, define-null commented on integration_tests/common.mk
> +	export ELECTRIC_VERSION_IN_DOCKER?=$(shell git describe --abbrev=7 --tags --always --first-parent)
I was about to suggest to move `ELECTRIC_VERSION` that you introduced in main makefile to use here, but noticed that it's located in `integration_tests/common.mk`. It feels to me that current mk structure needs refactoring and we would benefit by moving common shared stuff to corresponding files, to be reused by integration tests and ordinary workflow.

2023-01-31 18:44 UTC, icehaunter commented on .github/workflows/ci.yml
> +          fetch-depth: 0
Done

2023-01-31 18:45 UTC, icehaunter commented on .buildkite/docker-image.yml
> +      - docker tag "$${ELECTRIC_IMAGE_NAME}:$${ELECTRIC_VERSION}" "$${ELECTRIC_IMAGE_NAME}:latest"
Done

2023-01-31 18:45 UTC, icehaunter commented on .github/workflows/ci.yml
> +      - run: |
Done

2023-01-31 18:49 UTC, icehaunter commented on integration_tests/common.mk
> +	export ELECTRIC_VERSION_IN_DOCKER?=$(shell git describe --abbrev=7 --tags --always --first-parent)
Not relevant any more since this variable has been removed due to removing volumes altogether

2023-02-06 20:43 UTC, define-null requested changes

2023-02-06 20:43 UTC, define-null commented on integration_tests/satellite_client/Makefile
>  	rm -rf .yarn*
Would be nice to know the motivation why we switch from yarn to pnpm here, taking into account that yarn is used in typescript-client. If yarn is no longer used, I suggest we drop yarn from here, and drop yarn.lock file.

 Would it make sense to switch to pnpm in typescript-client as well?

2023-02-06 20:43 UTC, define-null commented on Makefile
> +	git describe --abbrev=7 --tags --always --first-parent
There are too many places in this PR where we use this call. Please define a variable for that.

2023-02-06 20:43 UTC, define-null commented on integration_tests/Makefile
> +	make -C satellite_client local-build
Huh? When running this on local machine the build will pick whatever version of the node is available locally, and later on will try to use those build deps to run in the docker container with potentially different version.

2023-02-06 20:43 UTC, define-null commented on .tool-versions
> +elixir 1.13.4-otp-24
I guess this file should be in .gitignore instead?

2023-02-06 20:43 UTC, define-null commented on mix.exs
> +          :error -> {:ok, "0.0.0-" <> String.trim(version)}
Perhaps just return :error here as well? Otherwise a bit too much unambiguity

2023-02-06 20:47 UTC, icehaunter commented on .tool-versions
> +elixir 1.13.4-otp-24
No, this unambiguously specifies required tooling for the project that a lot of tools honor, including asdf. I checked this in intentionally, since other contributors will face issues running e2e tests with differing versions as I did when my OTP25-compiled local `_build` was mounted into the `elixir-client` docker container which failed to use them

2023-02-06 20:50 UTC, icehaunter commented on integration_tests/Makefile
> +	make -C satellite_client local-build
I think this solves the git checkout issue, how do you suggest splitting this for local and ci? Also deps can be shared between node versions no problem generally, we don't use node-compiled stuff I don't think.

How about keeping it local and specifying the node in `.tool-versions` so that asdf can shim the correct version for this folder?

2023-02-06 20:51 UTC, icehaunter commented on mix.exs
> +          :error -> {:ok, "0.0.0-" <> String.trim(version)}
I actually use this case for local version as a default fallback. This is meant ao that we can always run just in case, to not interfere with dev experience

2023-02-06 20:54 UTC, icehaunter commented on integration_tests/satellite_client/Makefile
>  	rm -rf .yarn*
I've found pnpm to be more consistent and less finicky when using more complex or git-based dependencies. Switching it was an attempt to fix that weird yarn behavior where it complained about commit sha not being present on amongst the checkoutable refs of typescript client somehow despite it being totally there. Pnpm fixed it :)

2023-02-06 20:58 UTC, define-null commented on .tool-versions
> +elixir 1.13.4-otp-24
Our Readme explicitly specifies the versions that Electric can be build with. 
https://github.com/electric-sql/electric#pre-reqs

There could be many, and different developers (myself included) might want to use different Erlang/Elixir versions or even custom builds with extra options depending on the use-case. Specifying versions like that, which could interfere with local environment is not a very friendly move. 

In my view if developer want to be safe - they would build inside docker, otherwise they are expected to know what they are doing and can use whatever version they prefer. Also take into account that no internal makefile/docker tooling is using this file as a source of truth, so eventually it will diverge.

2023-02-06 21:01 UTC, define-null commented on integration_tests/Makefile
> +	make -C satellite_client local-build
In order to split this for local and for CI, we should provide targers to do that. Previously the build would work nicely with `build` target, which is what CI would use. And in case developer will want to build locally they can use `local-build` target. If that is not enough and some use-cases are not nicely handled - let's discuss them.

2023-02-06 21:02 UTC, define-null commented on integration_tests/satellite_client/Makefile
>  	rm -rf .yarn*
Sure, I just highlight that we need some more cleanup here then, to get rid of `yarn.lock` and other places where yarn is used.

2023-02-06 21:04 UTC, define-null commented on mix.exs
> +          :error -> {:ok, "0.0.0-" <> String.trim(version)}
I understand why we may want a **single** fallback, but i'm not sure it's great to have **2** different fallbacks.. 
I personally would rather have none. If that's a wrong version - we don't want to push it anyway. It will make a reasoning easier as well.

2023-02-06 21:14 UTC, icehaunter commented on .tool-versions
> +elixir 1.13.4-otp-24
I kinda don't agree. If you want to play around with differing local versions - sure, `asdf install local elixir 1.14` and off you go. This will also update this file which wi get reflected in the git status so you will remember it.
I also didn't find the "it should be built in docker" statement to hold while working on this and the neighboring PRs. As I've said in the comment up this chain, right now the `_build` directory is mounted straight into the Docker container running a pinned 1.13 Elixir w/ OTP24, which fails to run the code (`mix run --no-deps-check`). I don't like that I have to delete my local _build folder to make sure it's all compiled with a proper version, so having a file, which, given a consistent tooling (asdf) normalizes the development environment for everyone seems like a clear benefit to me.
With regards to "multiple places" - sure, we also have it in multiple makefiles and readme. I don't see that being such a big deal, we're not updating language versions every day to worry that much about it. And this fill will get updated as soon as you run asdf command, so you don't have to keep it up to date manually.

2023-02-06 21:24 UTC, define-null commented on .tool-versions
> +elixir 1.13.4-otp-24
> this unambiguously specifies required tooling for the project that a lot of tools honor, including asdf.
This does not hold. Asdf is just one of the many tools, Erlang or Elixir may be installed locally or through other tools, 
that does not use this file.

> as I did when my OTP25-compiled local _build was mounted into the elixir-client docker container which failed to use them
One should never use same beams inside and outside docker when environment is not fixed. If you want to compile elixir-test in container different mix env should be used, to make sure that they do not mix. This PR does not solve this problem.

> This will also update this file which wi get reflected in the git status so you will remember it.
This also means, that file gonna change, and it will show up in the `git status`. 

I understand potential frustration with discovering that our code base does not work with OTP-25, but that's does not look like a proper solution to me. Just add this file in your local environment if you feel that you need it.

2023-02-06 21:37 UTC, icehaunter commented on .tool-versions
> +elixir 1.13.4-otp-24
I'm arguing for making asdf a default tool for our systems. It's widely adopted and easy to use. And we very easily can use this as a source of truth for github actions. 

```yaml
steps:
  - name: asdf_install
    uses: asdf-vm/actions/install@v1
```

And in makefiles via https://www.gnu.org/software/make/manual/html_node/File-Function.html#index-file_002c-reading-from.

And it makes local development environments consistent easily

2023-02-06 21:43 UTC, icehaunter commented on .tool-versions
> +elixir 1.13.4-otp-24
Also, our codebase works with OTP25, but we mount local `_build` folder into docker which breaks with "module compiled for newer otp version" on any otp mismatches between container and local env. This means that full local dev cycle on a mismatched version involves rebuilding all dependencies twice - to run tests locally and in e2e. I understand why you decided to do this mount, and I suggest a fix for the problem at the local level instead of complicating the build process further.

2023-02-06 21:47 UTC, define-null commented on .tool-versions
> +elixir 1.13.4-otp-24
This clearly gets out of the scope of this ticket in my view. I suggest we remove this file from this PR and have a dedicated discussion regarding the issues and suggestions that you have found.

2023-02-07 08:12 UTC, thruflo commented
🍿

2023-02-07 09:51 UTC, icehaunter commented on mix.exs
> +          :error -> {:ok, "0.0.0-" <> String.trim(version)}
Ok, removed that

2023-02-07 10:10 UTC, icehaunter commented on Makefile
> +	git describe --abbrev=7 --tags --always --first-parent
I think I did what you wanted me to, not 100% sure

2023-02-07 10:10 UTC, icehaunter commented on integration_tests/satellite_client/Makefile
>  	rm -rf .yarn*
Done that

2023-02-07 10:28 UTC, icehaunter commented on .tool-versions
> +elixir 1.13.4-otp-24
I removed this file, although I disagree with the reasoning. To me, I was fixing an actual issue I encountered by using a ubiquitous tool to normalize developer environments. I feel like removing this file leaves the issue there for any contributors, bu we can take this into a separate discussion

2023-02-07 11:00 UTC, icehaunter commented on integration_tests/Makefile
> +	make -C satellite_client local-build
I'm having to battle against our own tooling here, for what I feel like no reason at all.
1. We use `node_modules` target which doesn't re-run if we have **any** node modules already installed, as Make doesn't care about checksums
2. This means that we cannot use any caching at all, as `pnpm install --frozen-lockfile` that would have rewritten the cache if frozen lockfile is changed just is not ran - `node_modules` target is satisfied already, right?
3. If I make `node_modules` target a phony target, then `pnpm install --frozen-lockfile` will rerun on every local build - probably not something we want, although it's ~500ms on my 
4. If I don't make `node_modules` a phony target and avoid having the `node_modules` in CI before we head into the docker environment, then we're wasting time each CI run to re-pull all the dependencies for no reason.

I don't know, running `pnpm install --frozen-lockfile` in CI feels like something I've done a thousand times and suddenly it's complicated for no obvious reason. What would be your proposed solution?

2023-02-07 15:08 UTC, define-null commented on .tool-versions
> +elixir 1.13.4-otp-24
What you are aiming for is commonly solved by specifying minimum version supported, or boundaries, in case some non-compatibility update to otp was introduced. This is trivially solved in erlang world with rebar3:
https://erlangforums.com/t/rebar3-restrict-compilation-to-a-specific-erlang-version/1584

But for some reason is not considered in elixir community important enough:
 https://elixirforum.com/t/specifying-minimal-erlang-version-in-mix-exs/39911

We can provide a little function to check that as part of the mix script I guess. But forcing every developer to use specifically "24.3.4" version of erlang, that should be accurate up to the patch and minor parts of the version is a pretty hard requirement.

2023-03-02 15:05 UTC, closed without merging